### ISSUE TITLE
[Bug] Show Prefix/Sufix/Base names levels don't work

### ISSUE THREAD

**Issue by Emefar** [DinoDevs/GladiatusCrazyAddon#103]
showPrefixSufixBaseLevels() function not working correctly. When i move this function on top, it is working. (https://i.hizliresim.com/8a039A.png)

**Comment by GramThanos** [comment]
Your image links does not work (you can copy paste the image here and it will automatically upload it).

**Comment by Emefar** [comment]
![screenshot_1](https://user-images.githubusercontent.com/36764954/48315214-5e2b4b80-e5e4-11e8-8fc6-e14b5384c4e9.png)

Only when i copy showPrefixSufixBaseLevels codes to top working.

**Comment by GramThanos** [comment]
Fixed on commit 9abe46508ac88c04c16037e895a774a6b7a910d2

**Comment by Emefar** [comment]
It is working now. Thanks ! :D
