### ISSUE TITLE
[Feature Request] Add spesific material

### ISSUE THREAD

**Issue by Emefar** [DinoDevs/GladiatusCrazyAddon#104]
I wanna add X material full orange. And Y material full red. I do not wanna add whole materials orange or red. I wanna choose.
If you can add this option, it would be nice :D
Just like this:

![ykzcwo](https://user-images.githubusercontent.com/36764954/48442287-d63d7100-e79e-11e8-8ceb-bd921db79525.png)

**Comment by GramThanos** [comment]
I think this is too difficult to be implemented.

**Comment by Emefar** [comment]
Yeap i know it is difficult. But.. YOU ARE GRAM THANOS :D :P You can do it everything about Gladiatus :D

**Comment by GramThanos** [comment]
Yeah, but I fist evaluate if the feature can be done in an easy reliable way, and this has many problems.

First you will have to select the item (so we would need a select interface)
Then we will have to check the storage to see if there are any materials of preference
Then we will have to export the materials to the packets
Where we will face the first big reliability problem, how to search the packets in a cross-language way that we will be able to find the materials we exported.
If we solve that, we will have to load the packet on the bag, so we will have to check for bag space before we start the hole process.
And lastly we will have to throw the material on the forge.

The weak points here are the packages and the bag.

A smarter simple brute force approach, would be to export all the other materials of the same quality to the packages, then call the "add from horreum" and lastly gather all the materials to the horreum from packages. But this will result in gathering materials on horreum that may be on packages before the operation.

The second way is reliable but we will have to inform the user in advance, that this action will gather all the forge resources to the horreum (or count them and re export them later).

**Comment by GramThanos** [comment]
Too much work... 😆

**Comment by Emefar** [comment]
On which server are you playing? And your name :p

**Comment by GramThanos** [comment]
I play on a couple of servers, but my main player and Guild mates are on s4-gr.
DarkThanos @ s4-gr](https://s4-gr.gladiatus.gameforge.com/game/index.php?mod=player&p=298498)

My players are 💩

**Comment by Emefar** [comment]
I am suprised. You are 118 level but only you have red weapon :( You should be red-man 👍

**Comment by GramThanos** [comment]
Well my focus is on the Addon and the Guild not on the game, I give most of my materials to the guild mates.

**Comment by Emefar** [comment]
I wish you're in my guild :D You are very supportive 👍

**Comment by Emefar** [comment]
How do you get server speed via js code? I am trying new things but i cannot get server speed :/

**Comment by Emefar** [comment]
> I play on a couple of servers, but my main player and Guild mates are on s4-gr.
> [DarkThanos @ s4-gr](https://s4-gr.gladiatus.gameforge.com/game/index.php?mod=player&p=298498)
> 
> My players are 💩

You are 131 now, and you have 2 red items :/

**Comment by FrutyX** [comment]
Man, I did read what Gram wrote... and I am not even gonna ask, closing this issue, for obvious reasons.
