### ISSUE TITLE
[Feature request] Show time until full expedition/dungeon points recovery

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#106]
Add time until a full recovery of expedition and dungeon points.

Proposed by [demon @ gladiatus.forum](https://forum.gladiatus.gameforge.com/user/1999-demon/)

**Comment by Emefar** [comment]
I did this request. I only cannot get server speed. Whole codes are ready! (Except server speed 😭 )

**Comment by GramThanos** [comment]
You can get the speed from the top of the page.

I think the costume is also saved in a gca storage somewhere.

**Comment by Emefar** [comment]
Okay i will try at this night, i hope i will succeess :D

**Comment by GramThanos** [comment]
Code to get server speed:
```javascript
let server_speed = parseInt((document.getElementById('header_game').getElementsByTagName('span')[7].textContent.match(/Speed x(\d+)/) || [null, '1'])[1], 10);
```

Code to get saved player's costume:
```javascript
let costume = gca_data.section.get("overview", "costume", false);
if (costume) ...
// Example: {code: 7, parts: 7, name: "Wrath"}
// More info on overview.js line 150
```

**Comment by Emefar** [comment]
I don't need costume but i solved different way to find server speed. But your function is better than mine.

**Comment by GramThanos** [comment]
I think you need to know the costume 

![image](https://user-images.githubusercontent.com/14858959/48571970-ef662f00-e910-11e8-9ddb-aaac4457fcf2.png)

**Comment by Emefar** [comment]
I solved that problem. I do not need :)

**Comment by GramThanos** [comment]
Yes you are right.

![image](https://user-images.githubusercontent.com/14858959/48572564-72d45000-e912-11e8-8afa-7eeeec4523ae.png)

**Comment by Emefar** [comment]
![image](https://user-images.githubusercontent.com/36764954/48572603-eed29600-e91a-11e8-8f29-0546967c0ddb.png)
Absolutely :)

**Comment by Emefar** [comment]
You can control my codes now, i sent ! 👍

**Comment by GramThanos** [comment]
Can I cancel them and let you create 1 pull request rather than 5?

**Comment by GramThanos** [comment]
The usual way is to commit your changes on your repo (https://github.com/Emefar/GladiatusCrazyAddon) and then make a pull request this repo> Any way, I see that you made the commits directly here, no problem.

**Comment by Emefar** [comment]
I cannot use good github, sorry for that. I tried your says but i did not do it.

**Comment by GramThanos** [comment]
Don't worry. It is just better in case you want to undo something.

**Comment by Emefar** [comment]
Thank you for that, i will learn GitHub 🤓

**Comment by GramThanos** [comment]
I compressed your code. I also took into consideration the first point timer.
Check when you are if the showing value makes any sense, maybe I missed something...

**Comment by Emefar** [comment]
I am going to add first time pointer tomorrow but you already did. I checked your code and it is very clean and nice. Congrats! 🎉 🎉 🎉

**Comment by Litvape** [comment]
> ![image](https://user-images.githubusercontent.com/36764954/48572603-eed29600-e91a-11e8-8f29-0546967c0ddb.png)
> Absolutely :)

How did you get 72 Expedition points?

**Comment by GramThanos** [comment]
Underworld 1st costume + 1 pacts buff + Cervisia
