### ISSUE TITLE
[Bug] Global Arena jquery ajax request returns 0 some times

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#107]
A user reported that sometimes the global arena shows the old error.

![image](https://user-images.githubusercontent.com/14858959/48524856-a075b680-e88a-11e8-9b3b-afba0b112ced.png)

That means something blocked the request.

**Comment by GreatApo** [comment]
Fixed: 8db96a5741c50361b4a1d9db04b4291885367527
