### ISSUE TITLE
[Feature request] Two target lists (one for each arena type)

### ISSUE THREAD

**Issue by halitak** [DinoDevs/GladiatusCrazyAddon#120]
I want two target list for arena and circus

**Comment by GramThanos** [comment]
I think that there is no reason to have 2 target lists, but maybe a need to have more options over the players you target (like the color selection).
Can you explain what limitations you face with the current system?
For example, you may want some players only to be highlighted on the turma arena and other only on the normal arena.

**Comment by halitak** [comment]
Yes, the color selection solves my problem.

Grammatopoulos Athanasios-Vasileios <notifications@github.com>, 29 Kas 2018
Per, 13:23 tarihinde şunu yazdı:

**Comment by GramThanos** [comment]
Ok, I think we can close this.
