### ISSUE TITLE
[Translation] Update Polish language

### ISSUE THREAD

**Issue by VanishSi** [DinoDevs/GladiatusCrazyAddon#121]
**Language name in English**
 - Polish

**Link the translation file here**

https://github.com/VanishSi/GladiatusCrazyAddon/blob/patch-1/source/core/locale/pl.js

**Comment by GreatApo** [comment]
I merged the translation, no conflicts or errors! However, I googled 1-2 strings and I was proposed some spelling corrections. Do a spell check if you have time ;)

**Comment by VanishSi** [comment]
Ok, so I have read my translation again.
I fix some language and stylistic errors.
I think that everything is stylistically and grammatically correct in Polish.

**Comment by Sorky96** [comment]
message_sent_success : "Wysłano wiadomość gildii",
"Wysłano wiadomość do gildii"
"Przejdź do Wojenna Hala Sław",
"Przejdź do Wojennej Hali Sław"

material_drop_chance : "{{number}}% szans na drop materiału"
"{{number}}% szans na upuszczenie materiału" 
If we translating it make it all good ;P

levels_you_can_see : "Możesz widzieć przedmioty od poziomu  {{min}} do poziomu {{max}}.",

 "Możesz widzieć przedmioty od  {{min}} poziomu do {{max}} poziomu {{max}}.",

category_global : "Generalne ustawienia",
"Ustawienia ogólne",

seems more accurately

category_global$forge_timers : "Wyświetl czas w kuźni/roztapiarki",
"Wyświetl czas w kuźni/roztapiarce"

That all I find :P these are mostly grammatical improvements ;) Hope I help you in any way :P

**Comment by GramThanos** [comment]
I updated the file from @VanishSi fork and then applied your suggestions (commit ba76754a299ce362b44197a906bb41659127274f).
I didn't replaced the `Możesz widzieć przedmioty od {{min}} poziomu do {{max}} poziomu {{max}}.` as it seems weird to me that it has the `{{max}}` 2 times, not that I know any Polish.

Report here any other changes 😃

**Comment by GramThanos** [comment]
We can reopen this for more fixes :)
