### ISSUE TITLE
[Feature Request] Green Rectangle Smelter Notification Pop Up Suggestion

### ISSUE THREAD

**Issue by TheWilliaf** [DinoDevs/GladiatusCrazyAddon#125]
When a user clicks on the green rectangle smelter notification pop up, automatically direct the user to the smelter page instead of making the smelter notification disappear.

**Comment by mehmetkaradeniz** [comment]
I've added this feature to my fork recently.
What I did was, add url support to notifications (When we pass url as an arguement it will go to url when you click the notification)

Right now it supports smelter, auction and durability notifications.
I can convert it into a pr after you guys reviewed it.

Here is the [commit](https://github.com/mehmetkaradeniz/GladiatusCrazyAddon/commit/6a2cff0dcd57352f9443b58977167df0470b2c61?diff=split)

**Comment by GramThanos** [comment]
@mehmetkaradeniz feel free to create a pull request. I will have a look into your code.

**Comment by GramThanos** [comment]
@mehmetkaradeniz feel free to create a pull request. I will have a look at your code.

**Comment by mehmetkaradeniz** [comment]
@GramThanos just sent the pr
