### ISSUE TITLE
[Bug] Dice game timer not starting

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#129]
Dice game timer does not start until page is refreshed.

**Comment by FrutyX** [comment]
Very ancient Issue.

Since it's now in-game, I was able to test it, either Gram fixed it or it fixed itself.

Proof (no refresh):
![proof](https://user-images.githubusercontent.com/23278552/146462620-281df019-61c6-4dbe-b671-e081a4d91500.PNG)
