### ISSUE TITLE
Problems with gladiatussimulator.

### ISSUE THREAD

**Issue by Thetawaves666** [DinoDevs/GladiatusCrazyAddon#130]
**Describe the bug**
The simulator on https://gladiatussimulator.tk does not show the provinces on Argentina's server.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/37487971/50848406-fdee2700-1352-11e9-9478-5e0d6309f535.png)

**Browser info (optional)**
 - Windows 8.1
 - Chrome

**Comment by GramThanos** [comment]
I forced updated the servers. Check again if it was fixed.
(You may need to clear the cache using `Ctrl+F5`)

**Comment by Thetawaves666** [comment]
It works now. Thanks.
