### ISSUE TITLE
[Bug] Additional Market Buttons Lead to the Wrong Webpages

### ISSUE THREAD

**Issue by TheWilliaf** [DinoDevs/GladiatusCrazyAddon#131]
![image](https://user-images.githubusercontent.com/20340230/51501627-b3cc6300-1da0-11e9-8d42-9ce28ee09af1.png)

When a user clicks the button with the image of Yellow powder it takes them to the Reinforcements market tab and not the Upgrades market tab. Also, when a user clicks the button with the image of a Flacon it directs the them to the Upgrades market tab and not the Reinforcements market tab.

**Comment by GramThanos** [comment]
Aaa... the code you seek find you will...
The file `GladiatusCrazyAddon/source/core/source/global.js` check you should!
At line 1962 look you must!

**Comment by TheWilliaf** [comment]
@GramThanos I believe I have fixed it: https://github.com/DinoDevs/GladiatusCrazyAddon/compare/master...TheWilliaf:patch-1

A quick question for you what does the -8 and -7 in the class scope on lines 1964 and 1965 respectively symbolize?

**Comment by GramThanos** [comment]
These are the classes of the items to be used as button icons.

**Comment by GramThanos** [comment]
So the question now is:
"Was the links wrong... or the icons?"

😆
