### ISSUE TITLE
[Bug] I can't put golden craft item in trade market.

### ISSUE THREAD

**Issue by sebek815** [DinoDevs/GladiatusCrazyAddon#133]
I can't put golden item into market unles I turn off the addon. Same with guild market.

**Browser info (optional)**
Mozzila

**Comment by GramThanos** [comment]
Is it working if you set "Toggle button changing sell price always to 1 gold" to off?
You can find it under Profile > Addon Settings > Market

Also can you please let me know if there is an error in the console, you can do that by right-clicking the page, select "Inspect Element" and on the panel that opens, click on the console tab. Is there any error?

**Comment by sebek815** [comment]
Hi @GramThanos,
yes, it's working now, I appreciate for your herlp

**Comment by GramThanos** [comment]
I tested it with golden hammer and I couldn't reproduce the problem.
