### ISSUE TITLE
[Bug] Advance packages filter, locale problem

### ISSUE THREAD

**Issue by Ritmisz** [DinoDevs/GladiatusCrazyAddon#135]
**Describe the bug**
misspelled filters in lithuanian in items 'Gydymas', filter - 'Gydymasis' also items 'Grėsmė', filter - 'Grasinimas'

**Screenshots (optional)**

http://prntscr.com/mi37re

**Browser info (optional)**
 - OS: [e.g. Windows, Linux, Mac, Android, iOS]
 - Browser [e.g. Chrome, Firefox, Opera, Edge]

**Comment by GramThanos** [comment]
The stats locale are copied from the stats table under the player.
So, if I understand correctly

`Threat` is `Grasinimas` and on the items is `Grėsmė`
`Healing` is `Gydymasis` and on the items is `Gydymas`

Am I correct?

**Comment by Ritmisz** [comment]
Yes, it called differently, in lithuanian
