### ISSUE TITLE
[Translation]:zh-Chinese traditional 20190310

### ISSUE THREAD

**Issue by smoothGrace** [DinoDevs/GladiatusCrazyAddon#136]
**Language name in English**
-language:zh-Chinese traditional 20190310

**Link the translation file here**

[zh.zip](https://github.com/DinoDevs/GladiatusCrazyAddon/files/2949353/zh.zip)

**Comment by GramThanos** [comment]
Merged 313c54d989c1f2132e9f36ad07bcfdf5e1e638b0
Thank you!
