### ISSUE TITLE
[Bug] choose language to blank and save cause error

### ISSUE THREAD

**Issue by smoothGrace** [DinoDevs/GladiatusCrazyAddon#137]
**Describe the bug**
setting-language- selected blank(on top). -save

most of function will disabled. even the addon interface will disappear at personal-account page ...

**Screenshots (optional)**
![11](https://user-images.githubusercontent.com/29204759/54486213-33b60b80-48c0-11e9-8073-38ba654d3ead.png)

**Browser info (optional)**
 - OS: [windows 7]
 - Browser [Chrome,]
 - Version [4.1]

**Comment by GramThanos** [comment]
I will look into it.

**Comment by GramThanos** [comment]
Patched on 8cb1f1b5f1ec1a92c0d344aad00ee41beb96517b

You can temporary fix it bu running the command bellow at the console (ctrl+shift+j opens the console)
```javascript
gca_locale._setLang('en');
```
