### ISSUE TITLE
[Feature Request] double click to buy/sell split into two function

### ISSUE THREAD

**Issue by smoothGrace** [DinoDevs/GladiatusCrazyAddon#138]
**Brief feature description**
now, double click to buy /sell on merchant is a combine function and control by same switch,it is dangerous when moving system generated items in merchant inventory ,it has a small chance that player wrong double click on ruby item and cost rubies.

it's better to split to two control switch, existing only control sell,and keep current setting, a new one control buy, default set off.

**Comment by GramThanos** [comment]
We can only enable double click on items that you have previous sold to the merchant.

**Comment by GramThanos** [comment]
Starting from v4.2.0 you can not buy items with double click.
