### ISSUE TITLE
[Bug] Separate buttons for Auto and 1gold market sales

### ISSUE THREAD

**Issue by MrMitza** [DinoDevs/GladiatusCrazyAddon#139]
Can you make two separated buttons for Auto and 1 gold?
https://prnt.sc/nj1biz
Some times when i press to Auto, i have to look for a position of some sort, for the button to become active (maybe it's happening only to me)
Its a minor issue, i know :)

**Comment by GramThanos** [comment]
They are already 2 buttons but, due to a bug on the Firefox version of the addon, the item's fee overrides the buttons and it is hard to press them. It is patched on the developer version.
