### ISSUE TITLE
[Bug] Wrong language

### ISSUE THREAD

**Issue by Adehmar1** [DinoDevs/GladiatusCrazyAddon#144]
Hello! I am currently playing on a spanish server but everything from the addon is on arab. When I play on a german server, it too shows everything in arab. Why is that?

I have everything on english.

**Comment by GramThanos** [comment]
You may change the language from the settings

![image](https://user-images.githubusercontent.com/14858959/58660528-52a83380-832e-11e9-9134-9013b56dbce8.png)
![image](https://user-images.githubusercontent.com/14858959/58660560-63f14000-832e-11e9-8727-295b831295f6.png)
![image](https://user-images.githubusercontent.com/14858959/58660581-6e133e80-832e-11e9-9e99-4ffbbcc97083.png)

Normally, the addon detects the server language and apply the appropriate language by default.

**Comment by GramThanos** [comment]
We can reopen this if the problem appear again.
