### ISSUE TITLE
Extended auction search

### ISSUE THREAD

**Issue by ranter13** [DinoDevs/GladiatusCrazyAddon#145]
Would be nice if you could input a few preffixes/suffixes in the auction filter box and only show these items. What I am asking is an extension to the normal auction filter functionality, just so it supports multiple words. For example, say you want to search for "Lucius" and "Delicacy" and show items that contain one or the other word. In that case you could type something like "Lucius, Delicacy"

**Comment by GreatApo** [comment]
This will require the addon to request all the items in the auction and that will cause tremendous server load. On the other hand, this can be "easily" implemented by Gameforge directly.
