### ISSUE TITLE
[Bug] Simulator invalid blocking chance

### ISSUE THREAD

**Issue by NotLampard** [DinoDevs/GladiatusCrazyAddon#147]
I think that since the last update the calculation parameters have changed with respect to "the possibility of blocking"

**Before:** 

Total Blocking value = (Strength/10) [round down] + Block value from items

Chance to block a hit = (Blocking value * 52 / (Character Level-8 )) / 6

**Now**

I do not know.

**Comment by NotLampard** [comment]
**I will try to express myself better**
In the first image I show the probability of blocking that the adversary possesses. ( 2% )
![1](https://user-images.githubusercontent.com/53106131/62236370-56474d80-b3a5-11e9-851f-0c5eb9ec2408.png)

In the second image I show the results of the battle. And the probability of blocking that the same adversary has in battle. ( 28% )
![Screenshot_1](https://user-images.githubusercontent.com/53106131/62236560-b3db9a00-b3a5-11e9-96a4-f0ad70abaf52.png)

I discovered that it is due to the difference in levels. I am 42lvl and the rival 55lvl.

**Finally, my query is:
Does the simulator take this into account?**

**Comment by GramThanos** [comment]
I didn't replied earlier because I forgot to check my reports :P.

I will check the simulator's code, I don't remember what is does when there is a big level difference.

**Comment by NotLampard** [comment]
Thanks!!

**Comment by GramThanos** [comment]
So it seems that the new formula is:

MIN(50, ROUND( (block_points * 52 / (level - 2)) / 6 ) + MAX(0, level - opponent_level) * 2 )

I will check tomorrow it the formula is the same on the turma battle and I will update the Simulator.

**Comment by GramThanos** [comment]
I think the same formula apply on Turma battles

**Comment by GramThanos** [comment]
The block formula was corrected for all the simulator battles. If there is any new info, reopen this issue.
@NotLampard Thank you for reporting the problem.
