### ISSUE TITLE
[Feature Request] Forge items generator/simulator

### ISSUE THREAD

**Issue by NotLampard** [DinoDevs/GladiatusCrazyAddon#149]
Simulate forge items. Compare result according to level, color, prefix and suffix.

**Comment by GramThanos** [comment]
Something like this https://en.gladiatus-tools.com/equipment ?

**Comment by NotLampard** [comment]
I love u!!

**Comment by GramThanos** [comment]
Don't love me :P
This webpage was made by [Michalus](https://forum.gladiatus.gameforge.com/user/69-michalus/)
