### ISSUE TITLE
I cannot enter the Global Arena

### ISSUE THREAD

**Issue by NotLampard** [DinoDevs/GladiatusCrazyAddon#150]
I cannot enter the Global Arena. The enemies do not arise

![111](https://user-images.githubusercontent.com/53106131/63535920-f9910b80-c4e8-11e9-9a4b-bfba78478136.png)

https://s21-ar.gladiatus.gameforge.com/game/index.php?mod=player&p=19056

**Comment by GramThanos** [comment]
I will look into it.

**Comment by GramThanos** [comment]
I think I fixed it. My mistake...

**Comment by NotLampard** [comment]
Thank you!!
