### ISSUE TITLE
Suffix error

### ISSUE THREAD

**Issue by NotLampard** [DinoDevs/GladiatusCrazyAddon#152]
![ta mal](https://user-images.githubusercontent.com/53106131/64069915-06210c80-cc2b-11e9-9c83-51b584b86e67.png)

The data isn't correct.   %Charisma is missing

de la muerte: 
Strength +4, 
Charisma +5,
**Charisma +28%,**
Intelligence -3%,
Critical attack value +16,
Level 36

The problem is solved when I change to "community: USA"

_Next time could I publish in Spanish? because my english is not good. And I must use the google translator. LOL_

**Comment by GramThanos** [comment]
We are not the gladiatus-tools site developers. I vuess, you can use their contact page to report bugs of share you thoughts https://en.gladiatus-tools.com/contact
