### ISSUE TITLE
Buy all button in Auction/Market

### ISSUE THREAD

**Issue by Igrasz** [DinoDevs/GladiatusCrazyAddon#153]
Additional button which has a possibility to buy all items in Auction/market for only 1 type of item only in case if we have enough gold to buy all.
If we have bid already, break the price by ourselves.

**Comment by GreatApo** [comment]
I see limited cases where this can be used. Additionally, interacting like this in auction would be aggressive against other players thus I don't think it is a good idea.

Can you explain a usual situation where this is useful but not aggressive?

**Comment by GramThanos** [comment]
I am also not a fun of the idea. You should ask Gameforge to implement such features.

**Comment by Igrasz** [comment]
Hey there,

Many thanks for fast response. As you have written already it would be agressive in every single cases when would be normal activity on a server. 

We can imagine, but it is not only a imagination but a holy truth also, on a older serveres there are moments when only few players are online. In this time the possibility will not be treated as an aggresive.

I think it is only my laziness… 😊


Od: Grammatopoulos Apostolos
Wysłano: środa, 4 września 2019 12:44
Do: DinoDevs/GladiatusCrazyAddon
DW: Igrasz; Author
Temat: Re: [DinoDevs/GladiatusCrazyAddon] Buy all button in Auction/Market(#153)

I see limited cases where this can be used. Additionally, interacting like this in auction would be aggressive against other players thus I don't think it is a good idea.
Can you explain a usual situation where this is useful but not aggressive?

**Comment by GreatApo** [comment]
> Hey there, Many thanks for fast response. As you have written already it would be agressive in every single cases when would be normal activity on a server. We can imagine, but it is not only a imagination but a holy truth also, on a older serveres there are moments when only few players are online. In this time the possibility will not be treated as an aggresive. I think it is only my laziness… 😊 

Well, this is indeed a fact. You could buy the whole auction and only 2-3 players will notice it :P
A global merge is what the game needs. Anyway, I am closing this issue.
