### ISSUE TITLE
Simulator Expedition improvement and Turma talk

### ISSUE THREAD

**Issue by rodrigomoreda** [DinoDevs/GladiatusCrazyAddon#156]
create an option to change skill, armor, block, as it does in arenas, before calculating the percentage of victory against the expedition beast.
And would you like to know what you need to place new animals from Britain?
Maybe I can help
I made a calculator in excel to know what is worth doing with the circus class items, there is only one thing I do not know, is the threat, how you formulate it?
You do a great job, thanks.

**Comment by GramThanos** [comment]
The expedition simulator needs a lot of improvements in general. Now, we added static stats of each enemy (from a random battle, or based on average), but the correct way it to generate random stats (but we don't know the min max and the distribution of the stats).

So, right now, to add an enemy, just a photo of the enemy's stats is enough, not perfect but better than nothing.

Lets now talk about the turma threat. We don't know how the Gladiatus handle the threat, so I personally implemented a WoW like way (hahaha). All players has a starting threat, the tank gets a x10 multiplier. Then, we basically normalize all the threats to generate the chance each player has to be attacked by the enemy. This way of using the threat game me results close to the Gladiatus' reports (in scores).

**Comment by rodrigomoreda** [comment]
of the enemies that open at level 150, I can make it available myself, in a few hours (because I'm about to level up) haha
of the others from 160 to 180, I will talk to the Top of my country.

but overall the site: https://gladiatus.gamerz-bg.com/britannia-expeditions
has the information of the expedition chief.
the 3 normal animals are not very useful after you start hitting only the bosses.


about the threat i'll do some tests with the information you gave me, thank you very much.

**Comment by rodrigomoreda** [comment]
this is the second critter of the nv 150 expedition
Camp Cassivellaunus - Mercenário
https://uploaddeimagens.com.br/imagens/mrece_nv_162-png
https://uploaddeimagens.com.br/imagens/merce_nv_163-png
https://uploaddeimagens.com.br/imagens/merce_nv_164-png
https://uploaddeimagens.com.br/imagens/merce_165-png
https://uploaddeimagens.com.br/imagens/mercenario_nv_166-png


once you get the next one, 1 from each level will send you too

**Comment by rodrigomoreda** [comment]
1º 
https://uploaddeimagens.com.br/imagens/cavaleiro_da_carruagem_nv_160-png
https://uploaddeimagens.com.br/imagens/cavaleiro_da_carruagem_nv_161_-png
https://uploaddeimagens.com.br/imagens/cavaleiro_da_carruagem_nv_163-png
https://uploaddeimagens.com.br/imagens/cavaleiro_da_carruagem_nv_164_-png

**Comment by rodrigomoreda** [comment]
3º
https://uploaddeimagens.com.br/imagens/fflur_164-png
https://uploaddeimagens.com.br/imagens/fllur_166-png
https://uploaddeimagens.com.br/imagens/fflur_nv_167-png
https://uploaddeimagens.com.br/imagens/fflur_168-png

**Comment by rodrigomoreda** [comment]
and last and most importantly
https://uploaddeimagens.com.br/imagens/cassivanius_166-png
https://uploaddeimagens.com.br/imagens/cassi_167-png
https://uploaddeimagens.com.br/imagens/cassivanius_168-png
https://uploaddeimagens.com.br/imagens/cassivanius_169-png
https://uploaddeimagens.com.br/imagens/cassi_170-png

**Comment by GramThanos** [comment]
I calculated the averages for each one based on your data (min/max for their damage) and I added the data on the web page.

Keep in mind that the expedition simulator may not handle correctly the block / critical / avoid critical chances (we don't have / haven't calculated the equivalent points of each enemy to generate different chances for each player). This may only be a problem on enemies with high chances or if the player and the monster have a big level difference (assuming that the new block formula that involves level difference applies on the expeditions too).

**Comment by rodrigomoreda** [comment]
my calculator that i made in excel to get a sense of which items are better
there's something wrong in the class circus
How would I see the formulas you used to come up with a simulation of your circus?
or look at mine and see what's wrong?
mine is in excel

**Comment by GramThanos** [comment]
I can send/show you our php code, if you can read algorithms.

**Comment by rodrigomoreda** [comment]
send me then please
rodriguin_moreda@hotmail.com
I don't understand php code, but I have some friends who understand, they help me
thanks

**Comment by egaznep** [comment]
Maybe the add-on can collect data from users' fights (if player opts-IN for this study), then one can possibly try logistic regression or some other type of statistical method to increase the accuracy of the simulator. Establish the current simulator as a prior, then let the data "speak the truth". 

Would you be interested in such a study?

Remark: The data collection could be done completely anonymously. Only the stats of the attacker and the enemy can be collected and it would be enough.

**Comment by GramThanos** [comment]
From the data side this is correct. But we also need to uncover the turma algorithm.

**Comment by FrutyX** [comment]
Closing, if you want to continue someday, feel free to do in #308, unless it needs a New issue.
