### ISSUE TITLE
New Filter for packages

### ISSUE THREAD

**Issue by Tharacius** [DinoDevs/GladiatusCrazyAddon#159]
I want to be able to 'favorite' a suffix or a prefix, so that when I see a item drop with given suffix or prefix it has a small indication that it's among my favorites(perhaps like a star or some symbol in its tooltip or icon).

When I open my packages, I want to be able to sort by 'Favorites' so that it displays all the items 
 that have a suffix or a prefix that I have in my favorites list.
Perhaps add an Import option so we can import underworld suffixes/prefixes from the gladiatus-tools page.
This is namely convenient for Underworld items, having them all in one place, and for favoriting items that you want to smelt for their resources.

**Comment by FrutyX** [comment]
Merged all "filter" request issues into one, from now, please use #343.

Closing.
