### ISSUE TITLE
inconsistency in simulator percentage Expedition

### ISSUE THREAD

**Issue by rodrigomoreda** [DinoDevs/GladiatusCrazyAddon#161]
inconsistency in simulator percentage
Me vs Cassivelanius
the simulator says: Player
<skulachado @ s33-br>
83.05%
VS
Enemy
Britannia / Camp Cassivellaunus / Cassivellaunus
16.95%

But in practice, I'm getting between 96 and 99% win

I'm finding this difference too big

hug

**Comment by GramThanos** [comment]
Yes, the difference indeed is big, according to the +-5% error margin that we usually see in statistics.

**Comment by rodrigomoreda** [comment]
I still can't understand how you calculate the percentage
but on my excel calculator i found out that there was something wrong, i will share the information, maybe you don't know.
I found that:
When the attack is blocked, it is not necessarily 0, it divides the damage by 2, and then the armor is subtracted.
in my fight against Cassivelanius, when my blow is blocked, there is still some damage
but when he attacks me I almost always block

**Comment by GreatApo** [comment]
> I still can't understand how you calculate the percentage
> but on my excel calculator i found out that there was something wrong, i will share the information, maybe you don't know.
> I found that:
> When the attack is blocked, it is not necessarily 0, it divides the damage by 2, and then the armor is subtracted.
> in my fight against Cassivelanius, when my blow is blocked, there is still some damage
> but when he attacks me I almost always block

That is indeed interested. I think simulator zeros on block, but it was coded many years but and I can't verify that without looking the code.

**Comment by FrutyX** [comment]
Closing, if you want to continue someday, feel free to do in #308, unless it needs a New issue.
