### ISSUE TITLE
Custom market sell prices

### ISSUE THREAD

**Issue by Oligarchas** [DinoDevs/GladiatusCrazyAddon#166]
When selling an item in the market, you have 3 options: auto price, 1 gold and item's value.

Could you add more custom options? For example I would need 50k, 100k, 200k, 500k, 1m and 2m sell options. 

Personally I find it annoying having to type the value manually every time, especially when I'm wearing hard underworld costume. With that costume I make 20m+ gold a day and I have to constantly repackage my gold using guild's market - https://imgur.com/a/HdHlzOh

**Comment by GreatApo** [comment]
I would suggest custom values to be added in settings (eg. Input custom sell prices: 100, 99, 3000) which will then be available in market as a drop down menu.

**Comment by FrutyX** [comment]
This.

I don't want to bump these older requests, but exactly this is, what active players with underworld costumes need.

Would use it every single day 100%.

**Comment by GramThanos** [comment]
I like this idea, I also had similar ones.
It is just too boring to be implemented hahaha

**Comment by Zitronenen** [comment]
Is it possible to add an "On / Off" switch here?

**Comment by FrutyX** [comment]
> * I think we should rewrite 1m to 1kk

Sorry, but I have to disagree with that, I prefer M much more, it's clearer.

**Comment by SleepingShadow-bit** [comment]
I need your opinion about for about 2.500.000.
![IMG_20220101_203211](https://user-images.githubusercontent.com/8767665/147858853-577ba54a-e464-45a8-b28f-c3f8729c52dd.jpg)

**Comment by FrutyX** [comment]
2.500.000 is 2500k, well, that's kinda confusing.

**Comment by FrutyX** [comment]
`.replace(/00000/,'m')` will make it only show as 25m.

![what-excuse-me](https://user-images.githubusercontent.com/23278552/147919104-6a3d5f24-3123-44fb-856d-a1155d04dbcb.gif)

**Comment by FrutyX** [comment]
`.replace(/.00000/,'m')` shows as 2m, which is the closest I could get without rewriting too much of the code.

**Comment by GramThanos** [comment]
Time for RegEx-Fu:

`.replace(/(\d)00000$/,'.$1m').replace(/(\d\d)0000$/,'.$1m')`

**Comment by FrutyX** [comment]
Hmmm, not sure if I am doing it right, maybe you should see for yourself.

For example, 2.500.000 and 500.000 has the same amount of "0", which means there always be a conflict between M's and K's.

**Comment by GramThanos** [comment]
RegEx-Fu upgrade!

`custom_mode_label.textContent = "💰 " + ((price + '').replace(/000000$/,'m').replace(/(\d)(\d)00000$/,'$1.$2m').replace(/(\d)(\d\d)0000$/,'$1.$2m').replace(/000$/,'k'));`

**Comment by FrutyX** [comment]
It looks perfect now.

![patch](https://user-images.githubusercontent.com/23278552/147944050-e573f9ee-410e-4224-b947-b2f0d03ab61e.PNG)

**Comment by FrutyX** [comment]
I've pushed it out, @SleepingShadow-bit you can test it too.

**Comment by SleepingShadow-bit** [comment]
![IMG_20220103_163449](https://user-images.githubusercontent.com/8767665/147949612-9a2fcea1-3920-4c67-bdb4-97a63418104e.jpg)

Great Thanks

**Comment by FrutyX** [comment]
I don't see any other required action here, closing, re-open if needed.
