### ISSUE TITLE
[Feature Request]  Hide auction items

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#167]
Hello there,

so,when it comes to saving our gold into amulets and rings,you are usually buying these things that got rubies value above 40 (that's why there is the "hide your gold here" text ,right) but instead of that,you should actually give us an option into auction settings,to hide all other amulets/rings under 40 rubies , it will be much clearer and you will never missclick on a wrong rubies value.

That's it,hopefully it's possible to make,I believe that it will be great for anyone who is saving their gold via auction items.

Thank you! :)
(Btw,great job on the Addon so far)

**Comment by GreatApo** [comment]
I would suggest a button at the top of the auction switching it on and off so that a player can see that this feature is enabled/disabled.

**Comment by mehmetkaradeniz** [comment]
Probably not the best way to implement this, but can be used from browser's developer console until this feature is implemented.

`jQuery(".auction_bid_div:not(:has(.gca-auction-good-price))").closest("td").hide()`

Also requires "Analyze items' prices" option is turned on I'm guessing.

**Comment by FrutyX** [comment]
Nice to see you really did it ! It's simple yet very useful,thank you for that.

It has one flaw tho,when you refresh the auction page,it will reset,so you have to set it every time you refresh the page.

**Comment by GreatApo** [comment]
Done
