### ISSUE TITLE
Quality and below filter on packages

### ISSUE THREAD

**Issue by C-h-e-s-h-i-r-e** [DinoDevs/GladiatusCrazyAddon#168]
**Brief feature description**
Add option in packs filters to see items ex. [Blue] quality and below (in this case u will see only blue and green) so u can easier sell junk items after finishing Underworld right now u can only filter [quality] and up so it will help if u add option to filter [quality] and below.

**Comment by GramThanos** [comment]
This would require the addon to crawl a number of package pages which will produce quite a load on the game server. We avoid features that may produce such a server load as they will result in a overall slower server responses.

**Comment by FrutyX** [comment]
This is overkill (for the servers)... Should we close this? I'll leave that up to Gram.

**Comment by GramThanos** [comment]
Yes, I don't think we should do something like that.
