### ISSUE TITLE
Auto sell

### ISSUE THREAD

**Issue by hendek95** [DinoDevs/GladiatusCrazyAddon#169]
Thanks for the extension it s very useful. I want to say something. We re trying to keep our gold with buying necklace or rings. But really hard to sell them. Can u add? Maybe only one page(Armor or weapon) if we have 2 clean pages maybe it can work?

**Comment by GramThanos** [comment]
We don't implement such actions to avoid getting the extension banned.

Also we try to minimize the requests to the server as it seems that they can't take it. Implementing such a feature would mean 8 to 40 requests per click... this may crash the server on events where everyone is selling items.

The repack problem can only be solved by Gameforge.
