### ISSUE TITLE
Installation of 4.2.1 Beta on Firefox

### ISSUE THREAD

**Issue by hejdannymej** [DinoDevs/GladiatusCrazyAddon#170]
**Describe the bug**
Hi, I'm trying to install the 4.2.1 Beta on Firefox but can't seem to find the .xpi file anywhere in the extracted folder.

**Comment by GramThanos** [comment]
Firefox let you load unpacked extensions as "temporary" extension. To do that, you can go to your extensions page, click the gear icon, and click "debug extensions". There you can load the extension source by selecting the manifest.json file. If you close the Firefox, you will have to do the process again.

**Comment by hejdannymej** [comment]
Thank you for the tips. 
Do you have any plan of releasing the 4.2.1 soon?

**Comment by GramThanos** [comment]
I have no idea... we haven't planned anything...

**Comment by GramThanos** [comment]
Version released! :D

**Comment by GramThanos** [comment]
Anyone who manually Firefox's offline version will have to uninstall it and get the version from store to get automatic updates.
