### ISSUE TITLE
[Feature Request] Market 'sell' button as primary button

### ISSUE THREAD

**Issue by egaznep** [DinoDevs/GladiatusCrazyAddon#171]
This is a very simple, yet extremely useful feature.

By setting the 'sell' button as a primary button, one can directly press 'enter' on keyboard to perform the selling. This would speed up the process of selling multiple items, as currently one constantly moves between the items and the selling panel. On the other hand, with this feature, one can dobule click the items & enter and total mouse trajectory would be maybe 10 times shorter.

**Comment by GreatApo** [comment]
Done, commit 57c98298d8b6adf02db2a5f7b8c8296e986b08a0
