### ISSUE TITLE
[Feature Request] Ability to disable 'buy with rubies' button in Auctions page

### ISSUE THREAD

**Issue by egaznep** [DinoDevs/GladiatusCrazyAddon#172]
I am very scared of accidentally pressing the 'buy with rubies' button only to spend say 50 rubies which I patiently saved to buy Centurio on some event day to a green-quality armor which would be of no use!

For almost all players, I think being able to purchase the items with rubies is redundant. There should be an option to disable that button from appearing.

**Comment by GreatApo** [comment]
Unfortunately we are not able to interfere with way with Gladiatus' monetization this way (remove buttons etc). Despite that, I remember some years ago we had a verification notification before using rubies. Maybe we could revive that feature...

**Comment by egaznep** [comment]
That actually still exists and works, and saved my precious rubies after I
suggested this feature. Also, I was going to re-buy some pendants I sold to
the alchemist (by using the double-click). I carelessly double clicked to
something is on sale with rubies. It prevented me from buying it by saying
this costs rubies. But I think by drag and drop I can buy it.

You guys are awesome!

18 Nis 2020 Cmt 20:33 tarihinde Grammatopoulos Apostolos <
notifications@github.com> şunu yazdı:

**Comment by GreatApo** [comment]
This request will be closed since the game already has a verification windows when clicking the "buy now" button in auction.
