### ISSUE TITLE
Want to help

### ISSUE THREAD

**Issue by jansedlon** [DinoDevs/GladiatusCrazyAddon#174]
Hi! I've just found this repo and it looks amazing! I would like to help you somehow. I'm a frontend developer (mostly React) as well as backend developer + some devops things. I've looked at the code and it's quite complex and your developer docs are in progress. Is there any way that you could introduce me how this works? Thanks!

**Comment by GramThanos** [comment]
The main idea is that each page has 1 script that was built for the features of that page.

**Comment by FrutyX** [comment]
@Zitronenen you think you can extract this useful info that Gram wrote and add it to the docs (developers)? You created most them, so it is better you do it, so we don't break your format.

You can request an pull request, I'll have a look at it.

Also there is this #175, talk about open sourcing, you can read I know, but to sum it up, they are willing to share the code only if someone will actually contribute to it.

The goal here is to create a little FAQ for developers, and you don't have to look for it everywhere in different Issues.

But only if you want, I am not forcing you into it :-).

**Comment by FrutyX** [comment]
From now on, refer to:
https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/developers/for-developers.md

Closing.
