### ISSUE TITLE
Open sourcing the simulator?

### ISSUE THREAD

**Issue by Croverit** [DinoDevs/GladiatusCrazyAddon#175]
Hello,
Thank you guys for this great work.
I wonder if you have plans to open source the simulator so people can contribute in improving it.

**Comment by GramThanos** [comment]
Personally speaking, I am not against open sourcing the simulator but I have some concerns, like "what if someone use it for bots?". Also, currently we (me and GreatApo) don't have time to work on the add on... so there is no time to maintain other projects. Lastly, I don't think anyone will eventually contribute, as was the case with the "GladiatusPlayerStatsAPI" that is part of the simulator.

So... we haven't discussed it, personally I am not against it, but right now I don't have the time to do it.

**Comment by Croverit** [comment]
Thank you for your response, and I hear you.
But for the bot part, you already know that anyone can scrape your web simulator and automate the process. That means, keeping the code source closed won't stop the botters but will just make it a little bit hard for them.

But I understand the point where you don't have time for it. I just hoped that this knowledge (the simulator) will stay and be maintained in those last days of this buggy old game.

**Comment by GreatApo** [comment]
We don't have the problem releasing the code but I agree with Thanos, I don't think anyone will contribute. Additionally, I don't see the game getting any decent update that will make the simulator outdated.

Anyway, if anybody wants to look and improve the simulator code let us know.

**Comment by DkVagabonden** [comment]
First of all, glad to see ya still around!.
Long time ago i used to translate the Addon to danish, and came back to gladiatus some time ago. 

Would love to take a look at the simulator to see if what i remembered is correct, but in the end i guess im in for a surprise. 
Mostly interested in the formulars to see if anything have changed from my own data i found and if so, how and why. 
Reading the code shouldn't be any issue. 

Please let me know if its possible.

**Comment by GreatApo** [comment]
> @GreatApo
> 
> First of all, glad to see ya still around!.
> Long time ago i used to translate the Addon to danish, and came back to gladiatus some time ago.
> 
> Would love to take a look at the simulator to see if what i remembered is correct, but in the end i guess im in for a surprise.
> Mostly interested in the formulars to see if anything have changed from my own data i found and if so, how and why.
> Reading the code shouldn't be any issue.
> 
> Please let me know if its possible.

I don't know how I missed this... I am sorry. Anyway, for anyone still interested, the most complete Gladiatus formulas manual is this: https://gladiatus.gamerz-bg.com/article?id=49

**Comment by FrutyX** [comment]
From now on, refer to:
https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/developers/for-developers.md

Closing.

**Comment by GreatApo** [comment]
For anyone still interested, the simulator is now open source:
https://github.com/DinoDevs/GladiatusBattleSimulator
