### ISSUE TITLE
Online players bug that was "fixed" 

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#176]
Hello,

yesterday,our guild name/tag was changed and the "display online players" function is not loading at all, I have found out that this bug was fixed by Mr.Thanos,it was reported on Gladiatus forums ( [https://forum.gladiatus.gameforge.com/forum/thread/263-gladiatus-crazy-add-on/?postID=142245#post142245](url) ),it's completely the same issue,only problem is,it's still here.

It was supposed to be fixed in this code:

[https://github.com/DinoDevs/GladiatusCrazyAddon/commit/6149f6916219d1873c67c8843254babdb11ca1ed](url)

Unfortunately,it does not work,our clan tag is `[[*A/S*]]` ,i think the "/" symbol is new and was not there before,maybe that's the thing that is making the trouble here (just guessing).

Addon ver. : v4.2.0
Browser: Google Chrome v83.0.4103.97
Console error:
`al.php:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
global.js?4.2.0&built=1591685310551:1171 Uncaught TypeError: Cannot read property '1' of null
    at Object.success (global.js?4.2.0&built=1591685310551:1171)
    at j (jquery.js:3)
    at Object.fireWith [as resolveWith] (jquery.js:3)
    at x (jquery.js:3)
    at XMLHttpRequest.b (jquery.js:3)`

Thank you for looking into this,I really miss the online players function,we now have the guild name change on cooldown,so we have to wait to change it,but a hotfix wouldn't be bad at all too :) .

**Comment by GramThanos** [comment]
Hello @FrutyX ,
the fix was introduced on version 4.2.1 (current change log [here](https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/PROGRESS.md)) that is not out yet (other things got inthe way).

**Comment by FrutyX** [comment]
Oh,this fix is not out yet,I see.

Hopefully you will find some time and strength to push this update out one day :).

Closing.

**Comment by GramThanos** [comment]
For testing reasons, we released a pre-release version for the new Edge browser. If you are using the new version of Edge, you can install it from the [Microsoft store](https://microsoftedge.microsoft.com/addons/detail/nielkbamjhjlhmpbhghafgndbcodglhb) (it is marked as v0.0.1)
