### ISSUE TITLE
Sort Auction items based on stats

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#181]
Ability to sort Auction items based on stats (heal, damage etc)

requested in discord

**Comment by mehmetkaradeniz** [comment]
I'm experimenting on this feature. Let me know if you guys have any ideas.

Right now the logic i'm trying to implement is:
- Parse item tooltip and save it in item data attributes (damage, armour etc)
- Sort ui based on these attributes

**Comment by mehmetkaradeniz** [comment]
I sent pr for the demo. It can sort auction items by max damage, armour, health and healing values  at the moment. 
Can be added more stats by extending the keyword model.

For UI I didn't know much so I just made it look like the filter panel.

**Comment by GreatApo** [comment]
I made some improvements (commit 0c134ac0cfa5f73690af2fd68196cf865fa7dd2a)
Hopefully, it will not work for everyone (at least most options)

**Comment by mehmetkaradeniz** [comment]
@GreatApo Nice!

About the bug, can you give more details? 
Do you mean when there are 3 items on table, the sort won't work?

I will check the case in the first change I get.

**Comment by GreatApo** [comment]
I mean when you enable the option to see 3 items in each row :)

**Comment by mehmetkaradeniz** [comment]
Fixed.

**Comment by GreatApo** [comment]
That was fast 😂

**Comment by mehmetkaradeniz** [comment]
Not gonna lie, I didn't even know this 3-view feature existed :)

Hopefully it was an easy fix

**Comment by GreatApo** [comment]
I think it works quite well!
