### ISSUE TITLE
Threat value text is missing in package advanced filters

### ISSUE THREAD

**Issue by Senakhtenre** [DinoDevs/GladiatusCrazyAddon#185]
**Describe the bug**
When you turn on Advanced filters for packages you see a droplist of the different options you have to choose, however, the option "threat" does not have a text the only way to figure out this is the threat option is by inspecting the code.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/7105322/87111022-b22e7d80-c268-11ea-85e1-14c7b2e7e76b.png)
![image](https://user-images.githubusercontent.com/7105322/87111836-9e841680-c26a-11ea-8289-6c4c10ca792a.png)

**Browser info (optional)**
 - OS: Windows 10
 - Browser: Firefox 68.10.0esr (GCA 4.3.0), Google Chrome 83.0.4103.116 (GCA 4.2.0) happens with both ES and EN game/addon language.

**Comment by GreatApo** [comment]
Once you visit your dungeon gladiator this problem be fixed.
I added a default English translation in the code to avoid this problem in the future.
