### ISSUE TITLE
Missing translations - question

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#191]
Heya,

so one of you have probably read that,but I didn't get my answer at all,so I am just curious what's going on with it.

In one of my recent pull requests,I have written that not all text is completely translated in-game,but it has been translated (by me,talking about Czech version),yet it is still in english in the game.

Is this on purpose?Is this a bug?Is only the CZ version bugging out?

For example: Global Arena,More player info,Target list and I believe I can find more,these all were translated and were updated in v.4.3.0 but it is still english.

And like I've said in my pull request,for another example,the "Global Arena" button is actually translated,but only in Gladiatus settings page,or sometimes it will randomly switch to CZ on some random page,but then again,it will go back to english.

I've been just trying to keep the Czech translation complete,so that's why I had to ask.

![eng](https://user-images.githubusercontent.com/23278552/87231785-625fcb80-c3ba-11ea-8043-a9a9556645c8.png)

**Comment by GramThanos** [comment]
Thanks for opening an issue about that! It is easier to track the problems in this way.
It works as supposed on my tests (the Czech translation loads correctly).

Can you please check for any errors on the browser's console (open it with F12).
Also, that type of PC do you run? High-end, low-end? (maybe the language loads too late).

I will look more into it.

**Comment by FrutyX** [comment]
- Well,I do believe my PC is doing okay (FX-8300 4,2Ghz OC,RX 580 GPU 8GB,16 GB RAM etc etc...).

- I am using Google Chrome version 83.0.4103.116 (newest) and no plugin should be in conflict with Gladiatus.

- There is one error in the dev console,blocked by client (adding screenshot).

Thank you for looking into it,let me know if you need any help for more testing.

![eng](https://user-images.githubusercontent.com/23278552/87232818-2fb9d100-c3c2-11ea-8b95-4f6bd5d0c09d.png)

**Comment by GreatApo** [comment]
I also can't replicate the problem (and I have never face such a problem, at least on chrome). You rig is good, there shouldn't be a problem with that.

Lets start from the basics. Can you check the values of the following variable in console? (when the problem appears)
```
gca_languages
```
You should see 2 languages, English and the Selected. Then if you open them (browse the variables), you should see the loaded translations. Anything suspicious?

**Comment by FrutyX** [comment]
I am not completely sure if this is what you wanted,but I have been digging a bit,and what seems suspicious to me is,that everywhere is "en". And in core/locale is only en.js , this is hella strange.

`/*
 * Addon Locale Script
 * Author: DarkThanos, GreatApo
 */

// Manage Locale
var gca_locale = {
	// Active Locale
	active : "en",

	// Load
	_loaded : false,
	_load : function(){
		// Clear
		this._loaded = true;

		// Get active lang
		if (gca_languages.hasOwnProperty("_active")) {
			this.active = gca_languages._active;
		}

		// Get info
		var country = gca_section.country;
		var savedlang = this._getLang();

		// Check if saved lang available
		if(savedlang && gca_languages.hasOwnProperty(savedlang) != -1){
			this.active = savedlang;
		}
		// Check if country lang available
		else if(gca_languages.hasOwnProperty(country) != -1){
			this.active = country;
		}
		// Lang not available
		else {
			this.active = "en";
		}
	},

	// Get or Set lang
	_getLang : function(){
		return window.localStorage.getItem(gca_data_manager.mod + "_" + gca_section.playerId + "_lang");
	},
	_setLang : function(lang){
		window.localStorage.setItem(gca_data_manager.mod + "_" + gca_section.playerId + "_lang", lang);
	},


	// Get Locale
	get : function(section, code, variables){
		// TODO : call deprecated warning
		if(typeof code == "undefined"){
			// Deprecated Message
			console.log("Function \"" + arguments.callee.caller.name + "\" called gca_locale.get(\"" + section + "\") which is deprecated!");
		}

		// Get raw translation code
		var raw = this.getRaw(section, code);

		// If not found
		if(raw == false){
			// Undefined Locale
			console.log("Function \"" + arguments.callee.caller.name + "\" called gca_locale.get(\"" + section + "\", \"" + code + "\") which is undefined!");
			// Return undefined
			return "Undefined_Locale[" + section + "][" + code + "]";
		}

		// If no variables
		if(typeof variables == "undefined"){
			// Return raw translation
			return raw;
		}

		// For each variable
		for(var name in variables){
			// Replace variable
			raw = raw.replace(new RegExp('{{' + name + '}}', 'g'), variables[name]);
		}
		// Return generated translation
		return raw;
	},

	// Get Locale
	getRaw : function(section, code){
		// Load if not loaded
		if(!this._loaded) this._load();

		// TODO : call deprecated method if needed
		if(typeof code == "undefined"){
			return this.get_deprecated(section);
		}

		// Check Language
		if(gca_languages[gca_locale.active] != undefined){
			// Check Translation
			if(
				gca_languages[gca_locale.active].locale[section] != undefined &&
				gca_languages[gca_locale.active].locale[section][code] != undefined
			) {
				// Get Translation
				return gca_languages[gca_locale.active].locale[section][code];
			}
		}
		
		// If not found, fallback to english
		// Get english locale
		if(
			gca_languages["en"].locale[section] &&
			gca_languages["en"].locale[section][code]
		){
			return gca_languages["en"].locale[section][code];
		}

		// If not found
		// Undefined Locale
		else{
			return false;
		}
	},


	// Get Locale - TODO : Deprecated method
	get_deprecated : function(x){
		// Check Language
		if(gca_languages[gca_locale.active] != undefined)
			// Check Translation
			if(gca_languages[gca_locale.active].locale_deprecated && gca_languages[gca_locale.active].locale_deprecated[x] != undefined)
				// Get Translation
				return gca_languages[gca_locale.active].locale_deprecated[x];

		// Get english locale
		if(gca_languages["en"].locale_deprecated[x])
			return gca_languages["en"].locale_deprecated[x];

		// Undefined Locale
		else
			return "Undefined_Locale["+x+"]";
	}
};

// Gca languages object
var gca_languages = gca_languages || {};

// ESlint defs
/* global gca_data_manager, gca_locale, gca_section */
`

**Comment by GreatApo** [comment]
No I didn't meant that. I meant this:
![image](https://user-images.githubusercontent.com/9620510/87233593-c84f5180-c3c0-11ea-8fcf-5cac31013ce7.png)

You can see from the log what languages are active. But DarkThanos is right, it sounds more like a loading speed problem :/

**Comment by FrutyX** [comment]
Yea I have edited my previous post,you probably missed that,so console says only:

`{en: {…}}`

...and that's it.

**Comment by GreatApo** [comment]
ok, that's a clue!

**Comment by FrutyX** [comment]
@GreatApo A bit more observation:

It seems that the translation is working fully on Gladiatus settings page,not only Global Arena button is translated,but also on the premium button in that tooltip "days" are translated too,now what else is on that settings page?Yes,the quick menu,it's translated as well.

So I went to check gca_languages on the settings page a few times,and I am not an expert,but the active language on settings page keeps changing,now it is :

`{en: {…}, pl: {…}, _active: "pt", nl: {…}, nb: {…}, …}`

before it was active: "ar" , "sl" , "Lv" and it keeps changing,I am not sure if this is supposed to keep changing like that,but I doubt it.

**Comment by GramThanos** [comment]
I pushed a possible fix.

**Comment by FrutyX** [comment]
Live or coming in 4.3.1? I can test it out (if it's possible), if you give me GCA compiled for Chrome,do not hesitate to ask.

I have started this,so I intend to finish it.

**Comment by GreatApo** [comment]
> Live or coming in 4.3.1? I can test it out (if it's possible), if you give me GCA compiled for Chrome,do not hesitate to ask.
> 
> I have started this,so I intend to finish it.

Just load the addon as a developer:
- Disable you current version
- Click the green button "clone" in the main github page to get the addon files and extract them
- Go to extensions, and click "Load unpacked extension"
- Go to the extracted files and load the sources folder

btw the behavior you mentioned in settings is normal

**Comment by FrutyX** [comment]
It's not a possible fix anymore,it's an confirmed fix now !

It works,everything is fully now translated,great job and thank to both of you :).

**Comment by GreatApo** [comment]
This will potentially fix other bugs too. Let us know if it happens again.
