### ISSUE TITLE
Training Calculator gone

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#195]
Hello (again :D ),

one of my guild mates has noticed that there is a bug,so I went to check it out,and there truly is.

The stat training calculator isn't working,it's gone,sending you a screenshot.

And there is an dev console error:

`training.js?4.3.0&built=1594663537837:158 Uncaught TypeError: Cannot read property '1' of null
at Object.show (training.js?4.3.0&built=1594663537837:158)
at Object.inject (training.js?4.3.0&built=1594663537837:22)
at fireLoad (training.js?4.3.0&built=1594663537837:958)`

![Výstřižek](https://user-images.githubusercontent.com/23278552/87337882-7df6dd80-c544-11ea-8fc7-d91b182fb865.PNG)

This function was working before the latest version.

 GCA v4.3.0
Windows 10
Chrome newest version (83.0.4103.116)

**Comment by GreatApo** [comment]
Thank you so much for the screenshot! In most servers there is a ":" before the number of available free trainings. The code was crashing when I was trying to read them... It should work on your server again with this fix.

**Comment by FrutyX** [comment]
Confirmed,thank you too :).

![Výstřižek](https://user-images.githubusercontent.com/23278552/87350963-eb146e00-c558-11ea-8417-c19becd6b0b0.PNG)

**Comment by GreatApo** [comment]
Found new bug related to stats base maximum (commit 92d24bf76138b254d0b27296b1169ae9e4c77996)
