### ISSUE TITLE
4.3.1 - Czech translation went to hell completely

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#203]
Oh boi,hello Apo and Gram,

so 4.3.1 is out,and Czech translation is....gone completely.

It's not even an option in language settings,it's completely missing.

Error:

`cs.js?4.3.1&built=1594973836813:208 Uncaught SyntaxError: Unexpected identifier`

at

`sort : "Třídit",`

I did this line,but I don't see anything wrong with it,I have just copied the english version and translated it,but again,I am not the codes expert here,so,we need a fix,please.

It seems GCA doesn't really like our language,because it's making only problems :D (damn diacritics,right).

You know,I've been testing 4.3.1 a few times and it was working without any problem,but now when it's live,it does not work properly.

![cz](https://user-images.githubusercontent.com/23278552/87765455-1f698200-c818-11ea-899f-28f471725ddc.png)

**Comment by GramThanos** [comment]
Don't worry we are aware of the bug but the extension was already uploaded at the time we found it out.

Today the review process was completed, thus we can push a fix version. Note that this problem is affecting only chrome.
