### ISSUE TITLE
Annonate sorted stat on item tooltips after sorting the auction items

### ISSUE THREAD

**Issue by mehmetkaradeniz** [DinoDevs/GladiatusCrazyAddon#204]
It will help with the item comparison after sorting.

Here is a screenshot about how it might look like:

![image](https://user-images.githubusercontent.com/24903574/87779234-2652bd80-c835-11ea-970f-c6d3a2ed5d5f.png)

**Comment by mehmetkaradeniz** [comment]
Had this idea while implementing auction sort. Let me know what you guys think.

**Comment by GramThanos** [comment]
I like the idea.
