### ISSUE TITLE
Target list - attack button

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#209]
Heya,

it's pretty simple,add a button to the target list in familia section.

I was thinking what could be a problem here,and the problem could be when a target isn't located on the same server (provinciarum),because I know we have the option to attack back,but we can't just attack anyone located on a different server,so possibly,the button would be available only for targets located on our current server?

Think about it,thank you.

Example 

![target](https://user-images.githubusercontent.com/23278552/88482205-1d15cf00-cf60-11ea-8a74-34fe3d7bd43f.PNG)

**Comment by mehmetkaradeniz** [comment]
Did some working demo a week ago. There are two icons like in @FrutyX's example.
Added text "A" for Arena and "C" for circus right below battle icon.
Code can be improved..

![image](https://user-images.githubusercontent.com/24903574/93237568-f9fde380-f788-11ea-88af-d3f52de3f1ba.png)

If you are not allowed to attack that player. Error message is shown right above that row.

![image](https://user-images.githubusercontent.com/24903574/93237798-45b08d00-f789-11ea-8157-824886431969.png)

If attack is successful, it redirects you to battle details page just like attacking a player from his/her profile page.
