### ISSUE TITLE
Link to Gladiatus-Tools while forging

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#212]
During forge (or smelting) the generated item link to Gladiatus-Tools doesn't include correct prefix and suffix values.

![image](https://user-images.githubusercontent.com/9620510/90923428-92e94b00-e3e5-11ea-9b86-6e252755c30b.png)

**Comment by GreatApo** [comment]
> Now this is interesting, when the page gets refreshed, it keeps redirecting me to the item in slot 2 at Smelter, even when it's not selected. When I manually select another slot, it works just fine.
> 
> So maybe there is a problem when the page is loaded, it seems like slot 2 URL is default for the URL link of any item that is currently selected.
> 
> Same problem goes for Forge as well.
> 
> If you understand me, it's easy to reproduce.

These tabs are handled by Gameforge's code...

**Comment by FrutyX** [comment]
Hmmm, so this one is... won't fix?

**Comment by GramThanos** [comment]
Low priority.

**Comment by FrutyX** [comment]
Oh, I shouldn't start this "priority" thing, now Gram is everywhere gonna write "low priority" 😆 .

**Comment by GramThanos** [comment]
> Oh, I shouldn't start this "priority" thing, now Gram is everywhere gonna write "low priority" 😆 .

That is a low priority.

**Comment by GreatApo** [comment]
Because of the late loading of the item data, the addon was creating the link to the item before the correct data were supplied. This was both on forge and smelt. It was fixed to check if the existing link url is correct.

**Comment by FrutyX** [comment]
You right, and it seems to be fixed, well done!
