### ISSUE TITLE
Addon default after logging in

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#213]
Hello,

first things first,this isn't some addon-breaking bug,it's just a small thing I've noticed recently,it probably came with one of the Google Chrome updates (v84 + v85 affected) and now to explain : 
**When you first log in in the game,and you are redirected from the lobby to the game,the first page you see seems to be not synced with addon settings,after you click on anything,it loads and works well,no problem.**

(To explain further,I see attack timers,even when I have turned them off (same goes with quick menu) and on the other side,I don't see the auction status banner,this is only on the first page,then it works,I wasn't sure if I explained it well)

This wasn't there before,not even when the newest version of addon came out,so it seems Google Chrome is causing it,a small detail,but it could potentially cause problems in future,so I just wanted to report it anyway,because I do like to help.

There are some console errors,I have checked them,all coming from Adblock,so I turned him off,no change,but Chrome is reporting some issues , adding screenshots : 

![error](https://user-images.githubusercontent.com/23278552/91431386-96a32480-e860-11ea-959f-ff649d43ddf9.PNG)

![error2](https://user-images.githubusercontent.com/23278552/91431403-9b67d880-e860-11ea-84f8-bd7e9652ea14.PNG)

![error 3](https://user-images.githubusercontent.com/23278552/91431411-9e62c900-e860-11ea-8eb6-369d704e462e.PNG)

And that's everything from me I can share,thank you for investigating and keeping the addon fresh and alive ! :)

**Comment by GramThanos** [comment]
So I don't think this is fixable.

On that first the addon detects the ID of the user. We could do that on the lobby, but we don't want to run any code read the login page.

**Comment by FrutyX** [comment]
Hmm,yes,I see where are you going.

I mean,it isn't a big problem,and if you cannot "fix" it ,then you could just add a note/warning on first page,saying something like "Refresh the page to load addon settings" , but that's just a small idea,it will load anyway because you will play the game ,no reason to stay on the first page.

Or perphaps Chrome will do something about it in the future,we'll see,I bet GCA isn't the only affected web with this.

Thank you for letting me know :)

**Comment by GramThanos** [comment]
I will have another look into it to see what options we have.

**Comment by FrutyX** [comment]
When it comes to this back again, I don't see it as a bug anymore, more like a feature, so...

But I am still with what I have mentioned above, that there maybe should me a little warning that GCA is loading and will be loaded on the next page, but it ain't no big deal.

**You can close this when you get there (and consider what I wrote).**

**Comment by GramThanos** [comment]
So this is something between a bug and an enhancement. If I remember correctly (by also checking my old comments), this is caused by a security feature gladiatus implemented to protect the user's feature. The problem is that by doing that, the addon doesn't know anythong about your account and has to do some digging into finding your ID. I may be able to develop a code to refresh the page after the addon have all the needed info.

**Comment by FrutyX** [comment]
Damn, this one is getting old.

You know, I noticed one thing, that this problem is gone, the first page when you enter from the lobby is loaded with my GCA settings.

That was on Google Chrome, then I tested it on Edge, and the problem is back, interesting.

This one is far from being a priority, but I just noticed this.

**Comment by GramThanos** [comment]
Technically, it will appear only the first time.

**Comment by FrutyX** [comment]
On my previous comment, I've said that the problem is gone, well I don't know what is causing this, I only know that I have different versions of Chrome, so I don't know if Chrome is just messing with it somehow and remembers sometimes the session, I simply don't know, but it does not matter.

First page after logging in is always default (without personal settings), because GCA needs a refresh to load everything, not really a bug and since I don't like unfinished things, feel free to close this, it's not a bug, unless you want to enhance it (like you said) and got some ideas for it, but it's really such small thing, that it's not maybe worth the time, there are better/worse issues to solve.

**Comment by GramThanos** [comment]
Since I disabled the zero player read & write to settings this now means that the first time you login, the settings will be set to default. But now, this is detectable we will be able to show a message.

**Comment by FrutyX** [comment]
> But now, this is detectable we will be able to show a message.

@GramThanos this has no priority at all, but, how hard would it be to add this message? So we can finish this issue once for all.

The idea was or is to show a message after you login (and the addon is not loaded yet) that it is loading, and will be loaded on the next page. A simple in-game message.

The reason I am asking (how difficult it is) is, if we are able to stuff it to 4.3.5 or for a next release, or never, that's up to you, it's a small thing, really small, tiny.

**Comment by FrutyX** [comment]
Before I forget it:

The message that GCA is loading can be filled with additional content such as: 

-> GCA is being loaded and will be loaded on the next page
> - Welcome back, (Name)
> - Check our GitHub for Issues (or Troubleshooting Guide)
> - You can find the GCA settings in the profile section
> - Link to DinoDevs web
> - Your current GCA version is: 

> - Current weather... **okay that was a joke.**

and possible more, only useful info.

**Comment by FrutyX** [comment]
@GramThanos 

Turned an bug/enhancement into a feature

![feel-me-think-about-it](https://user-images.githubusercontent.com/23278552/147373658-f0b8797f-b9be-4c90-98f4-4ed82b396378.gif)

**Comment by GramThanos** [comment]
Atleast for the global script, this is now fixed. The global script will try to detect if the player id is not known and try to detect it or wait for it to be detected by the overview script.

**Comment by FrutyX** [comment]
Okie, I don't think I have anything else to say for this :).

**Comment by FrutyX** [comment]
Patched in v4.3.6, closing, re-open if needed.
