### ISSUE TITLE
[Translation]:zh-Chinese traditional 20200903

### ISSUE THREAD

**Issue by smoothGrace** [DinoDevs/GladiatusCrazyAddon#215]
Language name in English
-language:zh-Chinese traditional 20200903

Link the translation file here

chrome is not allowed to test this myself,so...it may be some bug?
[zh.zip](https://github.com/DinoDevs/GladiatusCrazyAddon/files/5165544/zh.zip)

**Comment by GreatApo** [comment]
FYI to test an addon you need to load it as "unpacked" extension (there is a button under chrome extensions)

**Comment by smoothGrace** [comment]
is that "load unpacked"?
i copy a 4.33version  ,rename ,replace /core/locale/zh.js

and use load unpacked

is display:"Manifest contains a differential_fingerprint key that will be overridden on extension update."

**Comment by smoothGrace** [comment]
i delete differential_fingerprint from manifest.json and xxxfingerprin  ,restart chrome,it's seem work properly.

**Comment by GramThanos** [comment]
I am not sure what you did, but it sounds like you edited the extension package file.

Usually for development we download the GitHub project and load the extension folder to the browser as an unpacked extension.
