### ISSUE TITLE
GT as a new tab is messed up

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#217]
Hello,

so it's pretty simple,I have the guild market sorted by gold value (from lowest to highest) , the problem is when you open GT with a new tab,the values will be messed up,not sorted,it's not gonna stay that way tho,it will come back when you open GT normally,but it always happens on a new tab,it's just annoying,if this was fixable,it would be really nice :)

Browser: Google Chrome v85

**Comment by GramThanos** [comment]
I can't think a way to fix this.

**Comment by FrutyX** [comment]
I'll leave the decision up to you, but I adapted to it, and I am not opening GT as a new tab anymore, so I don't think this has much priority now, so you can close this, if you want or explore another options, that's why it's up to you.

**Comment by FrutyX** [comment]
We did improved the market site, especially in the #240 and maybe also somewhere else, or it could be my browser's doing, but all I know now is, that GT as a new tab is not messed up anymore, it is sorted.

Closing, wasn't really important anyway.
