### ISSUE TITLE
Double-click alternative (hotkey combinations)

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#218]
Hello again,

now this could be a little dangerous and no one wants the addon black-listed right.. and I wonder if someone actually suggested this already before,but it did not make it in-game for some reasons.

Now to the idea itself,you know,for those still playing Gladiatus,it can be really pain in ass to sell small items,especially rings and amulets to change them into gold,and so anything that would make it to sell them faster and easily would be helpful,for example: dragging more than just one amulet at time , let's say a "box" ? Let me show it on a picture : 

![kk2](https://user-images.githubusercontent.com/23278552/92323320-0fac3400-f038-11ea-9225-dfcad97ff962.PNG)

I am probably asking for a lot,and I have no idea if this would be actually allowed by Gameforge (server overload,making the game too easy etc...) , but what I know for sure is,that it would help the players a lot.

Another thing that was on my mind is selling items with ENTER button when you hover over them with mouse,that's not a bad thing either.

I know that javascript can be a powertful thing,the question is,what you can do with it and what you are allowed to do with it?

**Comment by mehmetkaradeniz** [comment]
Doing multiple actions by single trigger (e.g mouse click) may not be ok with Gameforge.

I would suggest implementing something like ctrl + click to buy/sell to speed up the process.

**Comment by GramThanos** [comment]
We already added double clicking. I don't think that anything else should be added.

Everyone wants to sell fast items. But this should be added by Gameforge. Just one button that sells everything inside the bag. Faster easier less painful for the server.

**Comment by FrutyX** [comment]
Hmm,well I was kinda expecting such response and I very doubt Gameforge will do anything about the game,I mean it's a miracle Gladiatus is still running.

I can't still help myself,if we can't use a single button sell option,then add something like @mehmetkaradeniz mentioned,or possibly,even better and if possible,add a option to customize it how we sell,like KEYBOARD BUTTON + (non changeable) MOUSE BUTTON ,of course it doesn't have to be customizable,that was just an idea.

I know I am spitting ideas on you,but sometimes when selling a lot items for some reason,I don't feel comfortable smashing that mouse button,sometimes you won't even sell it because it won't register or it will drag the item instead,but that's just occasionally when you are fast selling tons of stuff.

Thanks anyways for hearing me out :)

**Comment by GramThanos** [comment]
I agree that the double clicking is not always so easy then you want to click multiple items. We are open to suggestions for hotkeys combinations.

**Comment by FrutyX** [comment]
I would suggest something to comfortably cover the left hand, so left ctrl,alt,shift or spacebar could work too.

For left handed people,possibly add an settings option to switch to right alt/ctrl/shift.

Now thinking about it,spacebar would be the best solution for everyone,but every browser is scrolling the page with it,so that is a problem.

**Comment by GramThanos** [comment]
Ctrl and Shift are also used for the item stack move

**Comment by FrutyX** [comment]
Hover?Like hovering with the mouse?If hovering was possible,then there is nothing else to talk about ,with another button of course.

Hover + alt
or
alt + single click

both will work,the final decision is on you,we are on the right way,so decide and make the dream work :D :) , and when it will be available on Github,I'll try it out.

Thank you for listening.
