### ISSUE TITLE
Guild total gold won

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#222]
Hey,

this idea came from my guildmate and it's not a bad one:

Show how much total gold a guild made by stealing from other guilds in guild wars,possibly how much from each, it could be listed in War Master Hall.

Now I wonder, where this info should be stored because it's not some info for one player,but for a whole guild,only idea I have is to store the gold information for every player independently,meaning it will show for everyone total stolen gold only if the player actually participated in the battle, but if you have a better idea ... :)

Thanks :)

**Comment by GreatApo** [comment]
Will this do?

![Improve_Banks_Book_Layout_Y](https://user-images.githubusercontent.com/9620510/147749028-72e7959e-c51d-4a38-8b2d-372a2e44390e.png)

**Comment by FrutyX** [comment]
Most surely!

**Comment by Zitronenen** [comment]
Sure!

**Comment by FrutyX** [comment]
@GreatApo is that just an preview right? It's not functional yet, right?

**Comment by GreatApo** [comment]
> @GreatApo is that just an preview right? It's not functional yet, right?

It is functional in dev branch, once you visit your guilds' map page (it saves the building levels).

**Comment by FrutyX** [comment]
@GreatApo dev branch... yeah, you do mean master by that? Because I can see only master and version 3.

If yes (current master), then well, we do have a problem. 

It shows I have stolen 814M from other guilds, but I never even attacked any other guild.

**Comment by Zitronenen** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/8767665/147785343-9c6bc534-ef3a-4a79-bf61-b84bd06207fc.png)

My Testguild:
No Fight - Only Spend.

**Comment by GreatApo** [comment]
> @GreatApo dev branch... yeah, you do mean master by that? Because I can see only master and version 3.
> 
> If yes (current master), then well, we do have a problem. 
> 
> It shows I have stolen 814M from other guilds, but I never even attacked any other guild.

Yes master.

That number is the maximum potential stolen gold. If you send the money on scrolls and you have less discount on each upgrade, it would be more that the actual value. I am not sure I can make it more accurate

**Comment by FrutyX** [comment]
Uhhh, okay, just... 814M is a big approx, but I won't complain, hell no.

But I found a potential bug, I think, the section won't open sometimes:

![sec](https://user-images.githubusercontent.com/23278552/147786535-f471a61c-6c06-4551-801d-a36aa4a7cfdf.PNG)

And it's not clickable, I've fixed that (elements) by adding `style="display: block;"` to it's `<section>`.

**Comment by GreatApo** [comment]
> My Testguild: No Fight (i can make an testfight if u want) - Only Spend.

Go to you guild's map page once:
![image](https://user-images.githubusercontent.com/9620510/147788097-5a39b2d5-a7f5-4390-84cc-6d7e44346b5c.png)


> Uhhh, okay, just... 814M is a big approx, but I won't complain, hell no.

I made a change to improve the approximation. I am limiting the discount to the in guild members.

> And it's not clickable, I've fixed that (elements) by adding `"style="display: block;"` to it's `<section>`.

Done, thanks.

**Comment by FrutyX** [comment]
Perfection.

![perf](https://user-images.githubusercontent.com/23278552/147789346-78eeecf8-58ef-452c-b1ca-afa7c51a8586.PNG)

**Comment by Zitronenen** [comment]
> > My Testguild: No Fight (i can make an testfight if u want) - Only Spend.
> 
> Go to you guild's map page once: 
![Screenshot_1](https://user-images.githubusercontent.com/8767665/147791239-6f0960a5-5762-48be-a74f-e1380effffb7.png)
![Screenshot_2](https://user-images.githubusercontent.com/8767665/147791242-3e72f6f8-c400-465e-b3f4-b8fe45dd03b6.png)

The current version of github. I have one guild battle and I lost this one: D

**Comment by GreatApo** [comment]
> The current version of github. I have one guild battle and I lost this one: D

It doesn't measure the stolen gold from the war camp, so the approximation can not get better...

**Comment by SleepingShadow-bit** [comment]
Sorry :( I need more explanation about it.

First: Total donation from current members and Rip Members.
Second: Invest at guild building upgrades
Third: Stolen gold from other guilds (win) or stolen gold from my guild (lost)?

**Comment by GreatApo** [comment]
> Third: Stolen gold from other guilds (win) or stolen gold from my guild (lost)?

The first (Stolen gold from other guilds (win)). Mind that these are approximate.

**Comment by SleepingShadow-bit** [comment]
I think I'm too stupid for that (3rd Line).
But what about the gold that was lost in a guild battle or when activating a recipe? 
Is the 3rd line possibly misleading?

Sorry for that :/

**Comment by GreatApo** [comment]
> I think I'm too stupid for that (3rd Line). But what about the gold that was lost in a guild battle or when activating a recipe? Is the 3rd line possibly misleading?

I get what you mean, and yes it is a bit misleading. The correct way to calculate it is:
Stolen gold from other guilds = all donations - gold stolen from this guild - gold spend on building upgrades - gold spend on recipes
 
 I can't calculate the gold stolen from this guild nor the gold spend on recipes, this is why if assumed 0, then you will get the maximum possible value of the stolen gold from other guilds (that is why I have the maximum in the parenthesis).

**Comment by SleepingShadow-bit** [comment]
Now I understand it! Thank you!
I will note this in the documentation ok?

**Comment by GreatApo** [comment]
> Now I understand it! Thank you! I will note this in the documentation ok?

Thanks!

**Comment by mattemre** [comment]
![image](https://user-images.githubusercontent.com/95325400/148249573-fdc1182c-67bd-4bc4-8573-3325cc19b826.png)

What does this error mean?

The gold we earned from the guild war is not written. does it have anything to do with it?

**Comment by GramThanos** [comment]
> ![image](https://user-images.githubusercontent.com/95325400/148249573-fdc1182c-67bd-4bc4-8573-3325cc19b826.png)
> 
> What does this error mean?
> 

This error most probably notifies you that your adblocker blocked a URL associated with ads. It is not related to our extension.

**Comment by mattemre** [comment]
then this is ok :)

**Comment by FrutyX** [comment]
Apo, you planning anything else here, or we can close this?

Only thing, that came to my mind is, to add a small note under it (like I did with XP and Gold statistics) to explain how it works, in case someone wants to know, same as me and Shadow wanted to know.

**Comment by FrutyX** [comment]
Closing, re-open if needed.
