### ISSUE TITLE
Underworld - new location redirect

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#223]
Hello,

so,this is an improvement for underworld only, when you defeat a boss, and you click on the expedition button, it will not redirect you to the new location and what can happen is,that you accidentaly click on the boss you defeated again (it happend to me ,and not once) , so instead of that, once we defeat the boss and a new underworld location gets unclocked, the expedition button will redirect you to the new location, instead of the one that you already beat.

Thank you.

**Comment by GramThanos** [comment]
I would like to alter the solution a bit.

I suggest that in underworld, the expedition button will be changed to always point to the last unlocked location.

**Comment by FrutyX** [comment]
Yup, can't say anything against that,good solution.

**Comment by FrutyX** [comment]
Awesome, gonna test it when I am back in the underworld tommorow.

**Comment by FrutyX** [comment]
Implemented in v4.3.6, closing, re-open if needed.
