### ISSUE TITLE
Target list add button doesn't show on cross arena players

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#224]
The target list add button doesn't show up on players from other servers (at least for some players)

**Comment by GramThanos** [comment]
The problem is that the `document.referrer` is no longer caring the URL parameters, thus the new script can not retrieve the secure hash.

**Comment by GramThanos** [comment]
Walk-around was implemented.
Fixed on cb84f9fd6dc156905737501ed69a6be83acb18a7

**Comment by GramThanos** [comment]
New version is out, closing this one for now.
