### ISSUE TITLE
Adding to Opera Addon store

### ISSUE THREAD

**Issue by sahin52** [DinoDevs/GladiatusCrazyAddon#227]
Opera uses chromium, which means since this works on chrome, it must work on opera easily. Could you please add this to opera?

**Comment by GramThanos** [comment]
We submitted the addon on Opera many years ago. The addon hasn't been reviewed yet.

Basically the Opera store does not work. But the Opera has a functionality to install addons from the Google Chrome store, thus one may install it from there.

Additionally, Opera allows you to install crx files (chrome extensions addons) directly by drag n droping them into an Opera window.

**Comment by FrutyX** [comment]
We all know the state of this, for future questions, direct everyone to - https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/installation-opera.md

Closing.
