### ISSUE TITLE
Name inventory slots

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#228]
Heya!
I see there was some recent github activity, which is nice and appreciated!

I can also see that some my ideas weren't added yet, but that's alright, I just think some (most) of them would really useful, anyways, I got another I had to share with you.

It's pretty simple and not hard to do (I believe), now how to explain it, hmm..

We have inventory slots (I,II,III,IV...), and what I would most likely use is to name them, so it would be an overview function for inventory slots.

As an example, i have this:

![inv](https://user-images.githubusercontent.com/23278552/103463583-bf1abe00-4d2d-11eb-9c5a-b4734021d324.PNG)

We could just overwrite it with anything we want, in this case, I would name it "Food", if overwriting this source code would be a problem, then I guess you can always find even a better way, like putting some small box above the whole inventory box, but all I am saying here are just... my ideas and suggestions.

And again, thank you for considering my request, I do hope you have a nice start of the year!

**Comment by GramThanos** [comment]
The problem with such a feature is that there is not too much space there to write something.
For example, assume that I want to name tab 1 "Food", I will end up having something like that:

![image](https://user-images.githubusercontent.com/14858959/103466656-7a078380-4d4f-11eb-82f1-0246ffb3506d.png)

We can use a smaller font but once again, it will only fit at maximum about 4 letter.

![image](https://user-images.githubusercontent.com/14858959/103466686-bd61f200-4d4f-11eb-8c08-0956252791a0.png)

**Comment by FrutyX** [comment]
I see.

Or possibly add an independent small box (with editable text) above it like I mentioned, that will change when you click on a different inventory slot (I,II,III...), this might sound difficult and be more difficult to create, but well, I ain't here the programmer, so I'll leave the final result up to you, if you want to make it.

**Comment by FrutyX** [comment]
Note for future Gram or Apo:

This could work with changeable labels, positioned above the inventory tabs, we pulled something similar in #296.

A lot of work tho.

**Comment by FrutyX** [comment]
With a few CSS tricks, you can customize it, so that what Thanos said is invalid (I've played with it), however I think we can live without this, it's probably not worth it and needs a lot of changes, so imma close this, if you ever wanted (seriously) to do it, you can always open again.
