### ISSUE TITLE
New Glad update (v4.2.0) just bugged the whole auction GCA functionality

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#230]
Now, this is a terrible nightmare, anyways, hello, long time no see.

Well, a new version of Gladiatus just came out and one of the GCA functionalities just stopped working properly, I am talking about the auction page - GCA doesn't refresh the item status when making an offer into the auctions anymore, it actually works and it will make an offer, but it still shows that there are no buyers, you have to refresh the page manually to see that you made an offer.

I feel like this caused this:

> - game shows shortly a white page with every game change

And me, my whole guild, and all people that are saving gold via auctions, are just f*cked, to be honest, thanks GF, I guess :-/

I was just thinking, could you make some.. hotfix version? I know uploading new versions on some addon browser stores are pain in the ass and it takes a long time, so maybe just a Github downloadable edition? If you manage to fix it easily? Because, well, I guess it's gonna take a while until we see a new fresh version of GCA, and I don't want you to rush it, no, but this created a problem that needs to be fixed like... now.

Thank you very much!

EDIT: Oh and yes, console is throwing an error when making an offer:

`auction.js?4.3.3&built=1615291617110:325 Uncaught TypeError: Cannot read property '1' of null
    at Object.success (auction.js?4.3.3&built=1615291617110:325)
    at j (jquery.js:3)
    at Object.fireWith [as resolveWith] (jquery.js:3)
    at x (jquery.js:3)
    at XMLHttpRequest.b (jquery.js:3)`

**Comment by GramThanos** [comment]
Hello. Fixed pushed f7e10ebcd3e772f5efabd4f9157f28df7398cf3e

**Comment by GramThanos** [comment]
About editions that are not on the store, only Firefox supports such a functionality (developers can upload the new version for signing and then self host it). For chromium/chrome/opera/edge users can load the extension as an unpacked extension (method used for developing extensions).
Anyway, I will prepare a version.

**Comment by FrutyX** [comment]
Solved, closing.

Re-open if needed.
