### ISSUE TITLE
funciones perdidas en gladiatus crazy add on

### ISSUE THREAD

**Issue by layetan** [DinoDevs/GladiatusCrazyAddon#231]
SO : Windows 10
Navegador Chrome

Extensión Gladiatus Crazy Addon v 4.3.3

Han dejado de funcionar unas cuantas funciones por ejemplo : la barra de atajos, la de estado superior no queda anclada, el estado de las subastas y otras.
En configuración constan como activadas pero no funcionan.
He desinstalado y vuelto a instalar la extensión pero no funciona correctamente. 

Agradecería una solución al problema si esta en su mano.

Gracias.

https://gyazo.com/efd3a006e741c9aca6c622d1c90e3924

https://gyazo.com/5935c8874f1f91c6845098c58060b0af

**Comment by FrutyX** [comment]
@layetan I suggest to update your addon to v4.3.4 , just uninstall and install it directly from Chrome addon store, the newest version is already there.

I am on Chrome and I don't have any problems with the newest version.

**Comment by layetan** [comment]
siguen sin funcionar una parte de las funciones del crazy add on, version v4.3.4.

compañeros me han comunicado que no tienen ningún problema lo que me desconcierta más aún.

Problema con google ??

**Comment by GramThanos** [comment]
Try opening the console (by pressing F12 or right click inspect element, then select console tab). Any error there?

**Comment by FrutyX** [comment]
Since we never got any other reply, I will close this, it's a problem with GCA, but that does not mean GCA is causing it, I see many things that could cause this, also it probably fixed itself. 

Closing.
