### ISSUE TITLE
Wrong item color

### ISSUE THREAD

**Issue by Emefar** [DinoDevs/GladiatusCrazyAddon#233]
Whole items color is wrong. Red items are orange, orange items are purple.. And also my name is **Emefar** but seems like **rafemE**.

<img width="613" alt="Screenshot at Mar 11 14-00-02" src="https://user-images.githubusercontent.com/36764954/110777427-285d0700-8272-11eb-989a-eb9ce0721a01.png">

**Comment by FrutyX** [comment]
@Emefar 

Have you updated your addon to the latest version (4.3.4) ? Because there are some bugs in 4.3.3 thanks to Gladiatus update 4.2.0.

**Comment by Emefar** [comment]
I updated latest (4.3.4). And i asked my friends. And all friends have same bug. And i guess GCA is clearing some caches (this is different bug).

**Comment by SomDelfin** [comment]
I have the same problem.
http://prntscr.com/10iydew

testing mozzila and chrome

**Comment by GramThanos** [comment]
TGV0IG1lIHRlbGwgeW91IGEgc2VjcmV0Li4uIHRoaXMgaXMgbm90IGEgYnVnIDpEIC4gU29ycnkgYWJvdXQgaXQuLi4gSSBqdXN0IHdhbnRlZCB0byB0cm9sbCBwZW9wbGUgdGhhdCBoYXZlIGV4dGVuc2lvbnMgdGhhdCBhcmUgYWdhaW5zdCB0aGUgZ2FtZSdzIHRlcm1zIG9mIHVzZSBpbnN0YWxsZWQgOlAgLg==

:robot: Σφάλμα! βάση 64 :warning:

**Comment by GramThanos** [comment]
😆 Ok, since a lot of people think this us a bug, this is not a bug.

GCA detects if other extension that could be used against the rules are installed and if yes, it trolls the user :trollface: 

Quote from changelog:
```
Addon now is able to detect a number of extensions that are against the terms of use of the game
```

**Comment by FrutyX** [comment]
Haha, busted.

Well done.

**Comment by Emefar** [comment]
I am only using GCA, Adblock, ScreenRecorder and ViewImage (Google) extensions. I closed all extensions and tried again. Same result is appeared again :/

**Comment by GramThanos** [comment]
Again this is only a troll.

As I said, gca checks for extensions that COULD be used against the rules. This does not mean that the player is using them as a number of them require subscription.
