### ISSUE TITLE
COLOR BUGS

### ISSUE THREAD

**Issue by SomDelfin** [DinoDevs/GladiatusCrazyAddon#234]
Good day,
I have a problem with having swapped colors.
green is white, blue is green, purple is blue, orange is purple, red is orange.
can you help me with that?

GOOGLE CHROME

http://prntscr.com/10ivyi8
http://prntscr.com/10ivza9

**Comment by FrutyX** [comment]
#233 

Kinda interesting that I do not have such problem, not even in the underworld (tested just now) on Chrome with v4.3.4.

Must be individual, which means it can be harder to recreate - find the problem.

**Comment by SomDelfin** [comment]
i try reinstal

**Comment by SomDelfin** [comment]
Now I tried it on my friend's computer and it did the same thing after two minutes

**Comment by SomDelfin** [comment]
It usually does this as soon as I change something in the addon settings

**Comment by SomDelfin** [comment]
This problem started for me from 14:15 today.

in the morning everything worked for me as before without a problem

**Comment by GramThanos** [comment]
Closing that since it is the same as #233
