### ISSUE TITLE
error in colors

### ISSUE THREAD

**Issue by satanick2021** [DinoDevs/GladiatusCrazyAddon#236]
**Describe the bug**
changes in original colors

**Screenshots (optional)**
https://gyazo.com/2deae2b37596a19227683621cab69948

**Browser info (optional)**
 - OS: [e.g. Windows, Linux, Mac, Android, iOS]
 - Browser [e.g. Chrome, Firefox, Opera, Edge]

**Comment by GramThanos** [comment]
This is associated with #233 . Closing this, continue to the other.
