### ISSUE TITLE
falla de la aplicación Gladiatus Crazy Addon version 4.3.4

### ISSUE THREAD

**Issue by camtosner** [DinoDevs/GladiatusCrazyAddon#237]
Buenos días,  primeramente quiero agradecerles por la aplicación es muy buena te ayuda a encontrar rápidamente lo que buscas, ahorrando tiempo de búsqueda y es es muy bueno... Nuevamente gracias!
bien el problema es el siguiente:
soy jugador de gladiatus.gameforge en el servidor 35, Pais España
instale la aplicación Gladiatus Crazy Addon para Google Chrome Webstore, version: 4.3.4
La aplicación esta fallando en la forma de búsqueda... Pues que esta permite encontrar objetos de Descendente y Ascendente
en mi caso la tengo configurada en forma Descendente
Cuando realizo una búsqueda....  (esta aparece de forma Aleatoria y Desordenada).
Un ejemplo... búsqueda coraza... - armadura-descendente:
![image](https://user-images.githubusercontent.com/80536821/110972543-19399000-832a-11eb-8331-d229616be5fb.png)
búsqueda de anillos...  daño-descendente
![image](https://user-images.githubusercontent.com/80536821/110973438-433f8200-832b-11eb-8ef5-6e00b5a65205.png)
busqueda zapatos... armadura-descendente
![image](https://user-images.githubusercontent.com/80536821/110973822-c19c2400-832b-11eb-9b5c-8a7774c0e4fd.png)
busqueda guantes... armadura-descendente
![image](https://user-images.githubusercontent.com/80536821/110973968-f5774980-832b-11eb-9c4d-c67e9cf4cd2f.png)
busqueda casco... armadura-descendente
![image](https://user-images.githubusercontent.com/80536821/110974125-2d7e8c80-832c-11eb-9058-584d14db8b2f.png)
busqueda escudo... curacion-descendente
![image](https://user-images.githubusercontent.com/80536821/110974458-8b12d900-832c-11eb-96f3-9cbc2daa87b5.png)
busqueda coraza... curacion-descendente
![image](https://user-images.githubusercontent.com/80536821/110974635-ba294a80-832c-11eb-9e67-a05cb4f643af.png)

finalmente tengo instalada la versión
Gladiatus Crazy Addon  v.4.3.4 de Chrome.
Nuevamente un saludo al desarrollador de esta aplicación es muy buena,
espero puedan corregir el error que tiene en este momento. 
un saludo grande desde Colombia, gracias.

**Comment by GramThanos** [comment]
Thanks for the info. This is associated with #235. I am going to close this one, we can continue on the other issue.

**Comment by camtosner** [comment]
gracias por responder...
espero que la aplicación, gladiatus crazy addon funcione muy bien!
con su respectivo mantenimiento. saludos desde colombia.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
