### ISSUE TITLE
Bag pop over and double click

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#238]
Chrome, v4.3.4.

Hey,

sometimes the game keeps refusing the double click feature and it keeps moving your items back, it can be very annoying, but with the new "bag pop over" feature, the game is refusing items every time, you can still get then normally, but double clicking just doesn't work.

I've made a gif.

![bag](https://user-images.githubusercontent.com/23278552/111008495-83395000-8391-11eb-8c83-a8cf27413be1.gif)

(EDIT: And with this opportunity, I would like to mention #218 again :D )

**Comment by GramThanos** [comment]
I will look into it. A similar problem exists when you have scalled the page.

**Comment by FrutyX** [comment]
I can confirm, that this was fixed.

An very welcome fix, thank you.

Closing.
