### ISSUE TITLE
Different colors on items and name issue

### ISSUE THREAD

**Issue by cpassiopoulos** [DinoDevs/GladiatusCrazyAddon#239]
Items appear in lower color (see attachment)
Name is spelled backwards (see attachment)
When I disable CrazyAddon, all is normal.
I use windows 10, and this is in all browsers i use (Chrome, Edge and Opera)

 
![2021-03-13 10_06_10-Greenshot](https://user-images.githubusercontent.com/80570813/111023919-87428d80-83e4-11eb-8ae8-af26cde26132.png)

**Comment by FrutyX** [comment]
#233
