### ISSUE TITLE
[Enhancement] Stop normal scripts on server buckup

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#24]
We must stop the execution of normal scripts on server buckup page.

**Comment by GramThanos** [comment]
To do that, we can check if this is the buck up page on "fireLoadEvent" function

**Comment by GreatApo** [comment]
Too old, closed

**Comment by FrutyX** [comment]
What's the status on this? It's old, is it still needed? Was there a patch? Can we close this?

**Comment by GreatApo** [comment]
This issue was before we re-write the whole addon from scratch in 12/2017. Thus it is now invalid.
