### ISSUE TITLE
Market bug - kick to lobby

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#240]
Chrome, v4.3.4.

Since the new Glad update and v4.3.4, I keep getting randomly kicked to the GF lobby, it's hard to identify it but sometimes it will kick me only once, and sometimes it kicks me 3 times in a row.

I must say, that **I am not completely sure, if this problem is from GCA,** but I will ask here first. I was getting kicked and so I disabled GCA, and there was no kick.

Fortunately, I do have something, a console report when it happens + URL of the script, clearly it is a GF script but I am still sharing it with you, hopefully you will know more.

**Console:**

`Cookie banner version 0.11.4-pl4 loaded
cookiebanner.js:15 Initial consent: Objectmarketing: truenecessary: truepreferences: truestatistics: true__proto__: Object
main.6bdd6149.js:1 Cookie Consent Objectmarketing: truenecessary: truepreferences: truestatistics: true__proto__: Object
connect.js:24 Dispatching GFLocaleChange with Objectlocale: "en-GB"__proto__: Object
connect.js:24 Dispatching GFLocaleChange with Objectlocale: "cs-CZ"__proto__: Object`

And after this, I get kicked into the game lobby to choose my server.

The URL of the script is : [https://gameforge.com/js/connect.js](url)

I guess you can check it and tell me what should I do, I was ready to report it on gladiatus forums, but I wanted to consult it with you first, because maybe it was just random, that it wasn't kicking me when I disabled GCA  and now I have GCA on, and I am not getting any kicks, like I've said, it's completely random.

**Comment by GramThanos** [comment]
The console info and the script is related to the cookie consent notification you get on the Gladiatus (not related to the extension).
Lets keep this open and check if anyone has similar problems.

**Comment by FrutyX** [comment]
Since this was related to cookies, I have cleared my cookies together will all data from Gladiatus.

It's been 2 days now and I didn't get kicked anymore.

So basically fixed, wasn't GCA's fault.

Closing.

**Comment by FrutyX** [comment]
It came back, so I was testing it and observing it.

**This seems to be an GCA issue after all.**

The console message is still the same, but now I know more.

Every time I go to the **guild market**, it will kick me to the lobby, I've turned off GCA - no problem. I've turned on GCA, boom guild market again kicked me.

I've tested it million times, when GCA is ON, the guild market likes to kick me to the lobby randomly.

Also I tried doing this on Firefox, there is no problem on Firefox, but also, there is no message in the console like this.

I am sorry I cannot help you more, but the console isn't really saying anything more. 

Chrome v89.0.4389.90 
GCA 4.3.4.
Adblock off (not causing it)
Czech lang.
Clearing cookies and all data didn't help.

**Comment by GramThanos** [comment]
😭

**Comment by FrutyX** [comment]
I've been using my exported settings file for ages now, maybe it was or it is the problem. It probably got corrupted or it doesn't work with newer version, who know.

I've cleared it, lost my settings and target list, but so far no kick, but I cannot confirm it. It was gone for like 2 days and then it started kicking me again, so I really don't know if that was the problem, clueless.

**Comment by FrutyX** [comment]
Okay, that didn't fixed it, it's really funny, how it is random.

**Comment by GramThanos** [comment]
I will chech the code and get back to you tomorrow. Is the proble on all the market or when you filter something?

**Comment by FrutyX** [comment]
Kick to lobby immediately when I click on guild market (via quick menu or normally, it doesn't matter), I actually didn't tried normal market, because I am never using it anyway.

From the console log, I see that something changed from english to czech, and I know we had a problem with languages not being properly recognized in the past, could there be a problem? Well, I am just guessing at this point.

I only know, that when I checked GCA settings, my language was set to arabi (default), but everything else was czech, the problem is still here tho, even when I set the right language (looks like it is saved now).

Another mystery is... when it happens, like right now, I can nonstop refresh the guild market and it won't kick me, and then, one moment and I am unable to access the guild market with GCA ON, kinda strange, isn't it.

Well, I guess I'll leave it up to you, I didn't seen anybody else with this problem, I've asked some of my guild mates, no problem there, but I really have no idea, what is wrong.

Also this was an clean install from Chrome addon store, so it should be OK.

Thank you, kind sir.

**Comment by FrutyX** [comment]
An example:

![ezgif-1-86da0c5e6213](https://user-images.githubusercontent.com/23278552/111708656-8a0b0b80-8846-11eb-8814-9e7326af5808.gif)

.... and after this, I have disabled GCA and I was able to access guild market normally, so that's why I am here.

**Comment by FrutyX** [comment]
Okay, so it seems the GFLocaleChange is there every time, it's part of the Gameforge lobby, I should use my brain next time.

Which means, that we basically have nothing and console isn't saying anything about it.

Great!

**Comment by GramThanos** [comment]
The problem most probably is associated with yhe cookies. You can check
under the application tab of the developer tools (same plase as the
console) if there are duplicate cookies.

Do not share any screenshot of them.

**Comment by FrutyX** [comment]
Negative, no duplicates, but no problem at this moment, will check when the problem comes back (like I've said, random).

**Comment by GramThanos** [comment]
What is the URL like when you hover the link?
![image](https://user-images.githubusercontent.com/14858959/111848712-6ca47300-8914-11eb-84e7-182184a1761e.png)

It should be like:
`https://s<server-number>-<country-code>.gladiatus.gameforge.com/game/index.php?mod=market&sh=<a-big-hash-value-here>`

(do not post the big hash value at the end)

**Comment by FrutyX** [comment]
`https://s34-cz.gladiatus.gameforge.com/game/index.php?mod=guildMarket&sh=`

Today was okay, didn't get kicked,  so I wonder, if it will reappear again. Like it did before.

**Comment by FrutyX** [comment]
Yea, I got it again.

`Navigated to https://lobby.gladiatus.gameforge.com/cs_CZ/?mod=start&submod=needLogin&sh=..........`

Only thing I noticed after this, that the my guild market sorting did reset. I have it sorted by price.

**Comment by FrutyX** [comment]
@GramThanos 

[https://youtu.be/s0LN30Mqy0A](url)

**Comment by GramThanos** [comment]
I spotted some refreshes at the market when you had the addon disabled. You can take a look on the network tab too (on dev tools).

**Comment by FrutyX** [comment]
Welp, I wasn't able to find anything useful.

But.

I've been testing older versions of GCA, and I stopped when the problem vanished - version 4.2.0 is the version, where this problem isn't present, any version above this, keeps instantly kicking me.

**Comment by FrutyX** [comment]
These last days, I've been more actively playing the game, and this seems like a serious problem, because I can barely access the guild market.

You know how am I accessing the guild market? When I join back in from the lobby, and the addon isn't loaded (#213), I can normally access the guild market, after addon is loaded, I'll get kicked.

I've been trying all the stuff like reinstalling, removing all data from Gladiatus and nothing worked.

I don't see any error in the Network card, I only see that it was request:

`https://s34-cz.gladiatus.gameforge.com/game/index.php?mod=guildMarket&s=p`

and after this I got:

`https://s34-cz.gladiatus.gameforge.com/game/index.php?mod=start&submod=needLogin&sh.......`

is it normal, that the guild market URL is ending with `s=p` ? 

I mean I am not an expert so I don't know, I am just trying to inform you about everything. Also I know that I am the only person (in the world, probably), with this issue, but I am unable to fix it.

**Comment by FrutyX** [comment]
I investigated further, and yes, without GCA, the guild market URL has an `sh=` , with GCA, it is only `s=p`.

**Comment by GramThanos** [comment]
Can you check if it works if you disable the "remember market sort" feature

![image](https://user-images.githubusercontent.com/14858959/112895023-41c0d880-90e5-11eb-9516-663025865d20.png)

**Comment by FrutyX** [comment]
Indeed, give me some time, I will test it when the problem occurs again.

**Comment by FrutyX** [comment]
@GramThanos Yes, nicely done!

You have found the problem, turning off market sorting solved this problem.

And I can see that you already made some changes to it, I am happy to see that we finally found the root of the problem!

**Comment by FrutyX** [comment]
And it seems, 4.3.5 with your fixes solved it as well.

I believe you can put patched and testing labels on!

Thank you for the fix!

**Comment by GramThanos** [comment]
I don't really know what exactly was the problem. I know that it was something related to the URL parameters that the addon was setting to remember the sorting. So I did some cleanup and small improvements on the code.

**Comment by FrutyX** [comment]
So, I've had this fix for a while, and it works flawlessly.

Thank you, closing.

**Comment by FrutyX** [comment]
Reopening this to make a small note.

@GramThanos I've noticed something, I ain't sure if this is normal or if it's just a bug, but I am letting you know.

Last sort order (yes, it's enabled :D) on the market is reset when you close Gladiatus or when you log off (simpler, you leave the game).

I believe this wasn't happening before we made these changes, but it's not a big thing, I just thought you may want to know.

Chrome v90, GCA v4.3.5.

**Comment by FrutyX** [comment]
@GramThanos 

So, I've been watching this behaviour for some time, and yes, sometimes the market gets badly loaded and it's not sorted, sometimes it appears rarely, sometimes it is guaranteed when you leave Gladiatus completely.

Now, I've been saving the URL every time, it was usually the same:

**Good (sorted)**

`https://s34-cz.gladiatus.gameforge.com/game/index.php?mod=guildMarket&s=pd&sh=`
and
`https://s34-cz.gladiatus.gameforge.com/game/index.php?mod=guildMarket&s=p&sh=`

**Wrong (not sorted)**

`https://s34-cz.gladiatus.gameforge.com/game/index.php?mod=guildMarket&s=p%23&sh=`


We do rotate event items on the guild market to save our gold, if this is any useful to you, and that's all I can give to you, at least it's not crashing, like before.

**Comment by GramThanos** [comment]
Let's see if this is solved.

**Comment by FrutyX** [comment]
This one is gonna be meh to test, not only it appears only sometimes, but after this time, something changed and I have stopped completely to use GT, I can put some things on GT and check it time to time, but I also trust your fix, and the worst - kick to lobby was solved completely, so I am happy anyways.

**Comment by GramThanos** [comment]
No worries, the fix is based on your feedback, so it should be ok now.

The wrong URL had an extra %23, which is the # in url encoding (HEX 23 based on the ASCII table is #), and some times we add a #something at the back of a URL to point to spesific parts of the page. The code was misreading this part as the value for sorting the items.

Thanks for the feedback!

**Comment by FrutyX** [comment]
Finished, closing.

Re-open if needed.
