### ISSUE TITLE
German Translation [de]

### ISSUE THREAD

**Issue by Zitronenen** [DinoDevs/GladiatusCrazyAddon#244]
```javascript
/*
	Missing translations for Deutsch (German) (de)
	Add these values in the existing file or
	translate them and send them at:
	https://github.com/DinoDevs/GladiatusCrazyAddon/issues/new?template=translation.md
*/
{
global : {
	expedition_recover_full : "Volle Expeditonspunkte wiederhergestellt in",
	dungeon_recover_full : "Volle Dungeonpunkte wiederhergestellt in",
	guild_arenareports_goto : "Zu Gilden Kampfberichte",
	guild_templum_goto : "Zum Templum",
	notification_guild_attack_ready : "Die Abklingzeit für den Gildenkampf ist vorbei!",
	low_durability_items : "Es gibt {{number}} Gegenstand/Gegenstände mit einer Haltbarkeit von {{percent}}%",
}
overview : {
	more_player_info : "Weitere Informationen zum Spieler",
	can_use_max_item_level : "Kann Gegenstände bis zum Level {{max}} benutzen.",
	can_see_market_max_item_level : "Kann Gegenstände am Markt bis zum Level {{max}} sehen.",
	can_see_auction_item_levels : "Kann Gegenstände im Auktionshaus von Level {{min}} bis Level {{max}} sehen."
}

auction : {
	sort : "Sortieren",
	sort_by : "Sortieren nach",
	sort_order : "Reihenfolge",
	asc : "aufsteigend",
	desc : "absteigend"
}
markets : {
	item_cant_buy_back : "Du kannst den Gegenstand nicht zurück kaufen.",
	click_enter_to_sell : "Drücke Enter ⏎ zum Verkaufen"
}
forge : {
	show_hide_doll : "Zeige / Verstecke Ausrüstung des Charakters"
}

packages : {
	advance_filters : "Erweiteter Filter",
	advance_filters_apply : "Filter anwenden",
	advance_filters_clear : "Filter zurücksetzen",

}

settings : {
	category_pantheon : "Pantheon",
	category_global$expedition_dungeon_points_recover_timer : "Zeige benötigte Zeit für volle Expeditons- und Dungeonpunkte",
	category_global$notify_guild_attack_ready : "Benachrichtige wenn Abklingzeit des Gildenkampfes vorüber ist",
	category_global$notify_guild_attack_ready_interval : "Überprüfe Abklingzeit des Gildenkampfes (Minuten)",
	category_global$centurio_powerups_timers : "Zeige Timer zu Centurio und Pakte an der Premium Schaltfläche",
	category_global$show_forge_info : "Zeige Schmiederohstoff der Gegenstände im Tooltip",
	category_global$show_mercenaries_real_name : "Zeige den echten Söldner Namen (Typ) im Tooltip",
	category_global$global_arena_timer : "Zeige Gobale Arena",
	category_packages$small_items_layout : "Gegenstände verkleinert anzeigen",
	category_packages$special_category_features : "Aktiviere spezielle Funktionen
•Zeigt ob Schriftrollen bereits erlernt wurden
•Zeigt nicht erlernte Suffix / Präfix via Symbol am Gegenstand an",
	category_packages$double_click_open : "Pakete durch Doppelklick öffnen",
	category_packages$advance_filter : "Erweiteter Pakete Filter",
	category_merchants$show_shop_info : "Zeige Infos pro Händler (Gesamtes Gold und Rubinen)",
	category_merchants$double_click_actions : "Gegenstände verkaufen / kaufen durch Doppelklick",
	category_forge$horreum_materials_names : "[Horreum] Zeige Rohstoff-Bezeichnung",
	category_forge$horreum_remember_options : "[Horreum] Letzte Ansicht der Rohstoffkategorie merken",
	category_forge$horreum_select_meterials : "[Horreum] Rohstoff durch anklicken auswählen",
	category_arena$sort_by_lvl : "Sortiere Spieler nach Level",
	category_arena$highlight_guild_members : "Markiere Gildenmitglieder auf anderen Servern (Namensgleichheit)",
	category_arena$target_list : "Liste der Angriffsziele",
	category_market$double_click_select : "Wähle Gegenstände durch Doppelklick aus",
	category_market$sell_warning_icons : "Warnsymbol bei Verkauf von Seelengebundene Gegenstände",
	category_market$sell_with_enter : "Verkaufe Gegenstände durch Drücken der Enter-Taste ⏎",
	category_auction$save_last_state : "Zuletzt gewählter Filter als Standardeinstellung anzeigen",
	category_data$clear_cache_data : "Lösche Cache Dateien des Addons",
	translated_percent : "Aktuell übersetzt: {{number}}%",
	translated_by : "Übersetzt von: {{string}}",
	data_exported_save_the_file : "Datei wurde exportiert. Speicher die Datei.",
	missing_translations : "Fehlende Übersetzung"
}
}
```

**Comment by Zitronenen** [comment]
/*
	Missing translations for Deutsch (German) (de)
	Add these values in the existing file or
	translate them and send them at:
	https://github.com/DinoDevs/GladiatusCrazyAddon/issues/new?template=translation.md
*/

global : {
	gold_exp_data : "Gold- und Erfahrungswerte",
	merchenary_type : "Typ: {{name}} ({{number}})"
}
arena : {
	global_arena_title : "Globale Arena",
	global_arena_description : "Das ist die ultimative Arena, in der Gladiatoren aus aller Welt zusammenkommen! In dieser Arena kämpfen Gladiatoren nicht um Gold oder Erfahrung, sondern um einen Platz auf der Weltspitzenliste!",
	global_highscore : "Globale Bestenliste",
	country : "Land",
	server : "Server",
	target_list : "Liste der Angriffsziele",
	target_list_add : "Angriffsziel hinzufügen",
	target_list_remove : "Angriffsziel löschen",
	error_sth_went_wrong : "Etwas ist schief gelaufen",
	error_response : "Die Antwort vom Server zeigt an, dass ein Fehler aufgetreten ist.",
	error_blocked_access : "Etwas blockiert den Zugang zum GCA Server ({{url}})",
	error_connection : "Verbindungsfehler",
	attack_player : "Klicke um “{{name}}” anzugreifen",
	fight_won : "Du hast den Kampf gewonnen!",
	fight_lost : "Du hast den Kampf verloren...",
	player_tired : "Du hast gerade einen Kampf in der Arena bestritten",
	player1_hits_player2 : "{{name1}} schlägt {{name2}}",
	player_takes_x_damage :"{{name}} erleidet {{number}} Schaden",
	player_dies :"{{name}} gestorben"
} 
training : {
	stats_points : "Trainingsstatistik",
	points_breakdown : "Points Breakdown",
}
merchants : {
	search_item_in_merchants : "Suche Gegenstand beim Händler",
	no_such_item : "Gesuchter Gegenstand nicht gefunden."
} 
packages : {
	advance_filters_found : "(Gefunden:{{items}})"
}
reports : {
	avg_damage : "Ø-Schaden",
	avg_heal : "Ø-Heilung",
	total_hits : "Treffer gesamt",
	hits : "Treffer",
	points : "Punkte"
} 
sync : {
	are_you_sure : "Möchtest du dich als Spieler {{name}} anmelden?",
	gladiatus_crazy_addon_dependency : "Sie müssen Gladiatus Crazy Addon auf dem anderen Browser installiert haben.",
	how_to_sync_info : "Kopiere die URL und fügen diese in den anderen Browser ein oder scannen Sie den QR-Code."
} 
settings : {
	category_overview$double_click_consume : "Durch Doppelklick Gegenstände konsumieren",
	category_packages$pop_over_bag : "Beim Scrollen Inventar hervorheben",
	category_market$one_gold_mode : "Schaltfläche zum Ändern des Marktpreise immer auf 1 Gold",
	category_data$cross_browser_login : "Browserübergreifende Anmeldesynchronisation",
	show_info : "Zeige Informationen",
	each_category : "Zeige pro Kategorie",
	all_category : "Zeige pro Kategorie und gesamten Inhalt",
	do_not_run : "Nicht anzeigen"
}

**Comment by Zitronenen** [comment]
Some German changes (mistakes):

**### Old:**
// Guild donate
donate_gold_confirm : "Bist du sicher, dass du {{number}} gold spenden möchtest?",
donate_gold_failed : "Deine Goldspende schlug fehlt",
donate_gold_no_gold : "Kein Gold zum spenden vorhanden",
can_use_max_item_level : "Kann Gegenstände bis zum Level {{max}} benutzen.",

// More player info
can_use_max_item_level : "Kann Gegenstände bis zum Level {{max}} benutzen.",
can_see_market_max_item_level : "Kann Gegenstände am Markt bis zum Level {{max}} sehen.",
can_see_auction_item_levels : "Kann Gegenstände im Auktionshaus von Level {{min}} bis Level {{max}} sehen."

// Medic
medic_lost_points : "Verlorene Punkte",
medic_points_to_heal : "Punkte zum heilen",

// Info
items_info : "Gegenstands Informationen",

// Settings - Global
category_global$language_select : "Add on Sprache ändern",
category_global$quest_timer : "Aufgaben timer anzeigen",
category_global$cooldown_sound_notifications : "Aktiviere sound Benachrichtigungen (Expedition, Dungeon, Arena)",
category_global$gold_exp_data : "Zeige Gold und Erfahrung Daten an",
// Settings - Messages
category_messages$send_message_box : "Aktiviere die Nachricht senden box",

// Settings - Market
category_market$cancel_all_button : "Zeige Alle-abbrechen-Taste",
category_market$remember_sell_duration : "Merken die zuletzt gewählte Verkaufsdauer",

// Settings - Auction
category_auction$item_price_analyze : "Analisiere die Preise der Gegenstände",

// Settings - Data
category_data$reset_settings : "Setzt die Einstellungen des Addons zurück",
category_data$clear_data : "Lösche alle Addon Daten",
category_data$clear_cache_data : "Lösche Cache Dateien des Addons",

// Info
reset_settings_confirm : "Möchtest du die Einstellungen des Addons wirklich zurücksetzen?",




**### NEW:**
// Guild donate
donate_gold_confirm : "Bist du sicher, dass du {{number}} **G**old spenden möchtest?",
donate_gold_failed : "Deine Goldspende schlug fehl",
donate_gold_no_gold : "Kein Gold zum **S**penden vorhanden",

// More player info
can_use_max_item_level : "Kann Gegenstände bis zur Stufe {{max}} benutzen.",
can_see_market_max_item_level : "Kann Gegenstände am Markt bis zur Stufe {{max}} sehen.",
can_see_auction_item_levels : "Kann Gegenstände im Auktionshaus von Stufe {{min}} bis {{max}} sehen."

// Medic
medic_lost_points : "Verlorene Punkte",
medic_points_to_heal : "Punkte zum **H**eilen",

// Info
items_info : "Informationen zu Gegenstände",

// Settings - Global
category_global$language_select : "Add-on Sprache ändern",
category_global$quest_timer : "Aufgaben Timer anzeigen",
category_global$cooldown_sound_notifications : "Aktiviere Sound Benachrichtigungen (Expedition, Dungeon, Arena)",
category_global$gold_exp_data : "Zeige Gold- und Erfahrungswerte an",

// Settings - Messages
category_messages$send_message_box : "Aktiviere die Nachricht Senden-Box",

// Settings - Market
category_market$cancel_all_button : "Zeige Alle-Abbrechen-Taste",
category_market$remember_sell_duration : "Merke die zuletzt gewählte Verkaufsdauer",

// Settings - Auction
category_auction$item_price_analyze : "Analysiere die Preise der Gegenstände",

// Settings - Data
category_data$reset_settings : "Setzt die Einstellungen des Add-ons zurück",
category_data$clear_data : "Lösche alle Add-on Daten",
category_data$clear_cache_data : "Lösche Cache Dateien des Add-ons",

// Info
reset_settings_confirm : "Möchtest du die Einstellungen des Add-ons wirklich zurücksetzen?",

**Comment by GramThanos** [comment]
Changes implemented 557440532a0e9777a4e20e839fc96c3176507261

**Comment by GramThanos** [comment]
Thank you very much mate!

**Comment by Zitronenen** [comment]
`/*
	Missing translations for Deutsch (German) (de)
	Add these values in the existing file or
	translate them and send them at:
	https://github.com/DinoDevs/GladiatusCrazyAddon/issues/new?template=translation.md
*/

training : {
	points_breakdown_damage : "Schaden: +{{integer}} (+{{float}})",
	points_breakdown_block : "Block: +{{integer}}% (+{{float}}%)",
	points_breakdown_block_max : "Block: max. Wert",
	points_breakdown_normal_hit : "Trefferchance: +{{integer}}% (+{{float}}‰) *",
	points_breakdown_critical_hit : "Kritische Trefferchance: +{{integer}}% (+{{float}}‰)",
	points_breakdown_double_hit : "Doppelschlag Chance: +{{integer}}% (+{{float}}‰) *",
	points_breakdown_avoid : "Chance kritische Treffer zu vermeiden: +{{integer}}% (+{{float}}‰)",
	points_breakdown_avoid_max : "Chance kritische Treffer zu vermeiden: max. Wert",
	points_breakdown_enemy_normal_hit : "Gegnerische Trefferchance: {{integer}}% ({{float}}‰) *",
	points_breakdown_enemy_double_hit : "Gegnerische Doppelschlag Chance: {{integer}}% ({{float}}‰) *",
	points_breakdown_life : "Lebenspunkte: +{{number}}",
	points_breakdown_regeneration : "Regeneration pro Stunde: +{{number}}",
	points_breakdown_heal : "Heilung: +{{integer}} (+{{float}})",
	points_breakdown_critical_heal : "Kritische Heilungswertung: +{{integer}}% (+{{float}}‰)",
	points_breakdown_critical_heal_max : "Kritische Heilungswertung: max. Wert",
	
}
forge : {
	horreum_material_change : "Horreum - Rohstoff wurde aufgewertet"
}

settings : {
	category_accessibility : "Bedienungshilfe",
	category_accessibility$white_level_indicators : "Ändere die Stufen-Anzeige der Gegenstände in die Farbe weiss" ,
	category_accessibility$qualty_symbols_indicators : "Füge ein Symbol als Qualitätsindikator auf Gegenstände hinzu",
	category_accessibility$tooltips_qualty_white : "Ändere den Titel der Gegenstände im Tooltip in die Farbe weiss",
	category_accessibility$tooltips_qualty_symbols : "Füge ein Symbol als Qualitätsindikator im Tooltip hinzu",
}`

**Comment by GreatApo** [comment]
Awesome thanks!

There are still a few more if you are for the task :P
```
/*
	Missing translations for Deutsch (German) (de)
*/

global : {
	gold_exp_data_package_tax : "Weekly gold-to-package tax"
}
training : {
	points_breakdown_threat : "Threat: +{{integer}} (+{{float}})",
	stats_calculated_with_yourself_as_an_opponent : "* Stats are calculated with the concept of attacking yourself."
}
reports : {
	dodge : "Dodges or Blocks"
}
settings : {
	category_overview$block_avoid_caps : "Show block and Avoid caps",
	category_messages$fix_header_links : "Fix messages title link click bug",
	category_data$export_error_player_settings : "Export unknown-user data to file"
}
```

**Comment by Zitronenen** [comment]
I know, but I don't know how translate the last one =)

You can clear Zitronen because Zitroenen = Sleeping*Shadow =)

**Comment by Zitronenen** [comment]
Sorry Apo, i have an Translation Mistake in:
Wrong: `category_forge$horreum_remember_options : "[Horreum] Letzte Ansicht der Rohstoffkategorie merken",`

True: `category_forge$horreum_remember_options : "[Horreum] Merke gewählte Einstellungen zur Einlagerung (Inventar | Pakete)",`

**Comment by GreatApo** [comment]
> Sorry Apo, i have an Translation Mistake in:
> Wrong: `category_forge$horreum_remember_options : "[Horreum] Letzte Ansicht der Rohstoffkategorie merken",`
> 
> True: `category_forge$horreum_remember_options : "[Horreum] Merke gewählte Einstellungen zur Einlagerung",`

Thanks for spotting it!

**Comment by Zitronenen** [comment]
I have an Translation Mistake in:
Wrong: category_market$sell_warning_icons : "Warnsymbol bei Verkauf von Seelengebundene Gegenstände",

True: category_market$sell_warning_icons : "Warnsymbole bei Verkauf von Gegenständen anzeigen",

**Comment by GreatApo** [comment]
> I have an Translation Mistake in:
> Wrong: `category_market$sell_warning_icons : "Warnsymbol bei Verkauf von Seelengebundene Gegenstände",`
> 
> True: `category_market$sell_warning_icons : "Warnsymbole bei Verkauf von Gegenständen anzeigen",`

Thanks, changed!
