### ISSUE TITLE
Polish translations

### ISSUE THREAD

**Issue by Sorky96** [DinoDevs/GladiatusCrazyAddon#245]
**Language name in English**
 - Language: Polish
 -

**
[pl.txt](https://github.com/DinoDevs/GladiatusCrazyAddon/files/6177197/pl.txt)
**
I added separators for each category so I don't want to simply add translations with provided template and cant do push to repository :c I convert .js to .txt so you must convert it to .js again

**Comment by GramThanos** [comment]
Thanks for the translation, I will check it.
Don't worry about the format, I will parse it to a valid format.
