### ISSUE TITLE
Completely missing line (translations) ?

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#246]
Hey,

I've noticed, that the notice for horreum isn't translated, so I went to Github to add it, but, I've found out that it's not even in the english version, the line is completely missing.

![horreum](https://user-images.githubusercontent.com/23278552/112464277-953cca80-8d63-11eb-94ac-09ccc4b03842.PNG)

**Comment by GramThanos** [comment]
Missing translation added.
