### ISSUE TITLE
Medic console error

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#250]
Chrome v89, 
GCA v4.3.4 (this is also present in 4.3.5).

There is an console error on the medic site:

```
guild.medic.js?4.3.4&built=1617109276560:28 Uncaught TypeError: Cannot read property '1' of null
    at Object.improve (guild.medic.js?4.3.4&built=1617109276560:28)
    at Object.inject (guild.medic.js?4.3.4&built=1617109276560:13)
    at fireLoad (guild.medic.js?4.3.4&built=1617109276560:119)
    at guild.medic.js?4.3.4&built=1617109276560:122
    at guild.medic.js?4.3.4&built=1617109276560:127
```

![error](https://user-images.githubusercontent.com/23278552/112999386-31edd680-916f-11eb-81a3-a032c31a69e1.png)

**Comment by GramThanos** [comment]
Can you share a screenshot of the medic site description?

![image](https://user-images.githubusercontent.com/14858959/113011495-877fae80-9182-11eb-8872-dd3afd24e8ef.png)

I would like to see the format of heling percentage on the description.

**Comment by FrutyX** [comment]
![medic](https://user-images.githubusercontent.com/23278552/113014486-e9d5b080-917c-11eb-9504-9b32882a8b0c.PNG)
