### ISSUE TITLE
Notes - Quick menu option

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#251]
An idea came to my mind about notes in Gladiatus, it ain't no big deal, but if you gonna like the idea....

I believe people would more use them, if they were even more accessible, the quick menu should help us with this, and it would be more comfortable, it would work the same way as guild messages, just an window to the notes section.

A picture will explain it much better:

![notes](https://user-images.githubusercontent.com/23278552/112994777-e20d1080-916a-11eb-876a-a9af8391ca97.PNG)

**Comment by GreatApo** [comment]
Notes are pretty much useless and they are just one click away anyway :)

**Comment by FrutyX** [comment]
Wow, you solved this one quickly, but I actually use them, I save there the event schedule for example (and a few other things about the game...), but it's better than keeping it open and never actually doing it, you should do that to many other requests/issues too... probably...

**Comment by GreatApo** [comment]
> Wow, you solved this one quickly, but I actually use them, I save there the event schedule for example (and a few other things about the game...),

I also keep notes, in my notepad++ :P

> but it's better than keeping it open and never actually doing it, you should do that to many other requests/issues too... probably...

Exactly
