### ISSUE TITLE
Accessibility - symbols in wrong tooltips (4.3.5)

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#253]
Chrome,
GCA 4.3.5.

Hey, I know that these new versions aren't polished and meant to be used before they are released by you, but I've been running it mostly because of #240 ( and a few other fixes you did) and I found something.

The new feature "Quality symbols in tooltips" is also showing in wrong tooltips, for example, it is showing when you hover on your gold, or expedition, costume and more, it's not completely everywhere (XP and life bar doesn't have it for example).
![kost](https://user-images.githubusercontent.com/23278552/113146603-29110980-9230-11eb-95a6-71bce7e19cbe.PNG)
![ar](https://user-images.githubusercontent.com/23278552/113146606-29a9a000-9230-11eb-8bf8-8e61e1cc1df9.PNG)
![exp](https://user-images.githubusercontent.com/23278552/113146608-29a9a000-9230-11eb-9489-43e8b3e47cc5.PNG)
![ur](https://user-images.githubusercontent.com/23278552/113146609-2a423680-9230-11eb-85df-566ca9502959.PNG)

**Comment by GramThanos** [comment]
I am aware of that but not sure how to fix it.

**Comment by FrutyX** [comment]
If you don't find a solution, I can offer a possible idea.

Move the symbols on the same line before the text, that will look like it maybe even belongs there.

![zlat2](https://user-images.githubusercontent.com/23278552/113166257-e147ad80-9242-11eb-8ef7-cc67a5fca47a.PNG)
![zlat](https://user-images.githubusercontent.com/23278552/113166259-e1e04400-9242-11eb-9be5-d6d48d837997.PNG)


I mean... it looks better, I think...

**Comment by GreatApo** [comment]
I think I found a workaround. There is still a problem in items with less than 2 lines tooltips (e.g. Malefica items, or the gold in packets), however the quality of such items is usually not of importance. @GramThanos @FrutyX let me know if we can close this as patched.

**Comment by FrutyX** [comment]
@GreatApo Yes, it's gone.

It is showing in the malefica tooltips, but I don't see it in gold tooltips in packets, which is a good thing, I guess.

I'll possibly re-open if I see it somewhere where it shouldn't be, I am running on 4.3.5 anyways.

**Comment by GramThanos** [comment]
Alternative fix pushed on 55745ec92d1a58cb43e80246b44ba07ed7b6fb90

**Comment by FrutyX** [comment]
This one is good, on the list with #294.

Closing, re-open if needed.
