### ISSUE TITLE
Packages - last page load

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#258]
Chrome,
v4.3.5.

> v4.3.4
> BUG FIXES
> 
> Packages
> 
> - Fixed not parsing last page upon auto load

I thought this was fixed, but it wasn't, it happened to me already multiple times when I was selling my packages stuff.

For the bug description, for example, you go and search for specific items in your packages (filter them), and you move them to your inventory, but when you reach the end, the last page isn't loaded well and isn't recognized by the addon, which means no colors, no double-clicking, no anything from the addon features.

**Comment by FrutyX** [comment]
I went to test it to check if this is still a problem and I have some fresh results.

It is happening, but I didn't seen it for a long time, it is since I set my maximum loaded pages limit in packages to 10,  I had only 3 max before, this time I set it only to 1 and the problem instantly occurred.

So it seems having a small number of loaded pages in packages is triggering this.

As you can see here, the last page was loaded and the last items are not recognized by GCA:

![Last](https://user-images.githubusercontent.com/23278552/132779023-e5b0d8a4-f7a6-4a96-b0d6-76ae25ac7e91.PNG)

Tested on:
Chrome Canary 95.0.4636.3 
GCA v4.3.5

**Comment by FrutyX** [comment]
You probably won't go away with this so easily :D. It seems they are recognized that they have their colors, but I cannot double-click them, they just won't move, only the normal way works.

**Comment by GramThanos** [comment]
I forgot to correct line 795...

**Comment by FrutyX** [comment]
Well, I think this time you finally fixed it, no problem found, congratulations! :D

**Comment by FrutyX** [comment]
On the list with #294.

Fixed, closing, re-open if needed.
