### ISSUE TITLE
Setting Export / Import via Cloud?

### ISSUE THREAD

**Issue by Zitronenen** [DinoDevs/GladiatusCrazyAddon#259]
Would it be technically possible to automatically keep the Setting Export and Import file up to date via a cloud?
I save the file in a cloud and use it for import and export. This exchange takes place after a freely adjustable time.

Therefore, all devices (tablet, mobile phone and computer) would be up to date.

**Comment by GramThanos** [comment]
I am not sure if this can be done.

But I think there is an alternative solution... we can store your settings inside on your Gladiatus notes :P
What do you think?

**Comment by Zitronenen** [comment]
I don't know exactly what you mean by the notes. How can the export file be saved in the notes?

**Comment by GramThanos** [comment]
We can save your settings at the bottom of your notes:
![image](https://user-images.githubusercontent.com/14858959/114284884-ad972f80-9a5b-11eb-9a09-fe20c2ae27df.png)

**Comment by Zitronenen** [comment]
Is the content of the complete .gca file saved here? Wouldn't that be too many signs?
Or whats your plan? =)

**Comment by GramThanos** [comment]
It is just an idea.

The file is actually just a txt (you can rename it to `something.txt` and see it's contents).
My file for example is about 4.000 characters and I only use about 3.000 of my Gladiatus notes.
Assuming that you also use about 2/3 or less of your notes, they will fit.
I will also try to minimize the save.

**Comment by Zitronenen** [comment]
The add-on settings are usually hardly changed. However, the target list is probably the most important list. You could have this written in the notes.

**Comment by FrutyX** [comment]
When talking about settings save files, I would like to mention, that some of the options aren't saved when importing/exporting, for example, the minimum number for wear&tear of items isn't saved and is always default, and there are more of these, i just can't name them all from my memory, and I don't import/export my settings on daily basis of course... But I've been doing it when I had my problem "kick to lobby" and I know, that I had to change some of these settings manually, even when I made a new exported file...

Are they simply missing in the "save data" function? Something like was with missing translations?

**Comment by Zitronenen** [comment]
The new feature is very nice. Easy export and import =)
The message "OK" is output during the export.
No message is issued during the import.

I would change the message "OK" to the following: "Export Target List OK" ... "Import Target List OK"

Question: Is an automatic export actually possible with an adjustable interval? But i think is a nice to have ...

**Comment by GramThanos** [comment]
Well.. for exporting, there is no need for "automatic". You can just export it whenever you click to save your settings or uppon a new addition on target list. For importing, you can force run on settings visit or at an interval e.g. once every 3-4 hours. When exporting, you may save the export time and if a conflict is detected, user will have to resolve it. These are just thoughts.

**Comment by Zitronenen** [comment]
I see i comment the wrong issues... :/ 
https://github.com/DinoDevs/GladiatusCrazyAddon/issues/268

**Comment by GramThanos** [comment]
No problem.

**Comment by FrutyX** [comment]
Basically a duplicate now, refer to #268, so we don't cause some mess in Issues.

Closing
