### ISSUE TITLE
Firefox and it's warnings ⚠️

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#260]
Firefox, v4.3.4.

Sometimes I do use Firefox and there is something that may interest you, or maybe not, that's up to you.

Firefox has problem with a GCA cookie, it's in my language, but I'll translate it for you.

> Cookie „gca_players“ will be soon blocked, because it contains the "SameSite" attribute with an invalid value or value "None", that isn't allowed without the attribute "secure". You will find more about the "SameSite" attribute here:
> https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

It is possible, that Firefox decides, to block the cookie, as you can read, so I thought it may interest you.
Feel free to close this anytime.

It does have problem with some of the Gameforge cookies, but that isn't your problem.

**Comment by GramThanos** [comment]
I will look into it to understand what exactly is the problem. Maybe we will have to notify Gameforge regarding this.

**Comment by FrutyX** [comment]
I've been reviewing my issues and about this one, well, Firefox likes to complain.

But I didn't catched Gameforge cookie this time (don't tell me they actually did something), only GCA cookies, and according to my browser, their cookies are set to "Strict" and "Lax".

I actually think, that this one could be easily fixed by editing that attribute for GCA cookies, it's basically just an security thing, I don't know why Firefox has to threaten us that it will reject the cookie one day (yea, one day, haha).

![gca2](https://user-images.githubusercontent.com/23278552/125874987-80412bab-7d7a-45e6-8878-9ea13fb136a3.PNG)

**Comment by GramThanos** [comment]
Looks like it is GCA related. I will have a look.

**Comment by FrutyX** [comment]
Testing.

**Comment by FrutyX** [comment]
If there was a problem, I think I would have noticed it by now, on the list with it and closing.
