### ISSUE TITLE
Settings page problems

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#262]
Chrome, v 4.3.5.

So today, I had to clean my browser, and as I mentioned in #259 , there are problems with exporting/importing my settings, simply some options I made are not changed when I import back my settings.

I have freshly exported my settings and imported them, but it seems some (or most) of my preffered settings, are just not imported at all.

**Updated 29/8/2021**

Was set to <-->
![mater](https://user-images.githubusercontent.com/23278552/115053518-81f2ca00-9edf-11eb-9085-ecf3b8b2d07e.PNG)

Was set to Czech.
![lang](https://user-images.githubusercontent.com/23278552/115053621-9cc53e80-9edf-11eb-870f-beb19f06616c.PNG)

Was set to 8h.
![gca1](https://user-images.githubusercontent.com/23278552/131259504-8da1b6be-edff-4cdf-9451-59412b16af67.PNG)

Was set to Run on target category& all
![gca2](https://user-images.githubusercontent.com/23278552/131259507-82e63ed7-6526-4d3a-b145-42d4773407c7.PNG)

Was set to 120 ( Attention: This slider seems to refresh to 100 no matter what I set when this settings page gets refreshed, but I guess it should be saved, when I saved it and it was 120)
![cond](https://user-images.githubusercontent.com/23278552/115053809-d433eb00-9edf-11eb-97b6-e72f6c7e2637.PNG)

It may feel like it does not work at all, but the Target List and the Quick menu loads without any problem.

**Comment by FrutyX** [comment]
Oh yes, I guess it would be nice if I added my file too, so here you go.

Oh well, Github does not want .gca, I'll upload it on my website:

http://frutyx.maweb.eu/settings.gca

**Comment by GramThanos** [comment]
:cry: :sob:

**Comment by FrutyX** [comment]
So I have tried the new import/export way via notes, unfortunately, it's completely the same, it won't load some settings, not even the language :-/.

**Comment by FrutyX** [comment]
Little update: for now, some settings that are mentioned above are getting imported, and some are always default (like the language, durability slider, auction status bar etc..).

Didn't GCA had an auto-language-detect script? If yes, I think it never really worked much, if not and I am mistaken. then you could really use such a script, the language settings is something, that never gets loaded, even when imported.

To be completely honest, I think the whole GCA settings could use a little update, I mean the code, I think it's getting a bit rusty, most importantly the import/export function, could use a little code rework (or cleanup possibly).

**Comment by GramThanos** [comment]
I looked into this problem multiple times but I was not able to reproduce it. I will look into that again.

**Comment by FrutyX** [comment]
I understand.

Take a look at the first post here, I have updated it, there is now so much less items that doesn't work, which is a good thing, unfortunately, I am unable to help you more, I've tried playing with it, but these examples just wont load no matter what I try, the console isn't saying anything either.

By the way, one thing I never noticed is, that the buttons On and Off aren't and can't be translated, when I think about it, for anyone who does not know english (ye I know, who doesn't know english these days :D), On or Off can be a bit confusing, but then again, it's just a small detail.

**Comment by GramThanos** [comment]
I found the problem on this one.
I patched it, though it will reset the following settings (which you also identified):

- global
	- show_durability
	- min_durability
	- show_forge_info
- packages
	- special_category_features
- market
	- sell_duration

I will also fix the sound system in the same way.

**Comment by FrutyX** [comment]
Holy moly, you did find it? Damn nice, will test it later and throw some feedback.

Nice to see you are back doing some stuff with GCA :D. Hopefully in a few weekns, we could (possible?) release v4.3.5, it contains a lot of fixes and works (so far) very well.

**Comment by FrutyX** [comment]
Yes!!! It's getting loaded! It's seems my old settings file is useless now, because it was not loading well with it, so I made a new one, and it works!

Importing with file works good, no problem there, only importing from notes has one single problem - it loads everything but not the language, it's default, you probably need to check that.

Well done!

**Comment by FrutyX** [comment]
This is seriously pissing me off, I was visiting and changing my settings to check an old GCA bug, and this slider...... it just keeps resetting itself again! I have it always, always, and I have checked this before I changed my settings set to 120 and it just goes back to 100.

![Výstřižek](https://user-images.githubusercontent.com/23278552/133880464-42c8b766-71d2-40bb-833e-61e28e9721f3.PNG)

It does not happen when you enter/refresh the settings page, but when you change something and save it, it goes to 100 .

**Comment by GramThanos** [comment]
> This is seriously pissing me off, I was visiting and changing my settings to check an old GCA bug, and this slider...... it just keeps resetting itself again! I have it always, always, and I have checked this before I changed my settings set to 120 and it just goes back to 100.
> 
> ![Výstřižek](https://user-images.githubusercontent.com/23278552/133880464-42c8b766-71d2-40bb-833e-61e28e9721f3.PNG)
> 
> It does not happen when you enter/refresh the settings page, but when you change something and save it, it goes to 100 .

This should be fixed now.

**Comment by FrutyX** [comment]
Can confirm, thank you!

**Comment by FrutyX** [comment]
"Problems" fixed, on the list with #294.

Closing, re-open if needed.
