### ISSUE TITLE
Quest item reward info

### ISSUE THREAD

**Issue by PatrykLeczycki** [DinoDevs/GladiatusCrazyAddon#265]
I think it would be nice to have some info about value of quest reward items, maybe somewhere in this area:

![image](https://user-images.githubusercontent.com/24533415/115723926-c15a6400-a380-11eb-8267-26e8c9a2494d.png)

During events with -50% cooldown for quests it would be much faster to accept quests with rings/amulets as reward by just looking on some numbers rather than pointing at every single reward item.

**Comment by GreatApo** [comment]
![image](https://user-images.githubusercontent.com/9620510/147303107-a96ffbc4-1188-4f33-b1ef-81a13db80a22.png)

**Comment by FrutyX** [comment]
A green from me, looking good!

**Comment by GreatApo** [comment]
Add item name too

**Comment by SleepingShadow-bit** [comment]
> Add item name too

@GreatApo @FrutyX Can someone tell me where to find the name?  Should this be displayed?

**Comment by FrutyX** [comment]
No, I think it wasn't scripted, only suggested.

**Comment by FrutyX** [comment]
God be with us.

It ain't perfect, I know.

**Comment by FrutyX** [comment]
Maybe if Apo is lurking, he can tweak it so the css is applied only on quests with an item, probably... I am not sure.

**Comment by FrutyX** [comment]
Or you think it's fine like this? I mean, I wouldn't say it's a big deal, if it's empty, then well... no item reward, lol.

**Comment by GreatApo** [comment]
> Or you think it's fine like this? I mean, I wouldn't say it's a big deal, if it's empty, then well... no item reward, lol.

![image](https://user-images.githubusercontent.com/9620510/200144631-6b0ead0c-3344-4fee-ae9e-f3342818e561.png)

Is this better? I don't like the current solution

**Comment by FrutyX** [comment]
There is a reason, why it's not there, you know how long the item names are? You should know that, when Greek got the a very long words, there was no way I could fit the names in there.

**Comment by GreatApo** [comment]
> There is a reason, why it's not there, you know how long the item names are? You should know that, when Greek got a very long words, there was no way I could fit the names in there.

I have only the prefix presented, not the rest of the name :) (the whole name doesn't fit in the UI and it is not scalable)

**Comment by FrutyX** [comment]
![example](https://user-images.githubusercontent.com/23278552/200146339-e3be1c67-b23f-421b-a7e5-6c1df40a8a65.PNG)

Lucky me, this is a very good example.

**Comment by GreatApo** [comment]
> ![example](https://user-images.githubusercontent.com/23278552/200146339-e3be1c67-b23f-421b-a7e5-6c1df40a8a65.PNG)
> 
> Lucky me, this is a very good example.

Fruty, I am showing only the preffix (eg. Quintas)

**Comment by FrutyX** [comment]
You could potentially show only the prefix/suffix (if that is possible) but that sounds more like a downgrade honestly.

**Comment by GreatApo** [comment]
It partially is but I don't see how this can nicely fit in the UI

**Comment by FrutyX** [comment]
Well, another approach would be to create a completely new element under it, basically the same like now but nice (with it's own design), but that will require rewriting the code, most of it, I guess.

**Comment by FrutyX** [comment]
With some logic, I suppose people hunt for prefixes and suffixes, so yes, you could do that, but I seriously leave that only to you, because I already had some hiccups with this already, and the outcome isn't perfect, as you can see.

**Comment by FrutyX** [comment]
At first, I was playing with it a lot, because I didn't wanted to add it to a new line, but like I said, there is no way you can fit the full name there, even with some css edits, it was just bad. And I didn't get any other ideas, because you do this to get rid of the hover effect, that's the point, so your options are very limited.

**Comment by GreatApo** [comment]
![image](https://user-images.githubusercontent.com/9620510/200147194-282e15e2-4e86-4a49-b4b3-2c715ec2bfca.png)
What about this? It will cut the text it is longer but it is the best/nice we can do

**Comment by FrutyX** [comment]
Look, if you like it more, implement it. But again, people want to see it, so they don't have to hover over the image, if you cut it and add a a mouse over, how different will that be from hovering over the image?

It really depends on the language, some names will be alright, some, like Greek, will be with a hidden overflow.

But I guess it's better than my implementation.

**Comment by GreatApo** [comment]
I think it is a nice and neat solution that doesn't interfere a lot with the UI and it will work most of the time :)

**Comment by FrutyX** [comment]
![time](https://user-images.githubusercontent.com/23278552/200147378-ae831d72-fb3c-48a9-8bbd-f2bb80b3579b.PNG)

By the way, some quests are time limited and have an timer, it could collide? There isn't much space.

**Comment by FrutyX** [comment]
Yes, the idea and implementation isn't difficult, placing it in the UI layout, that's a damn mystery.

**Comment by GreatApo** [comment]
> ![time](https://user-images.githubusercontent.com/23278552/200147378-ae831d72-fb3c-48a9-8bbd-f2bb80b3579b.PNG)
> 
> By the way, some quests are time limited and have an timer, it could collide? There isn't much space.

It works:
![image](https://user-images.githubusercontent.com/9620510/200147460-63c90153-8dc5-4ee9-9ec3-af7fa4dab87e.png)

XD

**Comment by FrutyX** [comment]
Actually, it does, if you do some css changes, you could the time, if it will not collide with the upper text.

**Comment by GreatApo** [comment]
![image](https://user-images.githubusercontent.com/9620510/200147538-eb944b7b-4a42-4ae2-91dd-291b7d5d3c7e.png)

**Comment by FrutyX** [comment]
Yeah, that's actually pretty good, and I doubt any language text will touch that, not even Greek seems to be that long (lol).

**Comment by FrutyX** [comment]
ngl, this is a close one:
![close](https://user-images.githubusercontent.com/23278552/200147633-72e2e8b6-838d-4282-8eeb-97dba843ffa9.PNG)

**Comment by FrutyX** [comment]
I don't know how the final result will look like, but playing with this width, you can move the whole rewards sections more closely to the "Reward:" area. Perhaps? It would buy you more space for the item.

![width](https://user-images.githubusercontent.com/23278552/200147775-961a11d4-4c68-4645-ba2f-e14c8e42ce29.PNG)

**Comment by FrutyX** [comment]
In the end you'll rewrite the whole layout lmao, that's something I was trying to avoid, but sometimes there is no choice.

**Comment by GreatApo** [comment]
![image](https://user-images.githubusercontent.com/9620510/200148294-e511aa10-43b5-499d-ab81-c6dc96120814.png)

I just found how to scale the bg... hahaha

**Comment by GreatApo** [comment]
Is it better aligned?
![image](https://user-images.githubusercontent.com/9620510/200148341-d9d6b7af-8bde-4757-ba18-5445c674e6dc.png)

**Comment by FrutyX** [comment]
lol, well, now that is a solution too... Yeah, that's good as well.

**Comment by GreatApo** [comment]
Nice! Good job!

**Comment by FrutyX** [comment]
> Nice! Good job!

No, you good job! :D 

At last, I think some people will appreciate this feature. 

Two heads are better than one.

**Comment by GreatApo** [comment]
> Two heads are better than one.

Always!
