### ISSUE TITLE
Filtering packages by food health amount

### ISSUE THREAD

**Issue by PatrykLeczycki** [DinoDevs/GladiatusCrazyAddon#266]
It might be helpful to be able to filter food by health amount it gives after use in this filter tool:

![image](https://user-images.githubusercontent.com/24533415/116465984-3e4c7880-a86e-11eb-8f95-ee6b08542567.png)

**Comment by Zitronenen** [comment]
Further filtering by market, expeditions or auctions would also be great

**Comment by FrutyX** [comment]
Merged all "filter" request issues into one, from now, please use #343.

Closing.
