### ISSUE TITLE
Filter packages by resources or simply indicate ones meeting given conditions

### ISSUE THREAD

**Issue by drzuby** [DinoDevs/GladiatusCrazyAddon#267]
In packages, it would be great to have possibility to filter items based on the resources it consists of.

Another approach to this might be global setting to specify resources I'm interested in, and then somehow highlight appropriate items which meets the condition in all market, auction house, packages, shops, guild warehouse etc. Places where the items should be highlighted might be also configurable, but I don't find it necessary.

**Comment by FrutyX** [comment]
Merged all "filter" request issues into one, from now, please use #343.

Closing.
