### ISSUE TITLE
Synchronizing settings between browsers

### ISSUE THREAD

**Issue by PatrykLeczycki** [DinoDevs/GladiatusCrazyAddon#268]
Currently adding a new player to the target list saves it on only one currently used browser - other browsers don't know about any changes that were made. If only there's any possibility to make target list data independent on browsers, it would be great to see some improvements on this matter.

**Comment by FrutyX** [comment]
Well, nothing big, just undefined, you know what to do.

I will do more testing later.

![gca](https://user-images.githubusercontent.com/23278552/125873100-572a54b4-c6ff-4776-a8b3-c1ccfd106711.PNG)

**Comment by GramThanos** [comment]
I left this on purpose so that we don't get translation contributions before finalizing the feature.

**Comment by FrutyX** [comment]
By the way, i did tested this some time ago, and for this issue only, I think it worked without problems.

The big stop sign was #262, which makes import/export not reliable, but you need to do some testing on your own, because I don't know if anyone else has this problem.

**Comment by FrutyX** [comment]
I believe you can finish this feature, if we ignore #262 (which can be an individual bug), this feature does work and I don't have nor see any problem with it.

**Comment by FrutyX** [comment]
Found an problem in #262 (language not loading), needs to be fixed.

**Comment by FrutyX** [comment]
@GramThanos oh yes! You did fixed the language export, unfortunately, when clicking on export to notes, there is an console error, but it works fine:

`settings.js?4.3.5&built=1638924637962:2238 Uncaught ReferenceError: data is not defined`
    `at Object.success (settings.js?4.3.5&built=1638924637962:2238)`
    `at j (jquery.js:3)`
    `at Object.fireWith [as resolveWith] (jquery.js:3)`
    `at x (jquery.js:3)`
    `at XMLHttpRequest.b (jquery.js:3)`


![error](https://user-images.githubusercontent.com/23278552/145129019-4a565572-b99a-4c01-b902-83282e2b2211.PNG)

**Comment by GramThanos** [comment]
The behavior after export to settings and import from settings needs to be swapped.

- reload on save
- show notification on export

**Comment by Zitronenen** [comment]
I think we need an nottification?

Export current: Ok 
Export New: Export Data Ok

Import current: ...
Import New: Import Data Ok

**Comment by FrutyX** [comment]
I know you are gonna say "it's not a must", but...

You always propose things I wouldn't even notice :).

**Comment by Zitronenen** [comment]
Sry
