### ISSUE TITLE
Workbench new feature possible bug

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#272]
Chrome 91.0.4472.124
GCA v4.3.5
(Czech language)

Hello there, so I've been using v4.3.5 for a while, and I believe i have discovered an entirely new bug, even after so long.

Now, the new feature where you can get repaired items directly from the workbench without getting to the packages is throwing an error at me, but not everytime. So I went to see what is going on, when I have been repairing my own items, it was okay, but when I did this with new crafted items, the problem occured, the window was stuck at loading and GCA noted an error, the item was sent to packages instead.

So far, it looks like  it is throwing this error when trying to retrieve items that are not soulbound.

![error](https://user-images.githubusercontent.com/23278552/123999861-41312a00-d9d3-11eb-8267-db9195209071.PNG)
![error2](https://user-images.githubusercontent.com/23278552/124000626-0ed3fc80-d9d4-11eb-95f5-2d8014a86ca6.PNG)

Console:

`gca.locale.js?4.3.5&built=1625071673521:63 Function "success" called gca_locale.get("global", "error") which is undefined!`

I don't know if it is any useful to you, it seems that's all I can get from it, but I can reproduce it anytime.
Let me know if you need anything else from me.

Edit: Tested on Edge, error too.
Edit 2: Actually, it's not that new, is it? :) Anyways, I tested it on Firefox with 4.3.4 installed, I got this error too.

**Comment by GramThanos** [comment]
The error itself is just a bad translation reference. Did this button fails a lot for you are just once in a while? (if I remember correctly, it just just checks the first and the last page of your packages to find the item)

**Comment by FrutyX** [comment]
Every single time when I try to repair an item that is not soulbound, this error pops up.

**Comment by GramThanos** [comment]
@FrutyX thanks for the help, the problem was mostly related to non-soulbound items, as you identified.
Please let me know it any similar problem come up.

**Comment by FrutyX** [comment]
Yup! Just tested it, it is fixed.

I am happy I was helpful and thank you for the fix! :)

**Comment by FrutyX** [comment]
Terminated, so closing this.

Re-open if needed.
