### ISSUE TITLE
Package Feature - Items Prize without "Improve items layout"

### ISSUE THREAD

**Issue by Zitronenen** [DinoDevs/GladiatusCrazyAddon#274]
**Describe the bug**
See the Screenshot. It would not be bad if those features that are dependent on other features are to be grayed out or only to be activated.

I know its a nice to have =)
![Without_Improve items layout](https://user-images.githubusercontent.com/8767665/126049929-6b99228c-6e3e-474e-a57b-f45735215008.png)

Acitivated "Improve Items Layout"
![Activated_Improve items layout](https://user-images.githubusercontent.com/8767665/126049943-fa90ef38-dcbf-4a19-922d-507a4655369a.png)

**Comment by FrutyX** [comment]
This is how it looks like now, so ye, can confirm it is fixed .-).

![gca](https://user-images.githubusercontent.com/23278552/131230526-b0bc3620-38f4-4360-a33c-825fdb3360a9.PNG)

**Comment by FrutyX** [comment]
This is how it looks like now, so ye, fixed .-).

![gca](https://user-images.githubusercontent.com/23278552/131230588-6bfe76d2-f2c8-448e-b998-652fe4ff30d9.PNG)
