### ISSUE TITLE
Items images are missing

### ISSUE THREAD

**Issue by nghuytoan18** [DinoDevs/GladiatusCrazyAddon#275]
**Describe the bug**
why all the items have no pictures except the weapons

**Screenshots (optional)**
![1](https://user-images.githubusercontent.com/51833450/132461070-a6002b0b-b12b-4b1a-8749-408259c8363f.jpg)
![2](https://user-images.githubusercontent.com/51833450/132461097-94ca555d-0a87-4782-880c-3889a73e0ebd.jpg)
![3](https://user-images.githubusercontent.com/51833450/132461112-34354a7e-88d8-4aaa-8e48-05acfea0e1a5.jpg)

**Browser info (optional)**
  - Browser  Chrome
 - Version 93.0.4577.63 (newest)

**Comment by FrutyX** [comment]
Any other extensions that could mess with the game? Like AdBlock/uBlock? I am not having this issue on any Chrome version.

**Comment by nghuytoan18** [comment]
> Any other extensions that could mess with the game? Like AdBlock/uBlock? I am not having this issue on any Chrome version. Weird indeed.

![s](https://user-images.githubusercontent.com/51833450/132495732-4e79ea56-957b-4adb-bcd3-bfc685e13036.jpg)

i have disabled both types of ads block and restarted but it's still the same?

**Comment by FrutyX** [comment]
Alright.

Check Chrome's console by pressing F12, then reload the page, and see if there are any errors (they are red), disable all Adblocks before doing so, because they are causing some errors in the console (blocking ads).

Any errors copy here.

**Comment by nghuytoan18** [comment]
> Alright.
> 
> Check Chrome's console by pressing F12, then reload the page, and see if there are any errors (they are red), disable all Adblocks before doing so, because they are causing some errors in the console (blocking ads).
> 
> Any errors copy here.

there are 3

index.php:1 Unchecked runtime.lastError: The message port closed before a response was received.

jquery.js:3 GET https://s2-en.gladiatus.gameforge.com/game/ajax.php?mod=inventory&submod=setInv&inv=2&sh=8ac62baf752f9f250f7d8c72a7dc7e63 net::ERR_CONNECTION_TIMED_OUT

jquery.js:3 GET https://s2-en.gladiatus.gameforge.com/game/ajax.php?mod=inventory&submod=setInv&inv=1&sh=8ac62baf752f9f250f7d8c72a7dc7e63 net::ERR_CONNECTION_TIMED_OUT

**Comment by FrutyX** [comment]
Gram (dev) mentioned, that we shouldn't post public full url links (for account safety, I guess), so edit your post and remove everything that is behind "sh=" , the rest you can leave.

I am not seeing anything that has to do with your problem, except, I am not a GCA dev, let's wait for him/them, maybe he'll know more.

I've never seen the "unchecked runtime" error, but I have seen the other two, they are usually popping up when Gladiatus servers are not responding, which keeps happening over the last half of year.

I can only suggest that you play with your GCA settings, try disable/enable stuff that has to do with items, you can also always import/export and reset all your GCA settings, and see if something changes, you can also delete all data&cookies for Gladiatus in Chrome, just to make sure if nothing is messy.

**Comment by FrutyX** [comment]
@GramThanos 

![unnamed](https://user-images.githubusercontent.com/23278552/132517585-b562aeff-1a98-455c-95d2-7a031f2dbe67.jpg)
(:DDDDDDDDD)

**Comment by nghuytoan18** [comment]
> Gram (dev) mentioned, that we shouldn't post public full url links (for account safety, I guess), so edit your post and remove everything that is behind "sh=" , the rest you can leave.
> 
> I am not seeing anything that has to do with your problem, except, I am not a GCA dev, let's wait for him/them, maybe he'll know more.
> 
> I've never seen the "unchecked runtime" error, but I have seen the other two, they are usually popping up when Gladiatus servers are not responding, which keeps happening over the last half of year.
> 
> I can only suggest that you play with your GCA settings, try disable/enable stuff that has to do with items, you can also always import/export and reset all your GCA settings, and see if something changes, you can also delete all data&cookies for Gladiatus in Chrome, just to make sure that nothing is messy.

i am not sure if i should delete all data & cookies because i did it once and everything is exactly as it is now.
anyway thanks for your detailed answer. maybe after a few days it will be back to normal?

**Comment by GramThanos** [comment]
> > Alright.
> > 
> > Check Chrome's console by pressing F12, then reload the page, and see if there are any errors (they are red), disable all Adblocks before doing so, because they are causing some errors in the console (blocking ads).
> > 
> > Any errors copy here.
> 
> there are 3
> 
> index.php:1 Unchecked runtime.lastError: The message port closed before a response was received.
> 
> jquery.js:3 GET https://s2-en.gladiatus.gameforge.com/game/ajax.php?mod=inventory&submod=setInv&inv=2&sh= net::ERR_CONNECTION_TIMED_OUT
> 
> jquery.js:3 GET https://s2-en.gladiatus.gameforge.com/game/ajax.php?mod=inventory&submod=setInv&inv=1&sh= net::ERR_CONNECTION_TIMED_OUT

These are all network related problems. Its like when you phone, no one answers and after a few beeps the line drops.

**Comment by nghuytoan18** [comment]
No need to worry anymore. maybe this problem is related to cookies but deleting it is not enough, so i reinstalled chrome and logged in and everything is back to normal :)

**Comment by nghuytoan18** [comment]
> > > Alright.
> > > Check Chrome's console by pressing F12, then reload the page, and see if there are any errors (they are red), disable all Adblocks before doing so, because they are causing some errors in the console (blocking ads).
> > > Any errors copy here.
> > 
> > 
> > there are 3
> > index.php:1 Unchecked runtime.lastError: The message port closed before a response was received.
> > jquery.js:3 GET https://s2-en.gladiatus.gameforge.com/game/ajax.php?mod=inventory&submod=setInv&inv=2&sh= net::ERR_CONNECTION_TIMED_OUT
> > jquery.js:3 GET https://s2-en.gladiatus.gameforge.com/game/ajax.php?mod=inventory&submod=setInv&inv=1&sh= net::ERR_CONNECTION_TIMED_OUT
> 
> These are all network related problems. Its like when you phone, no one answers and after a few beeps the line drops.

I removed and reinstalled chrome, logged back in and the image showed up. But after turning on 'Display item's forge materials on tooltips' it still doesn't seem to work when the name of the materials is missing?
![s](https://user-images.githubusercontent.com/51833450/132797241-a0d5b522-c7ab-4ccd-af82-482ee53a6df1.jpg)

**Comment by GramThanos** [comment]
Visit horreum (material storage) and check again.

**Comment by FrutyX** [comment]
@nghuytoan18 so, this was just an browser issue, wasn't it?

**Comment by nghuytoan18** [comment]
> @nghuytoan18 so, this was just an browser issue, wasn't it?

I think so, May be the problem comes from cookies and we should close this case as it has nothing to do with GCA.
