### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#276]
There are some missing translations that needs to be added completely.

I've mentioned this before, but a whole new Issue will be probably best.

On/Off buttons in settings are missing:

![trans](https://user-images.githubusercontent.com/23278552/132601708-3c4d139c-0148-45b9-b730-2ccddc30da51.PNG)

In auction&packages sorting - Threat is missing, the rest is translated:

![trans2](https://user-images.githubusercontent.com/23278552/132601743-78f68c8e-2ae5-47f6-9df7-d2cd83f401cd.PNG)

That's all... for now, muheheh.

**Comment by GramThanos** [comment]
Removed text from settings On/Off toggles
![image](https://user-images.githubusercontent.com/14858959/133327429-b6f0808e-0a29-4bf3-ae32-b2ee30f2b1d4.png)

**Comment by FrutyX** [comment]
Unexpected, looking good.

![the-universe-tim-and-eric-mind-blown](https://user-images.githubusercontent.com/23278552/133328472-d20b52c5-962c-41fc-b896-e96152e64482.gif)

**Comment by Zitronenen** [comment]
Look good, but isn't good for the GCA documentation.. U know =D

**Comment by GramThanos** [comment]
You are a part of this now :smile:. You shall vote for it.

**Comment by Zitronenen** [comment]
It's Okey. I will update the documentation. It looks really good.

**Comment by FrutyX** [comment]
Just need to add Thread to the translation list and we done here, this is a very nice change, it looks modern and the options are more recognizable, really nice.

**Comment by GramThanos** [comment]
These should autoload from the UI. Visit the your turma player and check again if the treat is translated.

**Comment by FrutyX** [comment]
After visiting Turma profile, it is indeed translated, noice, I am silent then, thanks for the upgrades!

Close whenever.

**Comment by FrutyX** [comment]
You know, if you ever wanted to make GCA fully translatable, this [picture], it's no big deal, but it cannot be translated. Also, if you added that, I suggest adding a line where you mention to write to you only in english.

![trans](https://user-images.githubusercontent.com/23278552/134103831-768bb972-5cf3-4f9a-b3e1-ce7e2bd28196.PNG)

**Comment by GramThanos** [comment]
Personally, I don't think we should translate that. We are already getting many Facebook messages in other languages.

**Comment by FrutyX** [comment]
Well, Facebook is Facebook, no surprise, but this seems like an developer preference, some on their projects have their "about" section translated while others not. It's your decision and I respect that.

**Comment by FrutyX** [comment]
Nothing else to do here, done and done, closing.

Re-open if needed.
