### ISSUE TITLE
Feature "Sound and Notification" 

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#278]
Hey Guys,
checked in the documentation back then, it seems like the sound system is not working.

What is the difference between "Enable Sound Notification" and "Enable Sound System"?
Disable feature "Enable Sound Notification" I still get the pips sound during the waiting time.

And the "Mute / Unmute sounds" feature is actually to be equated with "Enable Sound System"? = Double feature?

best wishes

**Comment by FrutyX** [comment]
Sneak peek.

![sneak](https://user-images.githubusercontent.com/23278552/146154569-220e53bc-f76f-4db8-840c-e9d3668ff3f5.PNG)

**Comment by GramThanos** [comment]
You are playing with the fire 🔥 🤣🤣

**Comment by FrutyX** [comment]
I thought that too, but after like 2-3 hours of broking it, I think it seems promising now :D

**Comment by GramThanos** [comment]
I think the original idea was to have 1 option to disable everything related to sound, but it was confusing and useless. I was thinking of adding the channels on the settings and add options to enable/disable each channel as well as change its sound.

**Comment by FrutyX** [comment]
Yeah, I got it when I was reading the codes.

Right now, I am just doing a big cleanup, fulfilling this request and doing what you wrote "I will have to simplify the sound system".

I just have to solve one error, do a safe check and I am ready to make an pull request, it works fine so far.

**Comment by FrutyX** [comment]
Not sure why this keeps popping up, time to time, I didn't touched it, but it does not affect anything, it's normally there.

I think we can (by that I mean you haha) fix this later.

![error](https://user-images.githubusercontent.com/23278552/146160647-93f00151-a853-43ce-b4fc-fb219bb1d716.PNG)

**Comment by GramThanos** [comment]
The addon has to load as fast as possible, but there is 1 problem, the page loads in phases, e.g.

first the browser gets the head part of the page then while it loads the body, it also loads the resources of the head in parallel. The addon injects itself as soon as possible to minimize visual lags and changes after load. Thus, when the addon loads, their is no document body in the page.

In other scripts like the global, you will see 2 events in our code, the preload and the load, where the load event ensures that the body content is loaded.

But the sound script (like other scripts such as the tools script) has to be loaded before the other scripts. Thus if you want to interact with the dom, you have to wait for it to load.

**Comment by GramThanos** [comment]
The only thing left here is wether we want to let the user pick the sound that they want for each action.
Available sounds:
```
'water'			: 'alert-sound-water.ogg',
'coin'			: 'coins.ogg',
'channel'		: 'communication-channel.ogg',
'voila'			: 'et-voila.ogg',
'in-the-way'	: 'gets-in-the-way.ogg',
'done'			: 'job-done.ogg',
'pizzicato'		: 'pizzicato.ogg',
'served'		: 'served.ogg',
'wet'			: 'wet.ogg'
```

Sound actions:
```
'audio-mute-toggle' : 'water',
'expedition-notification' : 'water',
'dungeon-notification' : 'water',
'arena-notification' : 'water',
'turma-notification' : 'water',
'auction-status-change-notification' : 'water'
```

**Comment by FrutyX** [comment]
I am hella confused now, I thought we got rid of it.

If you can add this, don't ask, but actually add it, finish it, and no more "unfinished feature" thing, I didn't cleaned it for no reason.

**Comment by GramThanos** [comment]
I didn't revert anything. I cleaned the code even more.
This is just a question, as sound files and related stuff were still inside the addon's code.

Will we keep the other sounds or not?
and
Should all notifications have the same sound?

Apart from that the problem was solved.

**Comment by FrutyX** [comment]
Well, I would just repeat myself.

if you can add it, don't ask, someone would probably appreciate these (both) options (having the possibility to change everything), if they were there, but like I said, don't leave it unfinished. You either do it, or you don't.

**Comment by GreatApo** [comment]
I thing something in the sound is bugged. I have seen this error twice already:

![image](https://user-images.githubusercontent.com/9620510/147656694-9e2033e0-5d51-422d-a39f-d86bb5deb7ba.png)

**Comment by FrutyX** [comment]
Hmm, never seen that, but google is full of it, probably just a browser thing, adding some attributes to the script should fix it, but I am not gonna dig in it, I mean I didn't even seen that, Gram was in charge, so he better check it out.

I

**Comment by GramThanos** [comment]
Nothing to worry about, this is a browser protection similar to the popup blocking protections.
The browser assumes that in order to play a sound, the user has to interact with the website first, thus, if you open your browser and instantly the addon try to notify you, the sound gets blocked.

I am not sure if there is a walkaround that.

**Comment by FrutyX** [comment]
I think it's time to close this., no problem here. More sound stuff is in #18.

**Comment by GramThanos** [comment]
Someone reported that he was not able to disable the sounds. Every time he disables them, they come back.

**Comment by FrutyX** [comment]
We could use some more info... I've been trying a few scenarios with the sounds and I never found any error nor problem.

**Comment by FrutyX** [comment]
If there will be no more info, I will close this.

I have the sound system enabled nonstop, sometimes I use it, sometimes I keep it muted, I did no get any bug or errors related to the sound system, and I did not seen anyone else complaining.

**Comment by FrutyX** [comment]
Alright then...

Closing for moderation reasons, we can always re-open or someone can always just open a new bug issue.
