### ISSUE TITLE
Avoid or point out feature dependencies

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#279]
- The feature "Display Life Potion Use Icon" need to activated "Display extended HP and XP Header Info".
- The feature "Enable cooldowns sounds notifications (expedition, dungeon, arena)" need to activated "Enable sound system

Can this check another dude?

Solution: Automatic activation of the required feature or no activation allowed with a note?

**Comment by FrutyX** [comment]
I can offer a different solution, a cheap one, yes, but rather than scripting it, we can just do this, I mean, it's clean and simple.

![Výstřižek](https://user-images.githubusercontent.com/23278552/146186526-7848899c-7a32-478c-a7d7-bcaefecc8409.PNG)

Unless Gram wants to script it, connect these two buttons and enable/disable the other button when the main one is changed too.

The other feature is already mentioned in #278.

**Comment by FrutyX** [comment]
Okay, this was probably a crappy idea, this needs to be moved and reworked so it is not dependant:

![pot](https://user-images.githubusercontent.com/23278552/146649257-ef020c81-5281-4212-9531-591d45805fc0.PNG)

**Comment by GramThanos** [comment]
The best solution would be to somehow show the features as disabled when their dependencies are off.
I don't like asterisks and such notes. Also, features that can be adapted to work without dependencies should work, e.g. the potion icon may could be implemented on the other layout too.

**Comment by FrutyX** [comment]
> The best solution would be to somehow show the features as disabled when their dependencies are off. 

That's isn't hard to do in js, in this case, it is, I mean the buttons does not even have an ID, so you can't connect them just like that, there are probably more options, but this is above my skill level.

> e.g. the potion icon may could be implemented on the other layout too.

This is honestly the best solution.
Basically both these things I mentioned already above, but if and how you manage to do it is up to you, I'd rather not stick my nose in it, I tried, it's fire 🔥 .

**Comment by GreatApo** [comment]
> The best solution would be to somehow show the features as disabled when their dependencies are off. I don't like asterisks and such notes. Also, features that can be adapted to work without dependencies should work, e.g. the potion icon may could be implemented on the other layout too.

You are right. Styling can be done easily, for example:
```margin-left:20px;
filter: grayscale(100%);```
![image](https://user-images.githubusercontent.com/9620510/146692179-96a5fc05-e1c9-477b-bb86-2360d790cbe8.png)
but JS probably needs a lot of work.

Lets try to make the features work without dependencies, but I am sure there are settings than need to be linked.

**Comment by FrutyX** [comment]
*SLAP* PATCHED.

Nice Gram, nice.
