### ISSUE TITLE
[Gladiatus Update 2.10.0] After update bugs

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#28]
**Version 4.0.0 bugs**
 - Training visual bug [fixed da4a64faa40e2c4f931cfdf5817e05a961cd9413]
 - Reports items bugs [fixed]
    - No item shadow [fixed 73d09e790757301424d3d5ec53fc146af72419ff]
    - Reports list interface console error [fixed fbcedaaa9a5a8815137c6e0777c30d3a3d8517bf]
    - Error on getting loots [fixed fbcedaaa9a5a8815137c6e0777c30d3a3d8517bf]
 - Auction not shadow on items [fixed a606df6d860d5980688c925c8283ddda36afdc69]

**Version 3.x.x bugs**
 - Auction no items images [fixed f7d5bf97d0abca999b986a86d3bc698c67536158]
 - Reports errors (same as v4) [fixed 9baa4c0a3fc85d735e41daa77d44a5325df698ef]

Report more bugs under.

**Comment by DarkSide666** [comment]
Please please please fix auction. This is nightmare to live without it :)

**Comment by GramThanos** [comment]
Please only bugs here, wishes/requests on facebook :P

**Comment by GramThanos** [comment]
No more bugs were reported.
