### ISSUE TITLE
Expansion of buildings little flaw

### ISSUE THREAD

**Issue by Zitronenen** [DinoDevs/GladiatusCrazyAddon#280]
Hey Guys, 
A small blemish, can you add extra space?
![Screenshot_20210921_011710](https://user-images.githubusercontent.com/8767665/134089131-59fe29e1-6870-471f-bede-862ce25de83b.jpg)

**Comment by FrutyX** [comment]
Yea, I've noticed this too some time ago...

**Comment by FrutyX** [comment]
Fixed some time ago and seems okay, plus it's already on the list, so closing.

Re-open if needed.
