### ISSUE TITLE
White number indicators affecting resources too 

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#282]
Google Chrome v95.0.4638.54
GCA 4.3.5 Beta

Heya,

so normally this is how it should look like, right?

![surovinykvality](https://user-images.githubusercontent.com/23278552/138916774-46330921-7e64-4996-b5ad-f881985ac4b4.PNG)

The problem is, that when you enable this:
![bug](https://user-images.githubusercontent.com/23278552/138916819-e966e0ff-785e-49d4-8010-2b9ffeff6218.PNG)

.... it also affects the resources "bullet" color symbol, making it look like this:

![gca999](https://user-images.githubusercontent.com/23278552/138916986-f11ee681-87f9-4e2a-87b2-5c7902117b57.PNG)

It's just a detail I've noticed now, I can Imagine it can problematic to fix, since this setting affects all/most of the items, but still, it's a bug.

**Comment by FrutyX** [comment]
Hmmm, is this a bug? Some small icons are colored too (orange), check it out:

![bug](https://user-images.githubusercontent.com/23278552/142083119-4b7d38c2-da8a-4c87-923f-a6dc6aae5613.PNG)

**Comment by GreatApo** [comment]
> Hmmm, is this a bug? Some small icons are colored too (orange), check it out:
> 
> ![bug](https://user-images.githubusercontent.com/23278552/142083119-4b7d38c2-da8a-4c87-923f-a6dc6aae5613.PNG)

That is weird I have never seen it...

**Comment by FrutyX** [comment]
![bug2](https://user-images.githubusercontent.com/23278552/142093217-1f94a613-04af-4b6d-93c3-dc5e4064ad25.PNG)

**Comment by FrutyX** [comment]
I've reverted this fix (https://github.com/DinoDevs/GladiatusCrazyAddon/commit/6d6650a2762cbbb91b7737f52257746475e0d4d5), because I thought it caused it and I just didn't noticed, but I am wrong, it's not what is causing it. The small icons are getting colored for some reason, no clue why.

Currently running Google Chrome 96.0.4664.45, hopefully they didn't "improved" it again.

**Comment by GramThanos** [comment]
Yeah, it was a browser behavior change. The font-weight was enabling color on the symbols.

**Comment by FrutyX** [comment]
Awesome, thanks for the fix!

**Comment by FrutyX** [comment]
On the list with #294.

Another good fix, closing, re-open if needed.
