### ISSUE TITLE
Gold&XP Statistics reset button

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#284]
Heya, 
this is a feature request.

I think users should be able to reset their statistics whenever they like and without having the knowledge to do it with browser dev tools. Simply add an button to clean the data only for the statistics.

Example:
![Výstřižek](https://user-images.githubusercontent.com/23278552/139770518-fed88f41-6008-477e-9e3a-3b42103c2b89.PNG)

Thank you :-).

EDIT:

To prevent people asking why it does not work, i suggest adding a small text note to explain how the collecting actually works, example:

![Výstřižek](https://user-images.githubusercontent.com/23278552/139771407-b9f57201-7577-4635-a960-ce542a0c59ab.PNG)

**Comment by GreatApo** [comment]
> Upgrade 2.0:
> 
> ![139771407-b9f57201-7577-4635-a960-ce542a0c59ab](https://user-images.githubusercontent.com/23278552/139915426-b1bfe38c-2f54-4ba3-8c92-fe67e0ae2c5a.png)
> 
> Gram&Apo be like: "Oh no, he just won't stop spamming us with his crap."
> 
> ![PepeLaugh](https://user-images.githubusercontent.com/23278552/139915990-5d2b83d4-c026-4f0e-a5aa-221d8fb95392.png)

ffs... It probably makes more sense to teach you how to code :P

**Comment by FrutyX** [comment]
Maaaaaaayyyyyybeee, but I doubt an amateur can beat an structural engineer ,-), also maybe I'll teach myself javascript one day (no promises), but I am hella lazy for that :D, on the other hand, I know other things.

**Comment by FrutyX** [comment]
So you have assigned yourself? Hmmm, here is a little hint:

![apo](https://user-images.githubusercontent.com/23278552/139958326-2b4fc2e7-58bc-4e01-b59e-356d0dc94bfb.PNG)

:DDDD

I mean, adding the button isn't a big deal, making the function probably is, well not for you.
I was playing, just a little, I love the comments there with links to stackoverflow, long live stackoverflow :D.

**Comment by GreatApo** [comment]
> So you have assigned yourself? Hmmm, here is a little hint:
> 
> ![apo](https://user-images.githubusercontent.com/23278552/139958326-2b4fc2e7-58bc-4e01-b59e-356d0dc94bfb.PNG)
> 
> :DDDD
> 
> I mean, adding the button isn't a big deal, making the function probably is, well not for you. I was playing, just a little, I love the comments there with links to stackoverflow, long live stackoverflow :D.

Nice! Just do in there:
```gca_data.section.set('data', 'gold_exp_data', []);
gca_notifications.success("Stats have been reset!");```

**Comment by FrutyX** [comment]
Well, that was easy, well you know your thing (and most importantly your addon codes).

Are you gonna add it or should I make an pull request? It really doesn't matter to me, but don't use simple text for notifications (like Gram :P) , because someone like me will come, that it cannot be translated, always add (get) locales for it.

Thanks ❤️

**Comment by GreatApo** [comment]
> Well, that was easy, well you know your thing (and most importantly your addon codes).
> 
> Are you gonna add it or should I make an pull request? It really doesn't matter to me, but don't use simple text for notifications (like Gram :P) , because someone like me will come, that it cannot be translated, always add (get) locales for it.
> 
> Thanks ❤️

Hahaha, you worked that out :P I didn't want to confuse you with the translation part ^_^ but it seems you learn pretty fast! If you can make a pull request, go ahead.

**Comment by FrutyX** [comment]
Alright, gimme a sec, need to do it properly.

**Comment by FrutyX** [comment]
Thanks for implementing it! Oh wait... nah, no really, thanks for the help, boys! ❤️ 

According to my testing.... "it just works!" :D ...

**Comment by FrutyX** [comment]
Btw, the length is intentional? Also consider #288, cuz I did not seen any reaction on it anywhere.

![thick](https://user-images.githubusercontent.com/23278552/140436671-0ab409d6-65ff-4791-ac6d-8b3d04c732a9.PNG)


Think my OCD for unfinished things is kicking in again :/.

**Comment by GreatApo** [comment]
> Btw, the length is intentional? Also consider #288, cuz I did not seen any reaction on it anywhere.
> 
> ![thick](https://user-images.githubusercontent.com/23278552/140436671-0ab409d6-65ff-4791-ac6d-8b3d04c732a9.PNG)
> 
> Think my OCD for unfinished things is kicking in again :/.

Yes it is intentional. By default, Gladiatus has 2-3 different button widths. These are 2 of them.

**Comment by FrutyX** [comment]
@GreatApo I think this one is not on the progress list, but #248 (fixing the statistics) isn't either.

**Comment by GreatApo** [comment]
> @GreatApo I think this one is not on the progress list, but #248 (fixing the statistics) isn't either.

Done boss,  commit cc870038b3bb653b7183bf7289d117bf8def1fc7

**Comment by FrutyX** [comment]
After few days of daily testing, it works as expected without any problems!

**Comment by FrutyX** [comment]
This one is good and logged, closing.

Re-open if needed.
