### ISSUE TITLE
Warehouse value 

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#290]
Re-purposed this issue (was something bit different before, don't ask, I am just an idiot).

This is an enhancement (I believe), would it be possible to enable this feature for warehouse too? I don't see any disadvantages, so why not. Personally I was looking for it.

![gca](https://user-images.githubusercontent.com/23278552/140437450-32eb7fe4-2d66-4502-9658-ea3b0ebb2755.PNG)

Shouldn't be too hard for you to do, just some little edits in merchants.js.

**Comment by FrutyX** [comment]
Re-purposed.

**Comment by FrutyX** [comment]
It's weird that **if(!document.getElementById("shop")) return;** and warehouse has "shop" too, unless, you disabled it in warehouse on purpose.

Or we talking about a bug, I don't know.

**Comment by FrutyX** [comment]
Hmmm, I've been giving ideas and "instructions", but it is only fair to say why.

Well, recently I've started to save the most valuable scrolls into my warehouse, and I would like to know, how much gold I have there saved, I don't know if anyone else needs this, but then we go again, why not if it's already scripted.

**Comment by GreatApo** [comment]
We are not presented the value sum in guild store because that may push guild members (especially low level players) to just empty the storage and sell the content.
I can see that it could be helpful for hiding gold (maybe for guild upgrades too), so it could be codes but disabled by default.

**Comment by FrutyX** [comment]
> to just empty the storage and sell the content. 

I am not saying that it's not true, but fortunately Gladiatus has a rank system with their own permissions, and you can set that for each shelf. A new player shouldn't have a rank with full permissions to the warehouse, if yes, then it's not GCAs fault, it's on the guild master and the administrators.

I was actually the warehouse master in my guild, and each rank had their permission to each specific shelf.
It's more work, but you could, if you wanted, to add this option to settings and leave it at least disabled by default.

**Comment by GreatApo** [comment]
> > to just empty the storage and sell the content.
> 
> I am not saying that it's not true, but fortunately Gladiatus has a rank system with their own permissions, and you can set that for each shelf. A new player shouldn't have a rank with full permissions to the warehouse, if yes, then it's not GCAs fault, it's on the guild master and the administrators.
> 
> I was actually the warehouse master in my guild, and each rank had their permission to each specific shelf. It's more work, but you could, if you wanted, to add this option to settings and leave it at least disabled by default.

Yeah I agree. I just explained why it is not already there :)

**Comment by GreatApo** [comment]
Commit #4c320758156ce2242ec0a1cfd56907780aa1d3eb

**Comment by FrutyX** [comment]
And once again you fulfill my request, and once again, I thank you for that.

This will prove useful.

**Comment by FrutyX** [comment]
On the list with #294.

Added, looking good, closing, re-open if needed.
