### ISSUE TITLE
Food auction - quick access

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#291]
To explain why:

Speedservers are fast, and the bigger level you are, the more tougher enemies you get, and I am getting into that point, where I use a lot of food.

Now, this is starting to get more and more annoying, because I often have to buy food from auctions, and well, I have always set my auctions to amulets, so there goes the process of switching to food, turning off the coin (saving gold option), and getting the food, now I have to go back to amulets and switch the coin back on.

I don't want from you to automate this process, I want a quick access to the food list, the best option would probably be to use the quick menu (I can make a icon for you later, if you agree to do this) to navigate there, if possible (not sure about that one), loading the page without remembering it (so next time I go to auctions it will still be saved as amulets).

I was trying once to do this by myself, but I don't know how to navigate thru Gladiatus without unique "sh=", on the other hand, you can, because you know how to properly modify the URL parameters.

This would improve my overall experience with Gladiatus, honestly.
Thank you in advance.

**Comment by FrutyX** [comment]
@GramThanos with https://github.com/DinoDevs/GladiatusCrazyAddon/commit/6f576c69cf63bc53fb48bdb02bf8fe9fe293400c you broke it and it cannot be disabled/enabled in settings.

It has to be in the same order as :

`"values" : 'msg|gmd|gmr|gst|gbn|gwr|gar|gjl|glb|gtm|sim|stt|onl|fau'`

otherwise it will break.

**Comment by GramThanos** [comment]
Haha. I should not make changes before sleep. I will fix it tomorrow.

**Comment by FrutyX** [comment]
I did the same mistake, exactly :).

**Comment by SleepingShadow-bit** [comment]
Just saw that the general market also has shortcuts.  Couldn't this also be set / displayed at the auction house?  Or is the problem here which icons should be shown there

![IMG_20220627_232409](https://user-images.githubusercontent.com/8767665/176038605-009475ac-dc0e-47a1-b283-77075980f495.jpg)
