### ISSUE TITLE
Merchants search filter colors

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#292]
An option to filter by color can be added on merchant search.

(feedback from Emre on Facebook)

**Comment by mattemre** [comment]
I mean exactly; Instead of looking at all merchants, let it say this merchant has a purple item

**Comment by mattemre** [comment]
![image](https://user-images.githubusercontent.com/95325400/144236046-d590c525-51b9-4367-a3f2-b5d926b99729.png)
maybe it helps

**Comment by mattemre** [comment]
![image](https://user-images.githubusercontent.com/95325400/144326579-372b3c81-4868-4a9a-b3ca-f854ad324162.png)

maybe this helps. I really need this

**Comment by mattemre** [comment]
Will there be any development on this issue?

**Comment by GramThanos** [comment]
Yes, but this is not a high priority.

**Comment by FrutyX** [comment]
This is an perfect solution #81 , as this does not create automatic server load, it must be triggered by the user.

**Comment by FrutyX** [comment]
@GramThanos impressive piece of work, looking good!

**Comment by mattemre** [comment]
This should be given priority. Because these are the codes we need the most in these events.

**Comment by FrutyX** [comment]
It's already done and working, but 4.3.5 has still some flaws that needs to be polished.

**Comment by mattemre** [comment]
Thank you very much. have a good works

**Comment by Zitronenen** [comment]
Great Feature.
i think the hover effect ist misleading?!
![Hovereffect](https://user-images.githubusercontent.com/8767665/146076975-1330d867-554f-4c67-b211-033e4a74b511.gif)

**Comment by GreatApo** [comment]
> Great Feature. i think the hover effect ist misleading?! ![Hovereffect](https://user-images.githubusercontent.com/8767665/146076975-1330d867-554f-4c67-b211-033e4a74b511.gif)

This can not be fixed unless we make a custom drop down menu (li + js)

**Comment by FrutyX** [comment]
I've tried to play with this for a while, but Apo is right, it's needs to be custom made, but a custom drop down menu could be used also for other features, well, like Apo said.

Or you can change it completely, to be honest, I like the way it is, but you could change (select/options) to selectable buttons, or something else that would work with it.

I mean, in the end, it's a detail I didn't even noticed, so I don't know, depends on your mood I guess, lel.

**Comment by GreatApo** [comment]
@GramThanos if you want to have a look, no hacky way works to disable the browser blue render on selectors and even if one works, it will not be cross browser. I also had a look on jQuery 1.11 (the version that Gladiatus has) and we can use selectmenu() but needs styling (and probably a tweak in JS)...
```jQuery("#gca-search-input-color").selectmenu({transferClasses: true});```

This is a low priority.

**Comment by FrutyX** [comment]
The way Thanos made this (coloring a symbol) seems to be problematic and will eventually need a rework.

My Chrome just updated to v97 and I believe this is the result:

![colors](https://user-images.githubusercontent.com/23278552/148462098-dfcae51b-07e7-4bdf-9e6e-c29bef628e90.PNG)
![select](https://user-images.githubusercontent.com/23278552/148462314-0578072e-f5b3-4e2e-95ba-b32959b20a07.PNG)

I do agree that these browser behaviour changes are annoying (this isn't the first time).

**Comment by GramThanos** [comment]
💩

**Comment by FrutyX** [comment]
Unfortunately, that doesn't work :-/ Symbols are a no-go.

![poop](https://user-images.githubusercontent.com/23278552/148465003-c57b7667-d11f-4a9b-bdf1-b308ab96b15f.PNG)

**Comment by FrutyX** [comment]
@GreatApo nice, you even solved the blue hover problem, because it no longer colors the symbol to white when hovering, and you didn't even need to use custom js and css... :D

**Comment by FrutyX** [comment]
Alright, so I think it's time to close this one, everything has been done.

The problem when the hovering was affecting the symbol colors seems to be fixed (I've checked on 4 browsers).
