### ISSUE TITLE
Auction - stacked images, no yellow color on gold saving items and mess with side menu

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#30]
Bugs after version 3.2.9

 - Auction images are a bit messed up. Small items images don't cover big ones.
 - There is no yellow background for gold saving items.
 - There still is old time bug with left side menu in auction if I set .

![screenshot](https://user-images.githubusercontent.com/1969119/28333950-38b781fa-6c02-11e7-8e56-cb1bdf12accc.png)

**Comment by GramThanos** [comment]
Ok, but as v4 is almost complete, we may don't fix them if we release version 4.

**Comment by GramThanos** [comment]
Fixed
Commit 869f6b297ad12f19e388716da1c494bf5ef40f51
