### ISSUE TITLE
Double-click problems in guild storage

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#300]
When merchant shop area is smaller (when storage shelf is small, half shop area) double click thinks the area is the full shop size.

**Comment by FrutyX** [comment]
I wonder how do you even reproduce this (or found out), I have a half-sized shelf in my storage and since there is nothing, it does not recognize it as "clickable".

Like, I don't see a problem nor error, not saying it should not be addressed, but still, kinda clueless about this.

**Comment by GramThanos** [comment]
If you fill the first 2 columns of the half shelf shop, then try to double click an item on your inventory. The algorithm will try to move it outside the shop area.

**Comment by FrutyX** [comment]
Ooooohhhhh, I see it now, well, thanks for the explanation.
