### ISSUE TITLE
Show Unknown Enemy Drops

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#303]
We don't have data on what resources some monsters drop, but data are gathered (locally) by the addon (saved at: data -> enemy drops). When enough data are gathered, the addon can identify and show the drops of each enemy.

**Comment by GreatApo** [comment]
If you have collected more than 50 resources drop samples of an enemy that we don't have data on, the drops will be visible on the enemy.
![Screenshot (63)](https://user-images.githubusercontent.com/9620510/147296098-80b5101c-b4f2-4a59-a6ae-33c4ca3f2b2b.png)

**Comment by FrutyX** [comment]
That's actually pretty impressive.

**Comment by FrutyX** [comment]
Is this allowed in underworld too? I would really like to see it there too.

**Comment by GreatApo** [comment]
> Is this allowed in underworld too? I would really like to see it there too.

I think it is, I will double check

**Comment by FrutyX** [comment]
> Edit: No underworld implementation yet

![star-wars-darth-vader](https://user-images.githubusercontent.com/23278552/147393826-6b4af5a7-1a2d-4394-92b0-b27dc7221c2f.gif)

**Comment by FrutyX** [comment]
Hmmm, why I don't see the resources anymore with the newest commit? Did it reset or something?

**Comment by GramThanos** [comment]
I propably broke something :P

**Comment by FrutyX** [comment]
Oh, Apo is gonna love you for that.

**Comment by GramThanos** [comment]
Apo got too familiar with Python and now he forgets to add semicolons (;)

**Comment by FrutyX** [comment]
Yes, resources are back.

**Comment by FrutyX** [comment]
I don't know what's wrong with this, yesterday I have cleaned all my cookies and data, and since then, resources are not visible anymore, it could be also the new Chrome update, I am not 100% sure when this happened. 

There is no console error.

Or maybe I need more data (over 70 expeditions now)?

**Comment by FrutyX** [comment]
Aaaaaaaand they reappeared again, somewhen, at some point, interesting.

Maybe it was also caused because the resources changed to different ones, I don't know, I'll remove the bug label because it's probably not bugged.

**Comment by GramThanos** [comment]
> Aaaaaaaand they reappeared again, somewhen, at some point, interesting.
> 
> Maybe it was also caused because the resources changed to different ones, I don't know, I'll remove the bug label because it's probably not bugged.

I think it needs to collect 50 samples first.

**Comment by FrutyX** [comment]
Yeah right, thanks for alerting me, I am just blind once again.

![apo](https://user-images.githubusercontent.com/23278552/149040619-c79e88fd-0416-41b8-90bb-443ef7f2feb4.PNG)

**Comment by GreatApo** [comment]
This is about enemies that we haven't hardcoded their drops. You need at least 50 resources and the chance percentage to be above a threshold. We also need to ask in the forum for people to submit their findings if they have more than like 200-500 data. And we need to make it work in underworld too
