### ISSUE TITLE
missing_translations

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#304]
**Turkish**
 - Language: (Turkish-Türkçe)

**[trv2.txt](https://github.com/DinoDevs/GladiatusCrazyAddon/files/7741976/trv2.txt)**

**Comment by FrutyX** [comment]
Translation added, noted you as mattemre, if you wish to use a different name (in the translators names), an in-game one for example, I can edit it.

@GramThanos you might want to check it out I did it right -  80f03ca

**Comment by mattemre** [comment]
I think it would be good to change my name. but I got help from someone in this translation. I would appreciate it if you could write his name on it.  "Elderly (s48)" and "Rubick (s48)"

**Comment by FrutyX** [comment]
Names added, I think we are done here, closing.
