### ISSUE TITLE
Smelter timers all in one place

### ISSUE THREAD

**Issue by MiguelSOliveira** [DinoDevs/GladiatusCrazyAddon#310]
Would it be a usefull feature if we could see all timers for all tabs in smelter (maybe below the page), instead of clicking on each tab?

<img width="345" alt="imagem" src="https://user-images.githubusercontent.com/8149533/147418028-90c1596a-af64-459d-9fd6-59f42612d9af.png">

**Comment by FrutyX** [comment]
Do you have enabled "Show forge/smelt timer indicator" in the settings?

![smelt](https://user-images.githubusercontent.com/23278552/147419267-c5f2b711-0dc0-4c09-94dd-2eed1c5ec922.PNG)

**Comment by MiguelSOliveira** [comment]
Hey FrutyX, thanks for the response, but I can't find that setting?

**Comment by FrutyX** [comment]
In global, the first page.

![settings](https://user-images.githubusercontent.com/23278552/147419387-70d0339c-e8f7-4e83-abfb-b45a959fcc70.PNG)

**Comment by MiguelSOliveira** [comment]
ah I do have it enabled. the tooltip is triggered by hovering in the small red square. Didn't know that, thanks Fruty. 

Nevermind the request then, it's already implemented!
