### ISSUE TITLE
Victories - Honorary Title / No count? 

### ISSUE THREAD

**Issue by Zitronenen** [DinoDevs/GladiatusCrazyAddon#312]
See screen.
But "The Rite of CasVa" not available anymore via event.

![IMG_20211228_130135](https://user-images.githubusercontent.com/8767665/147564601-eba6664a-25cf-49bb-87ba-8eb63941b6cf.jpg)

**Comment by FrutyX** [comment]
Okay and?

This isn't a GCA feature, this is from Gladiatus.

**Comment by Zitronenen** [comment]
Oh really.  My mistake. I close
