### ISSUE TITLE
Show the divine chest in battle reports

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#313]
Show the "Chest of Divine Fate" in battle reports list, the same way as item drops are listed:

![vyprav](https://user-images.githubusercontent.com/23278552/147607953-6ab4fff8-56f7-4aa2-af04-d91fb9eba271.PNG)
![enemy](https://user-images.githubusercontent.com/23278552/147608101-0bde0132-a731-4e66-97c7-9f825f02fb7b.PNG)
![chest](https://user-images.githubusercontent.com/23278552/147607941-a571e9fb-f1e2-4c21-ae38-5882a33d7f5a.PNG)

The best way (probably) to approach this would be, to save the report id (when it drops) and write it after in the reports list, so GCA doesn't have to check every single report, which would create server load.

**The reason:**

Sometimes, I forget if I farmed the chest that day, so I have to check every single report to see if I got it.

**Comment by GreatApo** [comment]
Not finished yet:
- There is a bug in cache (change page, go back, sometimes the reward is not shown)
- I need to double check if chests are given from both arenas (to reduce requests)

**Comment by FrutyX** [comment]
> * I need to double check if chests are given from both arenas (to reduce requests)

It does drop in both arenas.

**Comment by FrutyX** [comment]
>  (to reduce requests)


Maybe you could flag only successful attacks, because the chest does not drop when you lose a fight.

**Comment by GreatApo** [comment]
> Maybe you could flag only successful attacks, because the chest does not drop when you lose a fight.

Good idea

**Comment by Zitronenen** [comment]
Today i make a Video about the feature.
I had to load the page 2x to make it visible - is it correct?

https://user-images.githubusercontent.com/8767665/147796138-62d50897-6a7f-4f85-9dd7-8bf8477297eb.mp4

**Comment by FrutyX** [comment]
Indeed, noticed it too, but I was waiting for another shot to test it, it does not appear immediately, you have to revisit the reports page.

**Comment by GreatApo** [comment]
I have seen that too (I also reported that at the top) but I can't find why it happens... Maybe @GramThanos can do a quality check...

**Comment by GreatApo** [comment]
Found the problem, I messed the asynchronous requests...

**Comment by FrutyX** [comment]
We good on this feature, no problem found.

**Comment by SleepingShadow-bit** [comment]
> We good on this feature, no problem found.

Yes. Same here. No Problems

**Comment by FrutyX** [comment]
@GreatApo for some reason, the problem is back, after you get your chest and check your reports, it is not visible, you have to refresh the page the reports page to see it.

**Comment by FrutyX** [comment]
Yep, so I am unable to confirm or deny it, I have probably seen once or twice a case, where it does not get loaded (only after a refresh), but now, a few days, it's been showing normally.
