### ISSUE TITLE
Online Friends - dont show family

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#314]
Hello guys, can u check the list about online friends?
My list dont show my family friends
![Enable_Select_Friend_YY](https://user-images.githubusercontent.com/8767665/147680698-97fb9b02-69c2-42e3-974a-997c96f9332f.png)

**Comment by FrutyX** [comment]
What version of GCA are you using?
What browser are you using?
Are there any errors in the console (press F12, errors are red, disable uBlock/AdBlock before doing so).

Sadly I cannot check this (I don't have any friends :( :D ).

**Comment by Zitronenen** [comment]
Current Github Version 4.3.5
Version 96.0.4664.110 (Offizieller Build) (64-Bit)
F12 = no Errors. No AdBlock using!

My guildmates have the same problem

:D :D

**Comment by FrutyX** [comment]
But your guildmates are not using the Github version, right? So it's also in 4.3.4, well maybe it never worked (did it?), I am not even sure.

**Comment by Zitronenen** [comment]
My guild mate use the official 4.3.4 with opera gx browser.

**Comment by FrutyX** [comment]
Yeah, I'll leave it to Gram & Apo, since they can test it on each other and I don't have to create another acc.

**Comment by GramThanos** [comment]
Hey! Can you send me a screenshot of your fiends list and also maybe a screen shot of the console (open online players modal, right click the page and select inspect element, then select the console tab on the new panel). If you don't want to post it here, send me an email at gramthanos@gmail.com

**Comment by FrutyX** [comment]
Maybe it works, but some symbols in player names are stopping it... or diacritics.

**Comment by Zitronenen** [comment]
@GramThanos i send you a email

**Comment by FrutyX** [comment]
> Maybe it works, but some symbols in player names are stopping it... or diacritics.

Tested this, not the case.

**Comment by SleepingShadow-bit** [comment]
> 

Could you test the friends list?
And do u have some errors? Maybe I can't handle the error console =)

**Comment by FrutyX** [comment]
I did, there is no error, no problem visible, but the list is not loading, either a small change is needed, or the script needs to be completely reworked, but the guild list does work.

**Comment by GramThanos** [comment]
I have done some testing and changes based on @SleepingShadow-bit 's feedback (he gave me more info through email), but I havent pushed them because of the new version. One problem is that the addon fails to detect friends that are not in a guild.

@SleepingShadow-bit can you also send me through email your friends table in html?
To do that follow the steps:
 - go to the friends page
 - right click and select view source
 - use ctrl+f to serach for `<section>`
 - copy from the `<section>` up to the `</section>` 
 - replace any `sh=abcd...` with `sh=xxxxxx..`
 
 Here is an example of my table:
 ```
<section>
	<table border="0" cellpadding="2" cellspacing="2" style="width:100%;">
		<tr>
			<th style="max-width:100px;overflow:hidden;">Όνομα</th>
			<th>Τάγμα</th>
			<th>Επίπεδο</th>
			<th>Κατάσταση</th>
			<th>&nbsp;</th>
		</tr>

								<tr>
				<td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=119682&sh=XXXXXXXXX" title="GreatApo">GreatApo</a></td>
				<td><a href="index.php?mod=guild&i=19676&sh=XXXXXXXXX" >[ENOMENOI]</a></td>
				<td>144</td>
				<td><span style="color: red; font-weight: bold;" title="off">12:58:52</span></td>
				<td valign="middle">
																							<a href="index.php?mod=messages&submod=messageNew&profileName=GreatApo&sh=XXXXXXXXX">γράψε μήνυμα</a>
															&nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=119682&amp;action=delete&sh=XXXXXXXXX">Αφαιρώ</a>
												</td>
			</tr>

												</table>
</section>
 ```

**Comment by SleepingShadow-bit** [comment]
At the moment i have a friend who isnt in my guild.

`  <section>
                <table border="0" cellpadding="2" cellspacing="2" style="width:100%;">
                    <tr>
                        <th style="max-width:100px;overflow:hidden;">Name</th>
                        <th>Gilde</th>
                        <th>Stufe</th>
                        <th>Status</th>
                        <th>&nbsp;</th>
                    </tr>

                                            <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18294&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="coonyyy">coonyyy</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>129</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:01:04</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=coonyyy&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18294&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=19350&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Latez">Latez</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>95</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:00:06</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Latez&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=19350&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=16143&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Jintha">Jintha</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>117</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:03:06</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Jintha&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=16143&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=19348&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="LoneStar">LoneStar</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>1</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">22:32:52</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=LoneStar&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=19348&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=19228&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="TheHawk">TheHawk</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>112</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">00:26:52</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=TheHawk&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=19228&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18928&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Schattenengel">Schattenengel</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>128</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">01:01:42</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Schattenengel&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18928&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=15721&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Son_Goku">Son_Goku</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>149</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">00:34:22</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Son_Goku&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=15721&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=19033&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Nurso">Nurso</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>103</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">-</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Nurso&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=19033&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18992&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Sarahbi">Sarahbi</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>121</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:00:02</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Sarahbi&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18992&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=19005&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="BlackMoney">BlackMoney</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>136</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:04:40</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=BlackMoney&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=19005&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=19044&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Apothegreek">Apothegreek</a></td>
                            <td>---</td>
                            <td>99</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">-</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Apothegreek&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=19044&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18958&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Panther">Panther</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>125</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:03:58</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Panther&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18958&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18971&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Temmu">Temmu</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>138</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">04:59:33</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Temmu&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18971&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=15996&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="PrinzEisenherz">PrinzEisenherz</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>163</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">1 Tag, 19:14:29</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=PrinzEisenherz&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=15996&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=16745&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="TexAvery">TexAvery</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>171</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:00:27</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=TexAvery&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=16745&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18937&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="JoKeR">JoKeR</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>159</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">01:04:05</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=JoKeR&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18937&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18835&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Lernutius">Lernutius</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>145</td>
                            <td><span style="color: #804000; font-weight: bold;" title="Online">00:13:20</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Lernutius&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18835&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18179&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Amun">Amun</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>131</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">8 Tage, 23:58:42</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Amun&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18179&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18345&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Grim">Grim</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>173</td>
                            <td><span style="color: red; font-weight: bold;" title="Away">20:57:03</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Grim&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18345&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                                    <tr>
                            <td style="max-width:100px;overflow:hidden;"><a href="index.php?mod=player&p=18809&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" title="Schatten-Leo">Schatten-Leo</a></td>
                            <td><a href="index.php?mod=guild&i=177&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >[BDS]</a></td>
                            <td>137</td>
                            <td><span style="color: green; font-weight: bold;" title="Online">00:00:01</span></td>
                            <td valign="middle">
                                                                                                        <a href="index.php?mod=messages&submod=messageNew&profileName=Schatten-Leo&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">Nachricht schreiben</a>
                                                                        &nbsp;<a href="index.php?mod=overview&submod=buddylist&amp;bid=18809&amp;action=delete&sh=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">verstoßen</a>
                                                            </td>
                        </tr>

                                                            </table>
            </section>`

**Comment by FrutyX** [comment]
Hmmm, I found out, on Glad. forums, that there has been already some problems with this (in 2019).

I think this feature has to be burned with fire 🔥 before it lays eggs 🥚.

**Comment by SleepingShadow-bit** [comment]
For me:
![IMG_20220103_184145](https://user-images.githubusercontent.com/8767665/147962091-32aea145-b7ab-4fb2-a07b-d16baafc9cd5.jpg)

**Comment by FrutyX** [comment]
Tested, working. Noted on the progress list.

Closing, re-open if needed.
