### ISSUE TITLE
Packages - total value on current page (event items bad calculations)

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#316]
GCA 4.3.6
Google Chrome v97

There is something very wrong with the calculations in packages, the event items with value 10g are badly calculated in "total value on current page".

First, it was showing the right value, but when moving started, it was going from to plus to minus, (from 100 to -20,), then it even added a dot (from -20 to -.150).

Example
![gca](https://user-images.githubusercontent.com/23278552/147769913-f53c40ae-e921-42ae-9acc-220964437888.gif)

**Comment by FrutyX** [comment]
#166 are thinking, that the value of the even item is 9g, but it's 10g.

**Comment by FrutyX** [comment]
Same goes for all other event items.

Other event items (snowballs excluded) are having a value of 13g, #166 thinks the value is 12g.

Unless this has been made on purpose and it's counted as 12g (lowered value) + 1g tax = 13g.

This is getting complicated.

![doctor-strange-things-just-got-out-of-hand](https://user-images.githubusercontent.com/23278552/147771775-1dd649f5-8bc1-4bbf-b122-a366bcae0e26.gif)

**Comment by FrutyX** [comment]
I am such a spammer, haha.

I know we had a similar problem in #248, could it be related?

**Comment by FrutyX** [comment]
![61cdea4e8741a457302044](https://user-images.githubusercontent.com/23278552/147774120-431bb0f6-1672-4165-bb1b-f4fcceea0f9a.gif)

**Comment by FrutyX** [comment]
Gif had awful quality.


https://user-images.githubusercontent.com/23278552/150959710-a52fe6f4-2af0-444b-9c82-23a1b59b6f7c.mp4

**Comment by GramThanos** [comment]
This is not a GCA bug.

**Comment by FrutyX** [comment]
Huh, it's been a while, so I don't remember how I tested it, but I am surprised I did not turned GCA off before reporting it, I don't really know, but it appears you are right.

**Comment by GramThanos** [comment]
This was one of the features the gameforge "borrowed" from the addon, a while back.
