### ISSUE TITLE
is there a way to filter multiple keywords in packages and auctions?

### ISSUE THREAD

**Issue by MiguelSOliveira** [DinoDevs/GladiatusCrazyAddon#324]
Is there a way to search multiple things in packages and auction with the same search?

For example: 

- Searching for "gaius + antonius" would get me the same results as searching independently for each word. So it would be items with Gaius and with Antonius.

Same for auction house.

Is there a way to do this at the moment?

**Comment by GramThanos** [comment]
I am not aware of such a functionality.

**Comment by GreatApo** [comment]
In the past, you could search with different keywords just by adding a space between them, but it was removed at some point.

**Comment by FrutyX** [comment]
Question answered, closing.

**Comment by MiguelSOliveira** [comment]
This was not just a question but a feature request. Unless this is something that GCA should not responsible for doing due to gameforge not allowing it?

**Comment by FrutyX** [comment]
I'll leave to Gram and Apo, cuz I am not 100% sure about it (if it's possible, it it's safe...).
