### ISSUE TITLE
Search for "unknown / unlearned" Items - advance Filter 

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#327]
Hey Guys,

search for "unknown / unlearned" Items for smelting in our advance filter? 
![image](https://user-images.githubusercontent.com/9620510/147989185-c2ad354a-d46a-47cc-8f5d-b960a997ed18.png)

Because it's troublesome to search 50 pages or more about the icon =)

**Comment by MiguelSOliveira** [comment]
What does that item mean ? I've seen it but have no idea

**Comment by SleepingShadow-bit** [comment]
Search for the feature "Enable special features per category"
The features acitived "Show if scrolls are know/unknown" and 📜 "Show scroll icon item's prefix/suffix is unknown"

https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/features/Documentation%20Packages.md

**Comment by GreatApo** [comment]
> What does that item mean ? I've seen it but have no idea... means you've never seen the item?

In order to forge items, you need to first learn each suffix/prefix scroll. That icon means the item has a suffix/prefix that you don't know. If you smelt such items, there is a chance you get one of its scrolls (suffix of prefix). You can get a nice view of the scrolls you know from the small icon at the bottom of the forge page:
 
![image](https://user-images.githubusercontent.com/9620510/147890010-b60fbcb0-3f62-4d05-ad9f-ee32af6cde77.png)
 
![image](https://user-images.githubusercontent.com/9620510/147890019-39b3719b-f8ae-462c-bd6c-3500e64706e4.png)

**Comment by MiguelSOliveira** [comment]
Wow awesome, didn't know that!

Really amazing work with this add on guys.. thank you for all your work!

(Sorry to deviate from the original topic)

**Comment by SleepingShadow-bit** [comment]
Oh sorry - It's an enhancement, but not what I want.
The extended filter hides the incorrect items. So I still have to leaf through all the existing pages.

**Comment by GreatApo** [comment]
Yeah, we just got a bit out of subject. This is a nice feature request, the reason we have nothing like that scripted yet is because it needs a lot of server requests and a bit more code to make it work.

**Comment by SleepingShadow-bit** [comment]
Alright.
I dont know if i adding a new feature request because ... "_because it needs a lot of server requests and a bit more code to make it work."_

I leave it with this enhancement, as it already simplifies the search for the icon

**Comment by SleepingShadow-bit** [comment]
However, I think the Extended Filter type will work very well with the List View.  This list view should also be adjustable how many pages you can display =)

You may also be able to filter by expedition, dungeons, market, auction,... here

**Comment by FrutyX** [comment]
Merged all "filter" request issues into one, from now, please use #343.

Closing.
