### ISSUE TITLE
TR update

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#329]
**Turkish**
 - Language: (Türkçe)

[tr.txt](https://github.com/DinoDevs/GladiatusCrazyAddon/files/7799740/tr.txt)

**Comment by GreatApo** [comment]
Thank you for the update @mattemre !

@FrutyX can you integrate this when you have some time?

**Comment by FrutyX** [comment]
Yeah, sure, but a little bit later.

**Comment by mattemre** [comment]
I think I forgot to put a comma.

**Comment by GreatApo** [comment]
> I think I forgot to put a comma.

If it's not part of the translation don't worry, we fix missing commas and special characters in strings!

**Comment by FrutyX** [comment]
Matt, why this is like the whole list and I can see some translation did not changed?

In the settings, there is a specific button for this:
![settings](https://user-images.githubusercontent.com/23278552/147889221-cae8b604-775b-4852-a37b-7e9617cfafea.PNG)

Unless, you want to rework the current translation, but I can see, some are completely same (or most of them?).

**Comment by mattemre** [comment]
I might be wrong again.

**Comment by FrutyX** [comment]
Oh I can see you only added the auction item name thing...

Next time, you can just copy it from this window, no need for the whole list.

**Comment by mattemre** [comment]
category_auction$item_name : "Eşya adını göster",

like this?

**Comment by FrutyX** [comment]
Yup, got it, thanks for the translation!
