### ISSUE TITLE
scrolls properties

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#331]
Like a gladiatus tools web site

I guess gladiatus tools website is down. Can you make a website that shows a scroll preview like this? I think it can be used as a separate page alongside Gladiatus simulator.

**Comment by FrutyX** [comment]
A duplicate Issue to #298.

Gladiatus-Tools are down only temporarily.

Also, do you know about this feature? Go to the forge and scroll down, click on the blue book:

![book](https://user-images.githubusercontent.com/23278552/147975614-8f57c774-8140-4579-b1d1-fa97dee4a5a4.PNG)

Rest is in #298. Closing.

**Comment by mattemre** [comment]
yes, I learned that feature yesterday thanks to you :). Before we craft an item, we look at its orange and red values.

**Comment by FrutyX** [comment]
@mattemre good! Unfortunately we can't upgrade the list, because we don't have the scroll data for all languages, but you can read that in #298 .
