### ISSUE TITLE
GCA Mobile Browser Bugs 

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#334]
Browser: [Kiwi Browser](https://kiwibrowser.com/)

**for example - bugs or anything else:**
- cant press the data and exp icon but the ugly gladiatus chat works 
- cant press the button at the smelt both of them
- its difficult to press the button add to target list 
- can't press the setting icon for Group inventory options

![IMG_20220104_013631](https://user-images.githubusercontent.com/8767665/147994850-6454c7df-4030-47c2-b500-e6fd9008466c.jpg)
![IMG_20220104_005132](https://user-images.githubusercontent.com/8767665/147994851-1b16faed-dca2-4cbe-9ab5-b98c6ccf3c6b.jpg)

**Comment by GreatApo** [comment]
Thank you @SleepingShadow-bit

**Comment by GramThanos** [comment]
These are all touchscreen related. For some reason the browser do not fire the click event after the touchend event.

**Comment by FrutyX** [comment]
![broken-phone](https://user-images.githubusercontent.com/23278552/148140356-6daf5fa0-3736-40df-9717-c64be76d0232.gif)

**Comment by SleepingShadow-bit** [comment]
Thank you.
I found an other one.
![IMG_20220625_191126](https://user-images.githubusercontent.com/8767665/175783863-074d4495-8d71-4d6b-b96d-71391588a998.jpg)

**Comment by GramThanos** [comment]
The advance filters button is not working?

**Comment by SleepingShadow-bit** [comment]
I can't press "+", "clear" and "apply filters"

**Comment by GramThanos** [comment]
I also fixed the buttons for the target list.
If you find more, reopen this issue.

**Comment by SleepingShadow-bit** [comment]
I test it all the last bugs! now its clean and works
Thank u so much!

**Comment by SleepingShadow-bit** [comment]
Statistic cant choose the setting view 
![IMG_20220802_053036](https://user-images.githubusercontent.com/8767665/182286578-8db7a7de-ae5b-4d28-b300-269c2f8b1d9c.jpg)

**Comment by GramThanos** [comment]
The statistics related problem can not be fixed (it is a problem of the library used to display the chart).
