### ISSUE TITLE
:poop: Gladiatus Time Saver :poop:

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#336]
I am sure that you know this extension...
I have done various actions in the past to cause problems to this extension and to its users, and I will continue to do so.

So... before we start I have to say the following:

1. I AM AGAINST USING SUCH EXTENSIONS.
2. FYI THE GLADIATUS TIME SAVER EXTENSION LOADS ADS & TRACKING CODE IN THE BACKGROUND PAGE

With that being said, I always check the code of such extensions so that I know if they are doing any malicious activity... and because it is fun deobfuscating their code...

Thus... since I want to mesh with the developer of this extension... 

here is a nice code to generate FREE tokens:

```javascript
(function(playerId){
	let player = parseInt((playerId + "").substr(0, 6));
	let base = 16;
	let expire = new Date('2022-12-31').getTime();
	let token = [];
	token.push(base + (0x13161f663 * player + 0x36f5b846c97a).toString(base));
	token.push((expire).toString(base));
	token.push((expire + 0x13161f663 * player).toString(base));
	token = token.join('-');
	return token;
})(/*Your PLAYER ID HERE -->*/ 1234 /*<-- Your PLAYER ID HERE*/);
```
And a demo here https://jsfiddle.net/q7zbfv6c/

I hope now the Author knows how I felt when he used my code for doing something I don't like.

**Comment by manyo50** [comment]
can we make premium code generator with few edits?

**Comment by GramThanos** [comment]
Yes, your player name, country and server?

**Comment by mattemre** [comment]
https://s48-tr.gladiatus.gameforge.com/game/index.php?mod=player&doll=1&p=20423&sh=646fa39df3a9aee0ba8f5ec7994519bc

TR - 48

**Comment by manyo50** [comment]
https://s48-tr.gladiatus.gameforge.com/game/index.php?mod=player&doll=1&p=20423&sh=646fa39df3a9aee0ba8f5ec7994519bc

TR - 48

**Comment by FrutyX** [comment]
Can we get some free rubies too?

:)

**Comment by GramThanos** [comment]
Yes, your player name, country and server?

**Comment by FrutyX** [comment]
Send it to this account please, it's for a friend :)

https://s4-gr.gladiatus.gameforge.com/game/index.php?mod=player&p=119682&sh=d41d8cd98f00b204e9800998ecf8427e

**Comment by GramThanos** [comment]
Damn... now I need passwords too...

**Comment by FrutyX** [comment]
Hmmm, weird, sounds like scam🤔

**Comment by GramThanos** [comment]
No, I am legit... look --> 💩 <-- Official poop icon. 
/s

**Comment by reckescorpiano** [comment]
What version of the extension is this code generator for?

I manage to generate the license, it syncs but disables all premium options :(

**Comment by Elderly-Emre** [comment]
it already generates standard key. It is necessary to follow a different path to generate premium keys.

**Comment by Elderly-Emre** [comment]
> zaten standart anahtar üretiyor. Premium anahtar oluşturmak için farklı bir yol izlemek gerekiyor.

it's not actually a standard key, it generates it on a different system

**Comment by castsanti** [comment]
its not working, can you help us? there is any way to make it think we are premium or bypass the premium checker? like editing the .js archive in the extension or smth.

**Comment by GramThanos** [comment]
> its not working, can you help us? there is any way to make it think we are premium or bypass the premium checker? like editing the .js archive in the extension or smth. 

This is not the place to ask people "how to cheat for free".

**Comment by nicolasc1991** [comment]
Llegue tarde para esto de la licencia? lo ocupe por 3 dias free y me gusto xD

**Comment by FrutyX** [comment]
Bruh, what is this?

People can't seem to realize that this isn't meant to be some cheating wikipedia, **GCA never been and never will support bot-like scripts.**

Since I still have my permission, I am gonna abuse it a little, and lock this, for the better.

**Comment by GramThanos** [comment]
As the title says... this was poop. An attempt to cause problems on a cheating addon. GCA has other features inside that detect cheaters and make fun of them :P

**Comment by FrutyX** [comment]
Is this still relevant? Working? Maybe it was patched.

Update it or close it, the choice is yours.

**Comment by GramThanos** [comment]
we can reopen it any time
