### ISSUE TITLE
Arena total gold

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#337]
It would be great if total gold stats were shown in arena reports.
The picture is purely an example.

![total gold](https://user-images.githubusercontent.com/95325400/148372567-92ac729f-fb6a-4ca3-850e-0aa7913b188e.png)

**Comment by mattemre** [comment]
What do you think? is this a possible?

**Comment by FrutyX** [comment]
Yes, but there is no estimated time where (or if) this will be added, possible it is.

**Comment by FrutyX** [comment]
But this... is very nice, and seems to be working well too, nice!

**Comment by SleepingShadow-bit** [comment]
I think the name is misleading.  Total gold per side.  Is it possible to display the gold of the whole day including losses?

![IMG_20220626_070959](https://user-images.githubusercontent.com/8767665/175800340-6fbbf8b0-8c91-4ecb-8cb8-3202529ff7c9.jpg)

**Comment by FrutyX** [comment]
For me, it's enough.

If you want to see the whole day, you would need to load other pages as well, which will create more requests, and you don't want that.

Perhaps Apo can tweak it a little bit however he can, but I would say it's pretty good in it's current state.

**Comment by GreatApo** [comment]
> I think the name is misleading. Total gold per side. Is it possible to display the gold of the whole day including losses?
> 
> ![IMG_20220626_070959](https://user-images.githubusercontent.com/8767665/175800340-6fbbf8b0-8c91-4ecb-8cb8-3202529ff7c9.jpg)

I changed the title to loot. Also, I was abstracting the loot when you get attacked but this included the win prize so it was not correct. I changed it to loot that you have gained (without accounting for looses)

**Comment by FrutyX** [comment]
I think it's a shame to remove losses when you can show it, only show it separately and I think it should be good.

**Comment by GreatApo** [comment]
> I think it's a shame to remove losses when you can show it, only show it separately and I think it should be good.

But we don't know the losses, we know the losses+win prizes :/

**Comment by FrutyX** [comment]
Right.

Can't you somehow lock on the text color? I don't know if it's possible and how such code should look like, and if it's even worth ti make something like it.

Honestly speaking, this is still pretty good as it is.

**Comment by FrutyX** [comment]
Nah, that's probably a shitty idea, forget it.

**Comment by GreatApo** [comment]
> Right.
> 
> Can't you somehow lock on the text color? I don't know if it's possible and how such code should look like, and if it's even worth it to make something like it.
> 
> Honestly speaking, this is still pretty good as it is.

Yes, I did that already but the when you lose a fight, the gold shown there is the gold you lost + the gold the opponent got a win prize (he didn't stole the full amount).

**Comment by SleepingShadow-bit** [comment]
Yes @FrutyX the feature is great.
I don't know what resources it takes to load all the pages and then you would have all the loot per day at a glance.

But i see its also my feature request at #354

**Comment by FrutyX** [comment]
I've said it many times, and before me I have it from Thanos or Apo, and it makes sense.

The best and possible features are the ones that does not require to load too much stuff and they are loaded in one page, not needing to load more pages. When multiple pages are loaded, it does create requests on the Gladiatus server, we don't want that because it could end up overloading the server and Gameforge surely will not like that.

But perhaps I am explaining it wrong, so I think Apo or Thanos should comment on this, maybe there are ways to bypass this, I don't know, that's why it's better to ask them, also they have some "past" with Gameforge, so they know best.

And yes, this also works for #354 too.

**Comment by FrutyX** [comment]
Implemented in v4.3.6, closing, re-open if needed.
