### ISSUE TITLE
Remove menu items like recruiting or training

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#340]
> i thought maybe u could add an option to remove some tabs like 'recruiting' or training if someone dont wanna train and dont wanna train by accident

by MBT on [Gladiatus forum](https://forum.gladiatus.gameforge.com/forum/thread/263-gladiatus-crazy-add-on/?postID=189554#post189554)

**Comment by GreatApo** [comment]
Even thought I would like the recruit menu option to be removed (I don't think anybody uses it), it may be against Gameforge's will since they is a financial reason it is there. If more players want it gone, please speak up so that we have a reason to back this up.

I see no use into removing the train menu option and it is impossible to accidentally train since you need to click 2 links at different locations on your screen. Again, if users see a use, please speak up.

**Comment by FrutyX** [comment]
In this particular case, I don't see a reason to disable anything, it's there, don't use it, it doesn't interfere with anything.

**Comment by FrutyX** [comment]
For moderation reasons, I want an opinion from @GramThanos, but the current opinions seems more or less the same.

So we can close this (or create a feature request...).

**Comment by GramThanos** [comment]
I don't see any value on such a feature.
I don't think that there is a rational behind it.
My vote is no.
