### ISSUE TITLE
Gods timers

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#341]
> there would be nice if u could add more timers, for oils (gods) for example, merchant time, war guilds, cooldowns better displayed instead of checking manually with cursor

by MBT on [Gladiatus forum](https://forum.gladiatus.gameforge.com/forum/thread/263-gladiatus-crazy-add-on/?postID=189554#post189554)

**Comment by GreatApo** [comment]
Half of these features already exist in a way: (make sure they are enabled in your settings)
- We already have a **merchant's timer** located on the green/red icon next to blacksmith
- When your **guild** is ready to **attack**, you get a notification
(make sure the above features are enabled in your settings)

For the other proposals:
- We can add a **gods' timer**, maybe similar to the merchants indicator
- Other cooldowns like what?

**Comment by FrutyX** [comment]
Duplicate to #201.

**Comment by FrutyX** [comment]
MBT uses mostly forum, never seen him on GitHub, answer there.

Gods timers Issue already exists (#201), other requests already exist or are unspecified, closing.

**Comment by GreatApo** [comment]
> MBT uses mostly forum, never seen him on GitHub, answer there.

I was not expecting him to reply, I was generally asking everyone in here :)

**Comment by FrutyX** [comment]
Well, I've closed this for moderation reasons.

And I am sure "everyone" here know how to create a feature request issue 😃.
