### ISSUE TITLE
guild war timer

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#342]
notification when guild war time expires

**Comment by FrutyX** [comment]
Isn't this already there? I never used it tho.

![war](https://user-images.githubusercontent.com/23278552/148684486-507acd1e-3573-4af6-8fb6-9eb11b24aadf.PNG)

If yes, then people seriously need to start to check their settings, we even have a whole feature documentation guide.

**Comment by mattemre** [comment]
I found this feature now, but it seems to be in the wrong place. Shouldn't this setting be in the alliance menu?

**Comment by mattemre** [comment]
I'm sorry for that. It's not my intention to bother you.

**Comment by FrutyX** [comment]
I didn't said you are bothering me, I don't know why people act so defensive now, the thing is, people also keep requesting things that are already there, all you have to do is check the settings, it's maybe there.

I think I have an idea why it's in global, the same idea goes for other settings in global, that could be moved, but that would require a lot of effort and I don't think it's necessary.

**Comment by FrutyX** [comment]
If Apo or Thanos got no comment, we can close this.

**Comment by mattemre** [comment]
I think we can close the issue. No need to make a big effort again. Next time I will review all the settings.

**Comment by GreatApo** [comment]
It doesn't bother me when people are not aware of features that are turned off by default. And you are right, it may fit better in guild settings. It is under the global settings because of technical reasons (the code needs to run no mater were you are). So it is a bit misleading...
