### ISSUE TITLE
Horreum - locales for specific actions

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#346]
No bug, no feature request - maybe an enhancement? 

When storing raw materials, there is probably an incorrect text. 
I mean the  text would be wrong. 

The same text also appears when converting raw materials.

Can't find this in the en.js file here. 

![IMG_20220120_173757](https://user-images.githubusercontent.com/8767665/150382596-e92ba405-25fa-4414-8de0-050d0781f124.jpg)

**Comment by FrutyX** [comment]
Alright, so it is in en.js at line 265.

The text itself isn't precise for the specific action, it's more like a global message that something changed in horreum, but you can see that.

For specific action, we will need to add it to the translations.

**Comment by FrutyX** [comment]
Oh welp, this script is detecting material changes, so it means the message is actually good and right.

It's not showing because you did a specific action,  but because something changed in the horreum...

**Comment by GreatApo** [comment]
> Oh welp, this script is detecting material changes, so it means the message is actually good and right.
> 
> It's not showing because you did a specific action, but because something changed in the horreum...

If I remember, it just tracks the change in the resources. I am not sure if we can somehow identify where the resources are coming from and I also don't see a value for now.

I am going to close this, feel free to expand on the idea if needed

**Comment by FrutyX** [comment]
I agree, good move.

Gladiatus is taking care of the horreum and I would say that this is too much work for such a little feature as material notification for specific action. Some things are better to leave alone.

**Comment by SleepingShadow-bit** [comment]
Yes its a good move. Put the energy into new good things. I Will adapt the text to changed and stored.. In my language. 
I think it is the easiest move.
