### ISSUE TITLE
auto-item highlight

### ISSUE THREAD

**Issue by xQlX** [DinoDevs/GladiatusCrazyAddon#349]
can you add a function to add some item names that got highlighted if you dropp the item or see it in the packages? a list to write names down that got highlighted gaius etc.

**Comment by GramThanos** [comment]
Can you explain a bit more your idea?

From what I understood, you want a way to select item names (prefixes and/or suffixes) and then the addon to hightlight them when it see such an item.

Am I right?

**Comment by FrutyX** [comment]
Isn't this in #343 already?

**Comment by xQlX** [comment]
no in the filter you can only search directly I mean an automatic mark comparable to the scrolls you have learned that simply have a red border

**Comment by xQlX** [comment]
here is an example https://gyazo.com/3cba24df0c54e472233fda234bff7b34

so it would then be marked the item that i select in a list before when i drop it which i can then customize myself with the suffixes and prefixes which is always active where i don't have to click on "search" or anything but directly when i drop the item is marked red and when i go into the packages there is also marked red

**Comment by FrutyX** [comment]
I am merging this issue with another into #306, because they are basically the same.

From now on, please continue in #306.
