### ISSUE TITLE
Quick Guild Message Issue

### ISSUE THREAD

**Issue by brunoaugusto** [DinoDevs/GladiatusCrazyAddon#35]
I've opened the game this morning and noticed the update. Yay!

Then I hovered the Guild Message quick link on top bar but after clicking **Send** on the top-left corner appeared:

> Undefined_Locale[global][no_data]

I imagined it could be just a missing i18n entry in your language files but after check, the message wasn't sent either.

**Comment by GreatApo** [comment]
The translation string _"No data"_ was not found. However, an event refreshing saved guild-members is missing. Click the _"online players"_ button once, this will update the saved guild data and the _Sent_ button will work.

2 issues here:
- The translation string was in the wrong section
   [FIXED] Translation call command was fixed
- Guild players seems to be updated only through online-friends button
   [FIXED] New function updating guild info every 24h
