### ISSUE TITLE
The shortcuts disappear sometimes

### ISSUE THREAD

**Issue by OzanKurt** [DinoDevs/GladiatusCrazyAddon#351]
I am not sure exactly when this happens but somethimes the shortcuts disappear.

![image](https://user-images.githubusercontent.com/8682003/172915099-5091e31d-c4b7-42d2-912c-0866651676ec.png)

Normal state:
![image](https://user-images.githubusercontent.com/8682003/172915223-7c746069-e4db-4a5c-9edc-858c7c105cbf.png)

**Console errors (optional)**
No errors in the console.

**Browser info (optional)**
 - Windows 10
 - Chrome (Latest)
 - 4.3.5

**Comment by GramThanos** [comment]
It seems like the addon does not have your guild information. You can visit
the list of players at your guild and the data will be synced.

Does it happen after a storage clean up on your browser or randomly?

**Comment by FrutyX** [comment]
Good to hear it has been solved, closing :).

**Comment by FrutyX** [comment]
@GramThanos you know what, when you have some time, it would be nice, if you made me a simple list of sites that needs to be visited to load GCA content, it is mentioned in my **Troubleshooting guide**, but not that specifically, I would like to add it there and you probably know it from your head, so I don't have to look for it in the codes.

Thanks.

**Comment by OzanKurt** [comment]
I finally found the real reason of this problem!

So as far as I see, the addon stores the settings in local storage via the `playerID` which is not accessible when you first load the tab and a mercenary is selected in the overview page instead of the "arena character". Since the mercenaries don't have an ID the addon creates a the following localstorage keys:
![image](https://user-images.githubusercontent.com/8682003/174484447-91f4386a-0649-4d16-a6af-0371513b491b.png)

Once you select your "arena character" and load the overview page it finds your `playerID` from this section:
![image](https://user-images.githubusercontent.com/8682003/174484511-01f193ea-f11d-437c-9788-a31361e0eeaf.png)

and loads the proper settings.
![image](https://user-images.githubusercontent.com/8682003/174484500-a1c32802-3a07-4c68-ae51-6d92283f89a5.png)
