### ISSUE TITLE
Automatic item transfer

### ISSUE THREAD

**Issue by Hades1953** [DinoDevs/GladiatusCrazyAddon#352]
Hello.
Could you please add options to automatically move items from packages to backpack (to fill it up) and from backpack to store?

**Comment by SleepingShadow-bit** [comment]
Equates to a bot. Bad idea.

**Comment by GreatApo** [comment]
We do our best to try an not cross the bot line. Unfortunately we can't automate this further. The current features to quickly repack are:
- Go to market and double click an item
- Make sure 1 gold option is select
- Hit enter to quickly list the item
- Hit the cancel button at the top of the market list

It is very fast if you sell many items together (eg. a full bag of item). Then clicking the cancel with send them all to the packages.
