### ISSUE TITLE
Lvl, Armour & Damage not shown

### ISSUE THREAD

**Issue by FilipSla** [DinoDevs/GladiatusCrazyAddon#353]
# Improvement
I was tired of seeing this mess:
![image](https://user-images.githubusercontent.com/44546766/175779738-7e288066-8bae-4bc6-a1b0-c227196585fb.png)
so I made few lines of code to improve it a little bit before they merge servers:
`const spanChange = document.querySelectorAll('.charstats_value21');`
`spanChange.forEach(charstats_value21 => {`
    `charstats_value21.style.marginRight = '10px';`
`});`
After adding it to page it looks as nice as before 😅
![image](https://user-images.githubusercontent.com/44546766/175779847-d6192117-b5d7-4321-b3ee-0ddcdffff4d7.png)

**Comment by FrutyX** [comment]
Okay but... it's a bug, it's on Gameforge's known issues list, so what is the point of this? I guess only for personal use until they'll fix it, but there is no point to add this to GCA.

**Comment by GramThanos** [comment]
It's a feature.

**Comment by FrutyX** [comment]
Funny.

**Comment by FilipSla** [comment]
The only funny thing is that the developer didn't check how it would be displayed or it could be missclick. He put there margin 100px instead of 10px.

**Comment by GramThanos** [comment]
Gameforge always tests the codes, this is why it was deployed publicly, so that anyone can test.

**Comment by FrutyX** [comment]
Users are always the best testers, indeed.

**Comment by FilipSla** [comment]
And yes, it is mainly for personal usage.

**Comment by GreatApo** [comment]
I am assuming they will fix it so I propose not doing any actions until the servers merge. If it is still there, I will add the proposed code as a fix.
@FilipSla , if it annoys you, you can add user code in the overview.js and player.js inject functions in your local copy.

**Comment by FrutyX** [comment]
How incompetent you must be, to not fix this day 1? Sure, it's not game breaking and the values can still be seen when you hover over the stats (+ in other places), and they are probably planning it to release the fix with the next version that is also planned, but still, one quick hotfix could fix it.

This is convincing me that Gladiatus could be only a huge mess after the merges.

**Comment by GramThanos** [comment]
I don't think they don't take the game seriously as doesn't have a big player base. The servers merging could be a potential costs reduction. I am sure they patched it on day one but they wait for the scheduled update to release it.

When I reported a security issue to them a few months ago, they patched it in 2 days.

**Comment by warkadiusz** [comment]
Just in case someone checks that issue to find some solutions, here is temporary fix with custom uBlock filter:
```
gladiatus.gameforge.com##.charstats_value21:style(margin-right: 0 !important)
```

**Comment by GreatApo** [comment]
A fix has been in the changelog for game version 4.6.1 which is going to be live tomorrow (probably on all servers).

**Comment by FrutyX** [comment]
Fixed by Gameforge, closing.
