### ISSUE TITLE
Packages - total value of category / all side (summation) 

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#354]
Is it possible to count the total value of a rubric?

![IMG_20220626_072539](https://user-images.githubusercontent.com/8767665/175800711-cbe10040-7da9-40e4-8779-5d89ce94d023.jpg)

**Comment by FrutyX** [comment]
Ehh, can you be more specific? I am having troubles understanding what exactly you want here.

**Comment by SleepingShadow-bit** [comment]
For the example i filter for Gold. So i can see the value of the page and value of all rubric.

My feature request is to display the value of all gold page.

**Comment by GramThanos** [comment]
Do you mean `Rubies`? I am confused.

**Comment by SleepingShadow-bit** [comment]
No.
Total value of gold
Total value of weapons
Total value of receipt
.
.
.

Filter for an category and see the total value of ALL side

**Comment by GreatApo** [comment]
We had a similar feature counting the gold and value of all items but Gameforge wanted it removed (causes a huge load on the servers). Actually this is why they added the value of the packages at the bottom :P

Anyway, I think we need to avoid such a solution again. I also don't see any other way of implementing this feature so I am going to close this request for now.

**Comment by SleepingShadow-bit** [comment]
Thank u Apo for the answer and clarification about the GF topic! =)
