### ISSUE TITLE
private Message Sending text - frame stretched

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#357]
**Describe the bug**
Send a private Message without addon = OK
![Screenshot_20](https://user-images.githubusercontent.com/8767665/176021507-97ba4d1c-079f-453a-ad96-9b004c2aab7e.png)

Send a private Message with addon = frame streched
![Screenshot_21](https://user-images.githubusercontent.com/8767665/176021530-147f1a60-af91-45fe-9eb2-b7d99489b8e0.png)

**Browser info (optional)**
 - OS: Windows
 - Browser Version Chrome with 103.0.5060.53
 - Installed GCA version [e.g. 4.3.6 - Beta

**Comment by FrutyX** [comment]
Please do test it now with the latest commit.

If you see more of these, just let us know.

**Comment by FrutyX** [comment]
![dev](https://user-images.githubusercontent.com/23278552/176191020-378be797-b6c9-4cc7-9bb4-857bdb6f0784.png)

**Comment by SleepingShadow-bit** [comment]
now we have a fix :) Thank you
![Screenshot_25](https://user-images.githubusercontent.com/8767665/176192063-ecbce83c-0056-457d-a7a6-5c68d506caf3.png)

**Comment by FrutyX** [comment]
Perfect.

It's possible to move it but it requires more changes and I don't think it's worth it, better to keep it as it is, honestly, it's just cosmetic.

**Comment by FrutyX** [comment]
@SleepingShadow-bit can you sleep well now? 😆

**Comment by SleepingShadow-bit** [comment]
I will sleep like a baby xD
