### ISSUE TITLE
merchants color search

### ISSUE THREAD

**Issue by Elderly-Emre** [DinoDevs/GladiatusCrazyAddon#360]
Source/core/source/merchant.js

74	---------			if (color === this.qualities[0]) option.selected = true;
74	---------			if (color === this.qualities[3]) option.selected = true;

wouldn't it be easier like that?
when i open the merchant we can search purple or higher directly.

**Comment by FrutyX** [comment]
I think I agree, usually everyone search for purple +,  however @GramThanos made this, so I won't touch it without him saying or doing so.

**Comment by FrutyX** [comment]
Implemented in v4.3.6, closing, re-open if needed.
