### ISSUE TITLE
Stats box behind event timer

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#367]
![image](https://user-images.githubusercontent.com/9620510/177542713-3d79eb07-e816-4ae4-b480-d7d3f7f00c22.png)

**Comment by FrutyX** [comment]
z-index should do the trick, I think.

**Comment by GreatApo** [comment]
> z-index should do the trick, I think.

I was hopping for that but it is not that simple.

**Comment by FrutyX** [comment]
Oh, but it is.
