### ISSUE TITLE
Item error - from storage to an item

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#369]
Taken from #311 
--
This errors shows up, when you use the item directly on an item, from your storage.

Items like grindstone, shred of leather, protective gear and this kind of stuff, anything that can be moved directly from warehouse inventory on an item in my inventory.

https://user-images.githubusercontent.com/23278552/150957521-44da1a3c-46cc-4b56-ba33-506a9b58080d.mp4

**Comment by FrutyX** [comment]
Son of a javascript, I think I found it, it's happening (dataset) when you are using this GCA feature:
![hammer](https://user-images.githubusercontent.com/23278552/180061431-e8ef256d-3388-406f-99ca-7f6d67f88a57.PNG)

`global.js?4.3.6&built=1658343486834:3938 Uncaught TypeError: Cannot read properties of undefined (reading 'dataset')
    at global.js?4.3.6&built=1658343486834:3938:76
    at gca.tools.js?4.3.6&built=1658343486831:948:8`

**Comment by FrutyX** [comment]
So Thanos, instead of fixing one, you created two new errors, I have to take your MVP badge, sorry.

🤣

**Comment by GramThanos** [comment]
Yeah, sure...

**Comment by FrutyX** [comment]
Btw, I knew you cannot resist the # 69.... 😉

**Comment by GramThanos** [comment]
I can't reproduce this error. Are you sure there is a problem?

**Comment by FrutyX** [comment]
Definitely, the video shows how, and with it, I can reproduce it easily:

![error](https://user-images.githubusercontent.com/23278552/183103766-77dc737a-1fd3-4ccf-87ed-d4eddd5ddfa3.PNG)

**Comment by GramThanos** [comment]
So, it was fixed everywhere exept guild storage. Now it should be ok everywhere.

**Comment by FrutyX** [comment]
Ummm, now I am getting the error even when I only move such improvement item to the storage :D:

![error2](https://user-images.githubusercontent.com/23278552/183107016-14312120-9678-4936-a61b-b446eaab8cea.PNG)

**Comment by FrutyX** [comment]
It just don't want to die 😆

**Comment by FrutyX** [comment]
Well now that's new, but ultimately, there is no error :D.

Thank you, Thanos.

![new](https://user-images.githubusercontent.com/23278552/183110387-cc3ebf40-e534-4382-98ef-ffb667005573.PNG)

**Comment by FrutyX** [comment]
68be623 I see what you did there.

**Comment by FrutyX** [comment]
Patched in v4.3.6, closing, re-open if needed.
