### ISSUE TITLE
Show mercenary max stats on tooltips

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#371]
I think this is helpful comparing mercenaries:
![image](https://user-images.githubusercontent.com/9620510/177891317-27321ee2-1113-4062-a2fb-4b55c4747465.png)

Stats are the maximum values from mercenary's stats

**Comment by GreatApo** [comment]
Currently hidden under the "Display mercenaries real names" option

**Comment by FrutyX** [comment]
Did Apo do some poo poo? I haven't looked at it closely, just noticed it, latest commit running.

![apo](https://user-images.githubusercontent.com/23278552/179418449-fbfee7de-b6cb-43fd-96ea-c576f7ce7752.PNG)

**Comment by GreatApo** [comment]
> @GreatApo Did Apo do some poo poo? I haven't looked at it closely, just noticed it, latest commit running.
>

I may have make a poo poo

**Comment by FrutyX** [comment]
Implemented in v4.3.6, closing, re-open if needed.
