### ISSUE TITLE
Add Shortcut to Bathroom / VOX 1

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#372]
Hello,
can we add a shortcut Icon / Link to the bathroom / Vox 1?
Because i think with the new feature, the VOX will be used more again?

**Comment by SleepingShadow-bit** [comment]
Can somebody add the de translation?

global : {
	guild_baths_goto : "Zum Badehaus (Vox I)"
}

**Comment by FrutyX** [comment]
Implemented in v4.3.6, closing, re-open if needed.
