### ISSUE TITLE
Top btn

### ISSUE THREAD

**Issue by MrMakintosh** [DinoDevs/GladiatusCrazyAddon#38]
It will be cool to add "top" button while scrolling :)

**Comment by GramThanos** [comment]
A got to top button? So you don't have to scroll back to top?

**Comment by MrMakintosh** [comment]
Yes

**Comment by DarkSide666** [comment]
yes. That's especially good to have in market and auction pages which can be quite long.

**Comment by GreatApo** [comment]
Ready!

![image](https://user-images.githubusercontent.com/9620510/34384255-c238a576-eb23-11e7-8e22-5b04dddb773d.png)

commit e228d730239d497abf374e29d503b3173b421523
