### ISSUE TITLE
Disable Britannia drop gathering

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#386]
If you have a lot of material enemy drop data gathered for enemies that we don't have data for, please share them in this issue.

To do so, got to gladiatus page, hit F12 and the run the following command in the console:

```
let localData = gca_data.section.get("data", "enemy_drops", []);
let groupedLocalData = {}
for (let i = 0; i < localData.length; i++) {
	let item = localData[i];
	if (item[1].substring(0,3) == "18-"){
		let enemy = item[0].replace(/\..+$/g, "");
		let material = parseInt(item[1].substring(3), 10);
		if (!(enemy in groupedLocalData)) groupedLocalData[enemy] = {};
		if (material in groupedLocalData[enemy]) groupedLocalData[enemy][material] += 1;
		else groupedLocalData[enemy][material] = 1;
		if ("total" in groupedLocalData[enemy]) groupedLocalData[enemy]["total"] += 1;
		else groupedLocalData[enemy]["total"] = 1;
	}
}
console.log(groupedLocalData)
```

You will then see something like the following, which you can copy-paste in this issue:
![image](https://user-images.githubusercontent.com/9620510/180075871-42af82df-df89-455d-a844-f646fe0b0bf5.png)

**Comment by mattemre** [comment]
{4/2_4: {…}, 4/3_4: {…}, 3/0_2: {…}, 3/2_4: {…}, 3/0_4: {…}, …}
3/0_2: {54: 1, 64: 1, total: 2}
3/0_4: {53: 1, total: 1}
3/1_4: {54: 1, total: 1}
3/2_2: {54: 1, total: 1}
3/2_4: {64: 1, total: 1}
3/3_2: {60: 1, total: 1}
4/1_4: {6: 1, total: 1}
4/2_4: {5: 3, 6: 2, 7: 3, 8: 4, 9: 2, 10: 2, 11: 1, 12: 5, 13: 1, 15: 2, 16: 1, 17: 3, 18: 3, 19: 4, 20: 3, 21: 1, 22: 3, 23: 4, 24: 2, 25: 3, 26: 3, 27: 4, 28: 2, 29: 2, 30: 3, 31: 2, 32: 4, 33: 5, 35: 2, 36: 1, 37: 1, 38: 3, 39: 8, 40: 7, 41: 3, 42: 3, 43: 2, 44: 2, 45: 6, 46: 3, 47: 6, 48: 4, 49: 4, 50: 2, 52: 3, 53: 3, 54: 1, 55: 3, 56: 4, 57: 3, 59: 1, 60: 1, 61: 1, 62: 2, 63: 2, 64: 1, total: 159}
4/3_4: {7: 3, 8: 1, 9: 1, 11: 1, 13: 1, 14: 1, 16: 1, 19: 2, 20: 2, 21: 1, 24: 1, 26: 2, 27: 2, 28: 1, 31: 1, 32: 2, 38: 1, 39: 4, 40: 1, 42: 1, 44: 1, 46: 1, 48: 2, 49: 3, 51: 1, 53: 1, 54: 1, 56: 1, 57: 1, 60: 1, 62: 1, 64: 1, total: 45}
[[Prototype]]: Object

![image](https://user-images.githubusercontent.com/95325400/180110190-eb8a2036-25d1-4a03-8a2c-9480039e2271.png)

**Comment by FrutyX** [comment]
Well, I don't know how reliable my data is, because I keep swapping developer versions (and it was plagued with bugs now), but I haven't touch my data, so it probably should be intact, you can check it out.

<details>

```
{
    "3/0_4": {
        "48": 1,
        "53": 1,
        "58": 1,
        "total": 3
    },
    "3/3_4": {
        "58": 1,
        "total": 1
    },
    "4/4_4": {
        "5": 7,
        "6": 4,
        "7": 6,
        "8": 8,
        "9": 4,
        "10": 2,
        "11": 6,
        "12": 3,
        "13": 4,
        "14": 2,
        "15": 3,
        "16": 4,
        "17": 4,
        "18": 5,
        "19": 8,
        "20": 3,
        "21": 8,
        "22": 4,
        "23": 5,
        "24": 2,
        "25": 5,
        "26": 6,
        "27": 4,
        "28": 2,
        "29": 5,
        "30": 2,
        "31": 6,
        "32": 3,
        "33": 4,
        "34": 5,
        "35": 6,
        "36": 3,
        "37": 8,
        "38": 5,
        "39": 10,
        "40": 2,
        "41": 6,
        "42": 2,
        "43": 7,
        "44": 7,
        "45": 7,
        "46": 4,
        "47": 5,
        "48": 3,
        "49": 7,
        "50": 7,
        "51": 3,
        "52": 3,
        "53": 7,
        "54": 7,
        "55": 5,
        "56": 6,
        "57": 6,
        "58": 7,
        "59": 7,
        "60": 6,
        "61": 8,
        "62": 3,
        "63": 5,
        "64": 4,
        "total": 300
    },
    "3/2_3": {
        "61": 1,
        "total": 1
    },
    "3/0_3": {
        "30": 1,
        "60": 1,
        "total": 2
    },
    "3/0_2": {
        "64": 1,
        "total": 1
    },
    "3/1_2": {
        "31": 1,
        "total": 1
    },
    "3/2_1": {
        "30": 1,
        "total": 1
    },
    "3/1_3": {
        "59": 1,
        "total": 1
    }
}
```

</details>

**Comment by GreatApo** [comment]
Thank you both! Unfortunately I don't see any material with higher drop for a specific enemy

**Comment by FrutyX** [comment]
When the materials were shown on the enemies, I have noticed that in Britannia, that unlike other locations, the materials just kept rotating, so most likely, this feature can be disabled there, or needs more testing.

**Comment by GreatApo** [comment]
Yes, it looks like drops are all over the place for Britannia

**Comment by FrutyX** [comment]
You know what Apo, I am going to farm another boss for a while and check if he is also dropping multiple materials, however, I think the best option would be not to hardcode it but just let GCA to show them, and since GCA is showing only two materials now, it also needs to be changed, I think I would add a carousel (< material material >) to it, so multiple material can be shown.

But it's just an idea.

**Comment by GreatApo** [comment]
> I would add a carousel (< material material >) to it, so multiple material can be shown.
> 

Based on our collected data, most enemies have a much higher chance to drop 2 specific materials, that's why only 2 are shown. In Britannia where it seems that each enemy drops more material (or any) there is not really a point of this feature (if my assumption is correct) since it will just be a list of most if not all materials with a similar drop rate (useless)

**Comment by FrutyX** [comment]
I guess you're right.

**Comment by FrutyX** [comment]
This was Apo's thing, but the gathering is still activate in the code, but it's not needed in Britannia, so once Apo is in mood, I guess this can be disabled and this issue closed?

**Comment by FrutyX** [comment]
Well then.

No saving the data because it drops like everything (in Britannia), but also I don't see a reason why it can't stay enabled and show some resources, even if they should rotate.

Anyaways, there was no response, I am closing this.

**Comment by GreatApo** [comment]
> This was Apo's thing, but the gathering is still activate in the code, but it's not needed in Britannia, so once Apo is in mood, I guess this can be disabled and this issue closed?

Let's leave it running to see if there is a pattern, but yeah, this doesn't seem to lead anywhere.

**Comment by FrutyX** [comment]
>  if there is a pattern

4/4_4: 
{5: 12, 6: 12, 7: 10, 8: 12, 9: 13, 10: 19, 11: 9, 12: 12, 13: 11, 14: 12, 15: 7, 16: 13, 17: 8, 18: 15, 19: 11, 20: 10, 21: 12, 22: 12, 23: 14, 24: 10, 25: 16, 26: 13, 27: 12, 28: 11, 29: 14, 30: 5, 31: 14, 32: 16, 33: 12, 34: 10, 35: 12, 36: 7, 37: 12, 38: 9, 39: 11, 40: 7, 41: 10, 42: 16, 43: 11, 44: 15, 45: 11, 46: 15, 47: 18, 48: 11, 49: 9, 50: 9, 51: 9, 52: 12, 53: 8, 54: 11, 55: 11, 56: 12, 57: 15, 58: 10, 59: 13, 60: 15, 61: 13, 62: 7, 63: 7, 64: 13, total: 696}

**Comment by GreatApo** [comment]
> > if there is a pattern
> 
> 4/4_4: {...data...}

![image](https://user-images.githubusercontent.com/9620510/197510421-7b810384-fe4c-4f1b-b9b9-b9dff6e9a6e1.png)

I am not convinced :P

**Comment by FrutyX** [comment]
I will try a different boss, but I think the result will be the same.

**Comment by GreatApo** [comment]
> I will try a different boss, but I think the result will be the same.

I am kidding :P

**Comment by FrutyX** [comment]
Yeah but, I was planning it anyway, riddle me this:

```
4/5_4:
{
    "5": 6,
    "6": 8,
    "7": 7,
    "8": 9,
    "9": 8,
    "10": 5,
    "11": 5,
    "12": 6,
    "13": 3,
    "14": 4,
    "15": 8,
    "16": 3,
    "17": 4,
    "18": 6,
    "19": 4,
    "20": 7,
    "21": 4,
    "22": 12,
    "23": 4,
    "24": 5,
    "25": 9,
    "26": 4,
    "27": 4,
    "28": 4,
    "29": 7,
    "30": 4,
    "31": 8,
    "32": 7,
    "33": 6,
    "34": 2,
    "35": 8,
    "36": 3,
    "37": 4,
    "38": 8,
    "39": 7,
    "40": 5,
    "41": 5,
    "42": 6,
    "43": 7,
    "44": 5,
    "45": 9,
    "46": 6,
    "47": 2,
    "48": 7,
    "49": 8,
    "50": 11,
    "51": 9,
    "52": 8,
    "53": 6,
    "54": 3,
    "55": 4,
    "56": 5,
    "57": 4,
    "58": 3,
    "59": 6,
    "60": 6,
    "61": 9,
    "62": 6,
    "63": 12,
    "64": 5,
    "total": 360
}
```
