### ISSUE TITLE
Don't Show clickable link on Private Message 

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#387]
The following feature is not supported for private messages.

![177401472-3656685d-d403-497a-bae8-faf01d47c4a7](https://user-images.githubusercontent.com/8767665/180597149-57f1a64f-58de-4955-bbfc-b292ac6320b8.jpg)

![IMG_20220723_103040](https://user-images.githubusercontent.com/8767665/180597282-edadfe1b-d77f-4185-bd8c-cc8a3f51e821.jpg)

Browser Kiwi
Version currently beta

**Comment by GramThanos** [comment]
Probably duplicate of #116.

In any case, since private messages may came from untrusted sources we shouldn't parse them.

**Comment by SleepingShadow-bit** [comment]
Oh thank for the explanation.
I think we can close it or?
