### ISSUE TITLE
Improve Highscore tables (positions)

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#396]
<details>

![table](https://user-images.githubusercontent.com/23278552/183221122-2613865f-42e8-4f7b-acff-30cc43c1cd4f.PNG)
![table2](https://user-images.githubusercontent.com/23278552/183221124-765a74b3-fcf7-4c39-a3ce-21a1625eaf4d.PNG)

</details>

**Comment by FrutyX** [comment]
This is now in a testing phase, you can test it, you can see if it caused any other problems.

Also, this might be deleted in the future, if Gameforge decides to fix it.

**Comment by FrutyX** [comment]
Problematic: This is also editing the reports layout, will take a look when I have time.

**Comment by FrutyX** [comment]
Does not have any ID, only class.. unsure if can be done without javascript... thinking.

**Comment by FrutyX** [comment]
I don't want to bring javascript into this, this was meant to be a simple fix, but Gameforge does not know what IDs are...

**Comment by FrutyX** [comment]
Me vs Gladiatus:

![patrick-bateman-why-isnt-it-possible](https://user-images.githubusercontent.com/23278552/183248433-9fedbbf5-85c7-4955-ac18-2ca5225bfe57.gif)


@GramThanos have you ever heard about a script, that injects (during the page load) to all elements without IDs an a unique automatically generated ID (probably from it's class name, so we can select it every time)? Imagine how easily would be to edit the page, if everything had it's own ID... Such script is a... Thanos level threat, lol.

**Comment by GramThanos** [comment]
> Me vs Gladiatus:
> 
> ![patrick-bateman-why-isnt-it-possible](https://user-images.githubusercontent.com/23278552/183248433-9fedbbf5-85c7-4955-ac18-2ca5225bfe57.gif)
> 
> 
> @GramThanos have you ever heard about a script, that injects (during the page load) to all elements without IDs an a unique automatically generated ID (probably from it's class name, so we can select it every time)? Imagine how easily would be to edit the page, if everything had it's own ID... Such script is a... Thanos level threat, lol.

You lost me at "have"

**Comment by FrutyX** [comment]
Fine, I'll do it myself.

😛

**Comment by FrutyX** [comment]
#403
