### ISSUE TITLE
Fix the broken line in header links (with various languages)

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#397]
![header](https://user-images.githubusercontent.com/23278552/183289025-5bc679ea-afb1-4c83-b8f2-9298f0cc899d.PNG)

**Comment by FrutyX** [comment]
Note for Thanos: I am not doing this for Gameforge, but for GCA users and simply for this project.

**Comment by GramThanos** [comment]
Μάιστα...

**Comment by FrutyX** [comment]
#403
