### ISSUE TITLE
Gladiatus site fixes & improvements (CSS style)

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#403]
**Total status:** Currently in the testing phase.

## UW Slider style bug (your avatar) #399 
🟡 **Status:** Implemented, testing

<details>

![yourself](https://user-images.githubusercontent.com/23278552/183293661-1e14bd1d-815a-41a4-bca4-5a6033627e4d.PNG)

</details>

## Main menu text breaking the line (with various languages) #398
🟡 **Status:** Implemented, testing

<details>

![text](https://user-images.githubusercontent.com/23278552/183292489-e6c6ed3b-4a66-434d-8cbd-7b20f0a66502.PNG)

</details>

## Fix the broken line in header links (with various languages) #397 
🟡 **Status:** Implemented, testing

<details>

![header](https://user-images.githubusercontent.com/23278552/183289025-5bc679ea-afb1-4c83-b8f2-9298f0cc899d.PNG)

</details>

## Improve Highscore tables (positions) #396
🟡 **Status:** Implemented, testing

<details>

![table](https://user-images.githubusercontent.com/23278552/183221122-2613865f-42e8-4f7b-acff-30cc43c1cd4f.PNG)
![table2](https://user-images.githubusercontent.com/23278552/183221124-765a74b3-fcf7-4c39-a3ce-21a1625eaf4d.PNG)

</details>

## Inventory tabs misaligned
🟡  **Status**: Implemented, testing

<details>

![invtabs](https://user-images.githubusercontent.com/23278552/184510304-7946ebb4-65f0-42b8-a42b-4d847ca18899.PNG)

</details>

## Buffs icons incomplete 
🟡 **Status**: Implemented, testing

<details>

![buffbar](https://user-images.githubusercontent.com/23278552/184510537-a8bde9af-2654-4a09-8510-0f31c5b503f6.PNG)

</details>

## Event timer visual overhaul
🟡 **Status**: Implemented, testing

## Custom scrollbar
🟡 **Status**: Implemented, testing

## Arena tables overhaul
🟡 **Status**: Implemented, testing

**Comment by SleepingShadow-bit** [comment]
![IMG_20220814_220907](https://user-images.githubusercontent.com/8767665/184553190-6a97cea0-c06e-4b65-9d79-6c02f82aeed2.jpg)

Is that new?

**Comment by FrutyX** [comment]
I've never seen that, are you on PC, not on a phone, right?

**Comment by SleepingShadow-bit** [comment]
Oh sorry for no information.
Smartphone and the current version. I will check tomorrow on PC

**Comment by FrutyX** [comment]
I thought so, then reopen  #334. I don't really focus on mobile problems in this issue.

**Comment by GramThanos** [comment]
Avoid using "fix" related keywords in commits 😆 , I had the same problem.

**Comment by FrutyX** [comment]
I am aware of it, but I forgot about it, it's annoying, yeah :/.

**Comment by FrutyX** [comment]
Reminder: Some changes aren't optimized for server with different side, needs to be adjusted. Other than that, there are things outside this feature that needs attention too.

**Comment by SleepingShadow-bit** [comment]
@FrutyX  i like your style fix and changes. Could you do the pot meter without that red gimmick?

![IMG_20220825_085611](https://user-images.githubusercontent.com/8767665/186597898-518f3a3d-acbe-42f8-b28e-e09d3af20dea.jpg)


And above the topic with the mobile version is no longer present

**Comment by FrutyX** [comment]
Hmm, well, can't satisfy everyone, do you like this more?

![again](https://user-images.githubusercontent.com/23278552/186623979-fd4623a9-4eb0-47ff-8865-8640d6abaa3f.PNG)

It is true that sometimes simpler is better...

**Comment by FrutyX** [comment]
? :D

![testing](https://user-images.githubusercontent.com/23278552/186638945-7a70a814-494f-4575-993e-86a9806b1aef.PNG)

Which one does Thanos likes the most?

**Comment by GramThanos** [comment]
I have no idea what this is :P

**Comment by FrutyX** [comment]
Eh... it's up to Sleeping then.

I can be very indecisive when it comes to design choices.

**Comment by SleepingShadow-bit** [comment]
> 

Like this one. Simple and good and not to much gimmick.

**Comment by FrutyX** [comment]
Then it's decided, simple it is.

**Comment by FrutyX** [comment]
This will stay open for future fixes and improvements, plus I wanna have a list/overview of things related and made for this.

**Comment by FrutyX** [comment]
Now Gameforge is gonna release a patch for the incomplete buffs icon I patched, now let's see what is gonna happen.
(Most likely nothing, hah)

![PauseChamp](https://user-images.githubusercontent.com/23278552/191039068-208baeb5-752e-43c4-bd5f-74ad431c749e.png)

**Comment by FrutyX** [comment]
> Now Gameforge is gonna release a patch for the incomplete buff icons I patched, now let's see what is gonna happen. (Most likely nothing, hah)

Lol,  my "fix" is still improving it, just look at those unnecessary spaces if I remove my css change:
![buffbar](https://user-images.githubusercontent.com/23278552/191243810-2a627d7f-de85-49e9-aa66-28f5b8def983.PNG)
