### ISSUE TITLE
One Guild Market Page

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#404]
Is a feature possible that you can get the save items from the guild market on one side. Reason: Saves over 2 pages are sometimes confusing, but they are required.

**Comment by FrutyX** [comment]
So if I get you right, you want to load more items on one page?

Related to #180.

**Comment by SleepingShadow-bit** [comment]
That's correct.  Why didn't I find that :/

We can close that

**Comment by FrutyX** [comment]
#180
