### ISSUE TITLE
Forging Wrong Mats (Guild Mail Tipp)

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#416]
Forging Slot I is showing wrong mats via Guild Mail Tipp.
Version Beta
Google Chrome

https://user-images.githubusercontent.com/8767665/187983843-eaf0b53c-3b0f-4a10-8b44-416d5a379926.mp4

**Comment by FrutyX** [comment]
Well, yes, this is happening sometimes, a few times when I was trying this, I had no problem, but then this occurred, it sometimes need a kick, to refresh itself.
