### ISSUE TITLE
Failed to detect enemy - material as secondary drop

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#419]
Taken from #382.

![error3](https://user-images.githubusercontent.com/23278552/183107496-7206a9dc-5040-456e-a017-c4452dfa5c6b.PNG)
> Confirmed, a secondary drop is causing this errors (very #368 related):
> **And it does look like, that the secondary drop has to be a material, for this error to happen.**
> 
> `Failed to detect enemy url("//gf3.geo.gfsrv.net/cdn29/bac7e539d61a9de6caec21363c2694.jpg")`
> 
> ![scd](https://user-images.githubusercontent.com/23278552/183431391-1cb182af-b19e-4394-b006-acce49f14c26.PNG)
>

**Comment by GreatApo** [comment]
I can't see how this error can happen with the current code.
```gca_tools.img.resolve("//gf3.geo.gfsrv.net/cdn29/bac7e539d61a9de6caec21363c2694.jpg")``` returns the enemy, so the error should not appear with the current code. Can anyone still replicate it?

**Comment by FrutyX** [comment]
I think Thanos said something like that too, but I am getting it pretty normally (remember, a secondary drop and only a material), basically my error log is spammed with it.

**Comment by FrutyX** [comment]
And so it goes on... might just disable the console warning.

![errors](https://user-images.githubusercontent.com/23278552/191841065-e0bd00a8-d57c-4e15-8770-7de0f6ddac7a.PNG)

**Comment by GreatApo** [comment]
> I think Thanos said something like that too, but I am getting it pretty normally (remember, a secondary drop and only a material), basically my error log is spammed with it.

Does running ```gca_tools.img.resolve("//gf3.geo.gfsrv.net/cdn29/bac7e539d61a9de6caec21363c2694.jpg")``` return the enemy url?

**Comment by FrutyX** [comment]
Yeah, it returns the enemy url `'img/npc/4/4_4.jpg'`, however I am looking at it now as a stored report, maybe the result would be different when it actually occurs, but damn, my UW costume just expired :D.

**Comment by GreatApo** [comment]
> Yeah, it returns the enemy url `'img/npc/4/4_4.jpg'`, however I am looking at it now as a stored report, maybe the result would be different when it actually occurs, but damn, my UW costume just expired :D.

Still throws an error?

**Comment by FrutyX** [comment]
Not when looking at an old stored report.

**Comment by GreatApo** [comment]
> Not when looking at an old stored report.

I think it works

**Comment by FrutyX** [comment]
Wait what? What works? :D I mean it works, but it's still throwing an error, but in when looking at the report later.

**Comment by GreatApo** [comment]
> Wait what? What works? :D I mean it works, but it's still throwing an error, except when looking at the report later.

Oh, sorry, yes it doesn't check the data if the report is old.

Edit the report.js line 187 and completely delete the check ```if (timePassed > 5) return;```
Then check the old report.

**Comment by FrutyX** [comment]
Hello there.

![enemy](https://user-images.githubusercontent.com/23278552/191843856-9d8223a0-0bef-42d0-90ef-08ac989a0a47.PNG)

**Comment by GreatApo** [comment]
> Hello there.
> 
> ![enemy](https://user-images.githubusercontent.com/23278552/191843856-9d8223a0-0bef-42d0-90ef-08ac989a0a47.PNG)

I still can't see how this error is generated... What do you get with:

```let image = document.getElementById('defenderAvatar11').getElementsByTagName('div')[2].style.backgroundImage;
let enemy = gca_tools.img.resolve(image);
if (enemy) console.log('Passed', image);
else console.error('Failed to detect enemy', image, enemy);```

**Comment by FrutyX** [comment]
![enemy2](https://user-images.githubusercontent.com/23278552/191844972-27961309-60ea-4ffe-9ec2-cc7b2cb325da.PNG)

**Comment by FrutyX** [comment]
I am only eager to see if you can solve this, because it seems even Thanos just ignored this :D.

**Comment by GreatApo** [comment]
> I am only eager to see if you can solve this, because it seems even Thanos just ignored this :D.

The error was extremally misleading :P
Test this fix (keep that check deleted and check the old log)

**Comment by FrutyX** [comment]
PATCHED!

Well done, and thank you. It seems it's gone, I hope, forever, gone, reduced to atoms. (yes I deleted the check again)

**Comment by GreatApo** [comment]
> PATCHED!
> 
> Well done, and thank you. It seems it's gone, I hope, forever, gone, reduced to atoms. (yes I deleted the check again)

This will do for now... Ultimately, instead of deleting the url("...."), I should search for the url in the parenthesis... anyway, let's close this for now.

**Comment by FrutyX** [comment]
Ah lovely, I had 3 expeditions left without UW costume, and last exp gave me a secondary material drop, no error, perfect.
