### ISSUE TITLE
Manifest v3 breaks v4.3.6

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#421]
The manifest v3 broke the addon. The current version on chrome store don't runs at all.
I am working on a fix.

**Comment by FrutyX** [comment]
Ouch, I don't even know how that happened.

**Comment by FrutyX** [comment]
I just went for a small nap, and everything went to hell 😆, this is the biggest release ever lol.

**Comment by FrutyX** [comment]
Both on dev (local) and stable (store) versions (Google Chrome):

`Error in event handler: ReferenceError: document is not defined at loadScript (chrome-extension://dfbmiedjenagoegiiabjfjpkhfocifkp/core/background.js:45:15) at needScript (chrome-extension://dfbmiedjenagoegiiabjfjpkhfocifkp/core/background.js:34:3) at actionManager (chrome-extension://dfbmiedjenagoegiiabjfjpkhfocifkp/core/background.js:67:11) at chrome-extension://dfbmiedjenagoegiiabjfjpkhfocifkp/core/background.js:80:2`

But it does not seem to stop the extension.

**Comment by FrutyX** [comment]
It's almost unbelievable how many people you have awakened by breaking the addon for a day, the forums, discord, store reviews... :D

**Comment by GramThanos** [comment]
I know... its fun to look at the statistics :P

Quiz: Can you spot when the problem happend?
GitHub:
![image](https://user-images.githubusercontent.com/14858959/190699415-be349a7e-6a06-460e-8a8f-b56c425ce5af.png)

Gladiatus Crazy Addon Website:
![image](https://user-images.githubusercontent.com/14858959/190699887-db00538d-ca88-4ac6-96ef-9e5a47cfbc1e.png)

**Comment by FrutyX** [comment]
:D :D

**Comment by FrutyX** [comment]
![Untitled Project](https://user-images.githubusercontent.com/23278552/190703255-e5416ce5-45fc-4b48-893a-a6ce1d37e9b0.gif)

**Comment by GramThanos** [comment]
Ahhhh.... the GIF-Fu is strong with this one.

**Comment by FrutyX** [comment]
@GramThanos if I select this:

![dura](https://user-images.githubusercontent.com/23278552/191759995-ad143a01-67be-4fec-afa2-0963949549d8.PNG)

I see this:

![numberrs](https://user-images.githubusercontent.com/23278552/191760020-a5e452db-cba1-4b01-abe1-a233009c08d9.PNG)

there used to be numbers, no? Is it bugged? Can you check it please?

**Comment by FrutyX** [comment]
Ahhh, I see, I forgot we have a documentation, I was never using this (using the % option) and I thought it bugged, nevermind, sorry to bother you @GramThanos :D

**Comment by GreatApo** [comment]
> Ahhh, I see, I forgot we have a documentation, I was never using this (using the % option) and I thought it bugged, nevermind, sorry to bother you @GramThanos :D

Only the color changes with that option

**Comment by FrutyX** [comment]
In it's current state, you can't load the dev version from a folder in Firefox? I've tried **manifest.json** and **manifest_v2.json** and both are throwing the same error.

```
[ACTION FAILED] TEMPORARY_EXTENSION_INSTALL_FAILURE: Unsupported manifest version: 3 [error-logging.js:16:17]

manifestVersionCheck@resource://gre/modules/Schemas.jsm:305:11 [error-logging.js:27:17]
postprocess@resource://gre/modules/Schemas.jsm:1288:59
normalize@resource://gre/modules/Schemas.jsm:2294:17
checkProperty/r<@resource://gre/modules/Schemas.jsm:2059:16
withPath@resource://gre/modules/Schemas.jsm:649:14
checkProperty@resource://gre/modules/Schemas.jsm:2058:25
normalize@resource://gre/modules/Schemas.jsm:2131:14
normalize@resource://gre/modules/Schemas.jsm:3612:23
normalize@resource://gre/modules/Schemas.jsm:3819:28
_getNormalizedManifest@resource://gre/modules/Extension.jsm:1169:25
parseManifest@resource://gre/modules/Extension.jsm:1242:33
```

It's not about me tho, I just want to prevent any future extension problems, I am not watching it closely, but it is very likely, that Thanos does some changes so it works on Firefox.

**Comment by FrutyX** [comment]
Ah, I see, I always get the idea AFTER I ask here, I renamed the **manifest_v2** to **manifest** and it works.

I only got:

`Reading manifest: Warning processing externally_connectable: An unexpected property was found in the WebExtension manifest.`

But I suppose that's nothing important.
