### ISSUE TITLE
Crazy Addon didnt work

### ISSUE THREAD

**Issue by IvarRagnarsso** [DinoDevs/GladiatusCrazyAddon#422]
**Check our Troubleshooting guide first (optional)**
Check our guide before submitting a bug issue to see if it helps, if not, continue with creating this issue.

You can find it at: 
https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/Troubleshooting.md

**Describe the bug**

**Screenshots (optional)**

**Console errors (optional)**
Check your browser's console (open with F12 / on Opera with Ctrl+Shift+J) and check it for errors (on the same page where the bug lies), they are colored red, screenshot them or copy the text from the console and paste it here. Beware, that other extensions that may affect Gladiatus (like AdBlock, uBlock etc...) do create console errors, disable them before inspecting the console.

**Browser info (optional)**
 - OS: [e.g. Windows, Linux, Mac, Android, iOS]
 - Browser [e.g. Chrome, Firefox, Opera, Edge]
 - Installed GCA version [e.g. 4.3.5]

**Comment by GreatApo** [comment]
Expect the chrome version fix to go live today or tomorrow. For more technical information see here:
https://github.com/DinoDevs/GladiatusCrazyAddon/issues/421
