### ISSUE TITLE
Market: Cancel all button rework

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#424]
When cancelling too many items (10 - 15+), it creates too many server requests in a short time and this returns an 503 server error.

![market](https://user-images.githubusercontent.com/23278552/193058823-f18a1270-9e53-4356-8286-32688b5f3527.PNG)

Without scrapping the feature, a possible solution would be to alter the script, to send those requests with a time delay between each request.

**Comment by GreatApo** [comment]
We may need to do something about this, a notification or retry the requests.

**Comment by FrutyX** [comment]
Apo, since you been around now, what would you do about this? It's one of those issues, that would be nice to deal with, if we ever release another update.

I have tried it just today, and once you cancel too many items, it just throw 503 at you, first at the console, but you can even get a 503 blank page.

We either need to slow it down, retry or limit the number that can be canceled. But I don't want you to waste too much time on this, it needs a simple change, without reworking the whole code.

**Comment by GreatApo** [comment]
I slightly modified @FrutyX 's code and just added a delay between requests. It seems to work fine (tested with 16 items).

**Comment by GramThanos** [comment]
- fixed cancel wrong item id
- fixed no wait time between requests
- added more wait time based on server response time to avoid spamming the server on high load/traffic periods
