### ISSUE TITLE
Reports List: Drops info - delay server requests

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#425]
The drops list info creates too many server requests in a short time and they can fail to load because of it, resulting into an 503 server error.

![drops2](https://user-images.githubusercontent.com/23278552/193062623-fb3c9043-0e02-48be-9c7d-d5ed4d5bab3f.PNG) 
![drops](https://user-images.githubusercontent.com/23278552/193062612-db759d72-978b-4ac9-85a6-31b01170529c.PNG)

Without scrapping the feature, a possible solution would be to alter the script, to send those requests with a time delay between each request.

**Comment by GreatApo** [comment]
I think Gameforge needs to sort their servers or shut down the game. The servers lag with no players 😂

**Comment by FrutyX** [comment]
Yeah, well, it's possible that they'll fix this in the future... we can hope they'll fix it, I don't want to punish GCA for their crap.

**Comment by GreatApo** [comment]
This doesn't cause any issues with the addon, some data are just not loaded. On the other hand, this is completely a problem due to laggy servers, thus we shouldn't do anything.
