### ISSUE TITLE
Item sell value problem

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#426]
We need to investigate this:

![index](https://user-images.githubusercontent.com/14858959/193575182-6260b2b3-a6bc-47f9-b7ce-72f2eb0221be.png)

Maybe it is nothing, or it may be a bug.

**Comment by FrutyX** [comment]
It is a bug, but it's a Gladiatus bug, turn GCA off, value will be still wrong.

**Comment by FrutyX** [comment]
https://forum.gladiatus.gameforge.com/forum/thread/10397-bug-beim-marktpreis/?postID=198226#post198226

Anyways, closing this.
