### ISSUE TITLE
Removing header buttons (Exp/Dun/Are/Cir) + Pantheon menu

### ISSUE THREAD

**Issue by Necreese** [DinoDevs/GladiatusCrazyAddon#427]
Hi,
I'm making a snowflake-account and would love a setting that removes certain buttons such as Arena and Expedition as I don't want to gain any Honour.
Also another one that would be great, when pressing Pantheon you don't go to the Questlist but Missions or Gods instead.

**Comment by FrutyX** [comment]
Hey,

just to clarify, are we talking only about the header buttons or also about the menu buttons?

Header buttons:
![header](https://user-images.githubusercontent.com/23278552/195412421-847c666f-4b46-4ec6-93cd-5a4bb8a4c64d.PNG)

**Comment by GreatApo** [comment]
I think he means those on the menu

**Comment by Necreese** [comment]
Yes, I'm talking mostly about the headers. But getting rid of it all would be great or maybe a warning  when trying to access something you don't want to access.

**Comment by FrutyX** [comment]
Removing the header button was implemented into the developer version and is currently in the testing phase.

For the menu, me personally, I don't think I want to touch it, touching the menu is technically more difficult and complicated and could also create potential GCA bugs, plus the menu is an image layout, so it has some limitations too.

For the pantheon thing, I have an idea, I may look at it later, but no promises.

**Comment by GreatApo** [comment]
> For the menu, me personally, I don't think I want to touch it, touching the menu is technically more difficult and complicated and could also create potential GCA bugs, plus the menu is an image layout, so it has some limitations too.
> 

Awesome, but since you are doing the header links, do the menu too :P

**Comment by FrutyX** [comment]
> Awesome, but since you are doing the header links, do the menu too :P

![cover3](https://user-images.githubusercontent.com/23278552/195704557-c4c352b4-7a9c-4c61-aa5b-430983df6c29.jpg)

**Comment by GreatApo** [comment]
I love your gifs 😂

**Comment by FrutyX** [comment]
Okay, I think I cracked it, however, removing stuff like that is affecting other GCA features, I can already see another error,

Mostly undefined stuff, so harmless, but still, at your own risk. Of course a solution is to disable features for some hidden buttons in the settings.

**Comment by FrutyX** [comment]
Pantheon - I have added a small expandable menu, for now, there are two empty buttons (can't be clicked), might be useful in the future.

![pantheon](https://user-images.githubusercontent.com/23278552/195722444-d1f6a122-9cf6-4936-be11-e47eed42944d.PNG)
