### ISSUE TITLE
Bug/feature: No workbench icon for 2nd character

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#43]
There is nice new feature icon for 1st character, but it's not for 2nd character which also need benching of items.

![screenshot](https://user-images.githubusercontent.com/1969119/34395962-e07c0aba-eb6d-11e7-9a39-ac5fd101c310.png)

**Comment by GreatApo** [comment]
We did that on purpose for **technical reasons**. You can only drop items form your first character because they have a secific ID. All the other character items have IDs that change if you move them to your bag. These IDs are not accepted when you make a server request for a repair.

**Comment by DarkSide666** [comment]
Wow. I didn't know that. Another implementation "pearl" of Gladiatus devs :)
