### ISSUE TITLE
Alert when HP is low when attacking enemies

### ISSUE THREAD

**Issue by 0tii** [DinoDevs/GladiatusCrazyAddon#436]
Sometimes I forget i am low on XP and do an expedition and obviously die. Same for arena, sometimes happens. Can we have a customizable alert (like let us say when health is under x%) - like a popup dialogue where we have to confirm we want to attack with low hp`?

**Comment by FrutyX** [comment]
Heya, this has been already suggested and thus this is a duplicate of #84.

I am closing this, you can continue in #84.
