### ISSUE TITLE
Lemuren - ingredients

### ISSUE THREAD

**Issue by jkamin61** [DinoDevs/GladiatusCrazyAddon#439]
Ingredients of second enemy in Dragon Remains (Germania) are not shown. As below.
![Bez tytułu](https://user-images.githubusercontent.com/107152863/201428373-7055b5f0-9feb-4041-9da9-127b03cc3057.png)

**Comment by FrutyX** [comment]
Thanks for the report, you are right, it seems to be bugged.

Now for some digging, she is `2/1_30.jpg`, she has set her drops and the cdn image link seems to be alright too.

This for example, seems to be working too:
https://s51-en.gladiatus.gameforge.com/cdn/img/npc/2/1_30.jpg

Unless I missed something, she does not appear to be any different from other npcs, but I have a screenshot, and she used to work.

**Comment by FrutyX** [comment]
I found the problem, well, GCA did, I only found it and enabled it in the code.

`gca.cdn.js?4.3.8&built=1668212086109:59 Image link "//gf1.geo.gfsrv.net/cdn93/230fc8d3268e05c79944a17ca8b58b.jpg" has duplicates. 93230fc8d3268e05c79944a17ca8b58b `
`(2) ['img/npc/0/1_36.jpg', 'img/npc/2/1_30.jpg']`

The other one is causing it, however, this is not a mistake, one enemy in "Revenge of the Dead" is using the same image, if you delete the event one, it works normally.

@GramThanos got any easy tweak in mind?

**Comment by GramThanos** [comment]
I think I pointed out the problem when I scripted the walk around for the CDN images translation. This can't be fixed as the image is the same for multiple NPCs thus by looking at the CDN URL you don't know which NPC is it.

There is no easy fix for that.

**Comment by FrutyX** [comment]
For this particular case, there actually is a workaround.

If our regular Lemuren is on the list first (before the event one), it loads the drops, so I swapped the location order in the cdn file (it's now from higher location to lower).

I have a screenshot of the event location as well, the other Lemuren did not have any drops shown, so there will be no problem with that.

![event_pomsta](https://user-images.githubusercontent.com/23278552/201465600-0b27018e-703f-4b21-b5f4-02f3e383ddc3.png)

**Comment by FrutyX** [comment]
Alright then, I did a full locations sweep, and only found that with swapping the numbers, I only created more problematic duplicates.

So I reverted it, and found out, that Lemures seems the only one problematic, so I did it just simple, I put her on top of the list, you could do that with other duplicates too, but others with drop does not seems to have problems, so there is no need.

**Comment by GreatApo** [comment]
Nice

**Comment by jkamin61** [comment]
The problem reoccurred
![image](https://user-images.githubusercontent.com/107152863/224719850-99f38799-98f8-4806-bed6-4441daeca7e0.png)

**Comment by GreatApo** [comment]
In the current dev version, this works:
![image](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/9620510/3889d3d8-53fc-4bbc-a671-1664c9ffaca7)
