### ISSUE TITLE
[Rainbows] Improving benching process

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#44]
Probably Github is not the real place to make brainstorming, but still:

Do you guys have any ideas how to make item benching easier? It takes a lot of time and effort to bench all items of your 1st and 2nd char.
- overview page: drag item from your char to your inventory
- go to workbench page
- drag item in workbench and accept benching
- check what resources you need and search for them in your inventory or packages
- drag these resources in your inventory (if they are in packages)
- go back to workbench page
- drag resources on benched item
- start benching and wait for it to finish
- drag benched item from packages to inventory
- go to overview page and drag item from inventory back to your char.

And repeat all these steps to each item of your char :(

P.S. Of course you can speed all this up a bit if you open game in multiple tabs (one for package searching, one for workbench page etc.) and then drag, switch to another tab, refresh it and drag again and so on. But still it's terrible UI to do such a simple and almost daily function.

**Comment by GramThanos** [comment]
:| No ideas from me :P

**Comment by GramThanos** [comment]
Gladiatus added a dropdown to auto add the materials need, and the forge box info of the addon now shows your materials amounts.

So, I am going to close. You can still comment if there is a problem.
