### ISSUE TITLE
Problem loading gca_resources on Firefox

### ISSUE THREAD

**Issue by amauryblin** [DinoDevs/GladiatusCrazyAddon#440]
**Describe the bug**
At least the gold and exp data cannot work on Firefox due to an error in the path while loading gca_resources.
The path seems hard-coded to look for the resources folder on chrome-extension, so on other browsers that won't work.

From the source code in [source/core/source/gca.info.js](https://github.com/DinoDevs/GladiatusCrazyAddon/blob/ff7694fad9f1c49fa96afd415cbc1cb8ef580d95/source/core/source/gca.info.js)
`var gca_resources = {
	"folder": "chrome-extension://" + gca_extension.id + "/core/resources/",
	"audio": "chrome-extension://" + gca_extension.id + "/core/resources/audio/"
};`

**Screenshots (optional)**

![2022-11-19 21_44_01-Window](https://user-images.githubusercontent.com/46691339/202871038-eb480963-6f27-410d-9308-3909875d5d74.png)

**Console errors (optional)**
(see screenshot)

**Browser info (optional)**
 - OS: Windows
 - Browser: Firefox
 - Version: 106.0.5
 - Installed GCA version: 4.3.7

**Comment by FrutyX** [comment]
Thanks for the report.

I think this might be related to manifest problems, it's probably gonna be wise, to wait for Thanos for his answer...

( This could be related, or it completely isn't https://github.com/DinoDevs/GladiatusCrazyAddon/discussions/389#discussioncomment-4151053 )

**Comment by FrutyX** [comment]
https://github.com/DinoDevs/GladiatusCrazyAddon/commit/1ba2c4ffc94b13d7be8cba69f0976b1938014557 Yeah, this is definitely related to the manifest changes:

![pub](https://user-images.githubusercontent.com/23278552/202926364-bbdbfd23-595a-4ddc-9622-d0e382962480.PNG)

... this is the public Firefox version, Firefox is using `moz-extension://`.

We have to wait for @GramThanos anyways, for the version release, so this is the first priority and then we can most likely (if no other bugs found) get a new version out, when Thanos has time, of course.

**Comment by GramThanos** [comment]
Patched at 5c062b0ba318d90adb23b2c0aff24c774d94a77e

**Comment by GramThanos** [comment]
Let's close this. On my tests, Firefox works ok.
