### ISSUE TITLE
Pact activation error

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#441]
There is a bug which causes an error when showing the list of ingredients.
Right after activating pacts (in my case it was for stats, agility and dexterity) ingredients stop showing while hover on item.

And after few days(?) the ingredients start showing again

(reported by Juliusz@Facebook)

**Comment by FrutyX** [comment]
![lglp97v9jmj61](https://user-images.githubusercontent.com/23278552/202929449-41b421d9-a952-4c24-ae42-7a3de394f60f.jpg)

**Comment by FrutyX** [comment]
Okay, so...

Activated a pact, got this:
```
global.js?4.3.8&built=1669113120524:5604

Uncaught TypeError: Cannot read properties of null (reading 'match')
    at Object.display (global.js?4.3.8&built=1669113120524:5604:57)
    at Object.init (global.js?4.3.8&built=1669113120524:5390:19)
    at Object.inject (global.js?4.3.8&built=1669113120524:268:23)
    at fireLoad (global.js?4.3.8&built=1669113120524:5920:14)
```

I remember i mentioned this somewhere, I think it was when I added the CDN images for buff icons, but I also remember that this error goes away on it's own, I don't know, more investigating is probably needed.

**Comment by FrutyX** [comment]
Assigning high priority, as this bug (activating a pact) stops many other features as well (materials included).

**Comment by GreatApo** [comment]
I potentially fixed:
- Reading the remaining time of an active pact
- Reading the remaining days as minutes after enabling a pact

@FrutyX do you know the original location of the powerup (Pacts) images?

![image](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/9620510/2f9cc85f-d230-46d5-96ba-bcc4009deae3)

I have added a way around the issue for now, but it would be good to have them in the list. I have tried the following paths without success:
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/powerups3_3.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/powerup3_3.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/rune3_3.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/runes3_3.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/3_3.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/apollo.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/powerup1.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/powerups1.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/powerups1_1.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/rune1.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/rune1_1.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/runes1.jpg
https://s51-en.gladiatus.gameforge.com/cdn/img/ui/powerups/runes1_1.jpg

I also know that when enabled, they may have "_border" in their name.

**Comment by FrutyX** [comment]
> @FrutyX 

![squidward-sleepless](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/23278552/138adf0a-b3f3-433d-8a47-f2115daaeaf2)

As much as I would like to help, I basically have no clue at this point, and right now I don't see a way how to dig them up, if someone knew something, it would be only Thanos, I suppose.
