### ISSUE TITLE
Wrong sorting order for items with negative bonus

### ISSUE THREAD

**Issue by Arctomachine** [DinoDevs/GladiatusCrazyAddon#445]
**Describe the bug**
Sorting items at auction uses absolute values. That makes items with negative bonus appear among items with positive bonus, above zero.

**Screenshots (optional)**
Here is example. This item has -1 bonus, but it appears above item with 0 bonus.
![image](https://user-images.githubusercontent.com/29041820/229371284-4a37579b-ac1c-42a2-827c-754d6f9b9163.png)

**Console errors (optional)**
No errors

**Browser info (optional)**
 - OS: Windows
 - Browser Firefox
 - Version 111
 - Installed GCA version 4.3.7

**Comment by Arctomachine** [comment]
It seems this bug only concerns sorting by damage due to specific regex used. It tries to match `number - number` on weapons and take second number, while there are also non-weapon items with `number` and `-number`.  Positive values are parsed correctly, but negative number do not take `-` into account.

**Comment by GreatApo** [comment]
Nice thanks
