### ISSUE TITLE
Suppress floating price info on double click buy/sell

### ISSUE THREAD

**Issue by Arctomachine** [DinoDevs/GladiatusCrazyAddon#447]
**Brief feature description**
Add option (or force default behavior) to suppress floating notifications with item price (i.e. +1000) on buy/sell when doing it with double click.
Why: text of this price gets in the way of other items, so double clicking them is registered as word selection instead. It becomes big obstacle when time to sell is critical.

**Add a image as an example (advanced + optional)**
![double-click](https://user-images.githubusercontent.com/29041820/230464994-e4b350b3-df88-4a5e-a555-4db3adb3345a.gif)

**Comment by FrutyX** [comment]
A rather simple implementation, pure CSS, easily changeable and fixable.

**Comment by GramThanos** [comment]
A better solution to the problem is to disable the click events on the floating prices all together using:

```
pointer-events: none;
```

We can apply that everywhere, without a need of an option.

**Comment by FrutyX** [comment]
You see, we can use both, since I already created it.

You can disable the floating prices completely (that's an unplanned new feature then), but also, it can be a part of my Gladiatus site improvements (#403).

Best from both worlds.

**Comment by GreatApo** [comment]
@FrutyX this shouldn't be by default enabled as other players may like the test.
Thanos' proposal would be better, assuming that the click even is not blocked by the floating text.

Feel free to move it to the global script so it doesn't have to be added in every other script.

**Comment by FrutyX** [comment]
You know what, I am not gonna touch this any further.

**Comment by GreatApo** [comment]
> pointer-events: none;

My bad, I see you have already changed to Thanos' proposal...
