### ISSUE TITLE
[Feature Request] Add warning message if you items benching goes low

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#45]
It would be great to have some warning message pop up (like we have one for smelting now) in case your 1st or 2nd character items benching goes below some predefined level.

To make it less resource heavy it could check items once in hour of once in 15 minutes or so and not on each page refresh.

Tricky part - what to do when you remove item from char or put new item on. I guess then we should simply have forced checking (not wait next 15 minutes).

**Comment by GreatApo** [comment]
If you take a look at the features you will see somewhere saying "display durability on items"/"display average durability", there can also be a notification. On the other hand, i don't think there should be a refresh request to the server since you constantly visite overview, dungeon players will have to face the consequences :P

**Comment by DarkSide666** [comment]
yes, no automatic refresh from server needed. It's ok to just refresh that every now and then when you visit overview page.
But don't forget that player have 2 chars which looses durability. It's not just main char.

**Comment by GreatApo** [comment]
We made this: (can also show a colored icon, default disabled)
![image](https://user-images.githubusercontent.com/9620510/34505102-9e814ffe-f02b-11e7-8a18-83a7dd062177.png)

Do we still need a warning?

Comit 3ecb26d883724b754190d6d4487011910bbed6d3

**Comment by DarkSide666** [comment]
Notification would be better, but ... I will ask my guildmates to participate and comment here too. Maybe it's just lazy me :)

**Comment by GramThanos** [comment]
Its really easy just to add a notification, but onpy when you visit the page of your player.

**Comment by DarkSide666** [comment]
Yeah i guess such message should be enough. Overview page is often visited and benching is not changing very fast.
Only question is - how to set threshold for such message?

**Comment by GreatApo** [comment]
So:
The code already loops through your items (in the page you visite) and adds data-durability attributes on them (CSS handles all the others). We will add a notification under a specified durability.

Should there be a limit? We could save the item's ID when a notification is displayed, that ID changes when you pack the item (i suppose it changes when you repair them too).

**Comment by DarkSide666** [comment]
Only need alert for items you wear. Benching doesn't matter for items you have in your backpack or anywhere else.
It's also not that important if there is one big or many small alerts. Important is to draw players attention and say something like "hey man, check out durability of your items - it's going very low!!!"

By threshold I mean - what's the condition when alert is shown?
Like:
```
durability < 100% OR conditioning < 10%
```

**Comment by GreatApo** [comment]
Oh, i already made that ^_^
![image](https://user-images.githubusercontent.com/9620510/34608879-251b7078-f223-11e7-89e4-bdf31fba5f7a.png)
It's between 0 and 200 (total/combined with the durability over 100%)

**Comment by DarkSide666** [comment]
So 125% means durability 100% + conditioning 25% ?

**Comment by GreatApo** [comment]
Yes ^_^

**Comment by DarkSide666** [comment]
Then I am satisfied 💯

**Comment by GreatApo** [comment]
Comit 36625214879cf68a089198e810ff7f254847737e 
- Show durability and notifications now work separete
- Setting % to 0 will close the notification feature

Everything seems to work, i am closing this request.
