### ISSUE TITLE
Add tooltip or notification about training increment with ctrl

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#452]
Somehow inform the users that by pressing CTRL the training increment buttons change by 10 instead of 1. (#450)

**Comment by jrel** [comment]
CTRL doesn't work on Mac. We can use `e.metaKey` to check if the command key is pressed, but meta is the window key in Windows.
We can add a filter to check if the user uses a Mac.
```ts
var isMac = navigator.platform.toUpperCase().indexOf('MAC')>=0;
```

But I think it is easier to switch to the shift key and use `e-shiftKey`.
