### ISSUE TITLE
Missing translation for (Slovak) (sk)

### ISSUE THREAD

**Issue by mafianko548** [DinoDevs/GladiatusCrazyAddon#457]
**VolFinKo**
 - Language: (Slovak)

/*
	Missing translations for Slovenský (Slovak) (sk)
	Add these values in the existing file or
	translate them and send them at:
	https://github.com/DinoDevs/GladiatusCrazyAddon/issues/new?template=translation.md
*/

general : {
	hours : "hodiny",
	yes : "Ano",
	no : "Nie",
	ok : "OK"
}
global : {
	expedition_recover_full : "Plne obnovenie expedicnych bodov",
	dungeon_recover_full : "Plne obnovenie zalarovych bodov",
	guild_baths_goto : "Chod do kupelov (Vox I)",
	guild_arenareports_goto : "Prejdi do reportov subojov spolku",
	guild_templum_goto : "Prejdi do spolkoveho templum",
	auction_food_goto : "Prejdi na aukcie jedla",
	notification_guild_attack_ready : "Casove obmedzenie na spolkovy utok vyprsalo!",
	item_worth_rubies : "Ten predmet je bezcenny",
	gold_exp_data_reset : "Statistiky vynulovane",
	gold_exp_data_desc : "Data su zbierane kazdych 5 minut. Predavanie itemov ktore si kupil ti zdvojnasobi zisk",
	mercenary_type : "Typ: {{meno}} ({{cislo}})",
	gains_with_full_stats : "Zisky s plnymi statmi:",
	base : "Zakladna",
	prefix : "Pred menom",
	suffix : "Za menom"
}
overview : {
	more_player_info : "Viac udajov o hracovi",
	can_use_max_item_level : "Moze pouzivat predmety do {{max}} urovne.",
	can_see_market_max_item_level : "Moze vidiet predmety do {{max}} urovne.",
	can_see_auction_item_levels : "Moze vidiet predmety na aukcii od {{min}} do {{max}} urovne."
}
guild : {
	total_donations : "Prispevky dokopy",
	min_upgrades_gold : "Zlato pouzite na vylepsenia (minimum)",
	max_stolen_gold : "Ukradnute zlato od inych spolkov (maximum)",
	pinned_message : "Pripnuta spolkova sprava",
	pin_unpin_message : "Pripni/zmaz tuto spravu",
	pinned_message_info : "Pripnute spravy su zobrazene na vrchu sprav pre vsetkych clenov spolku pouzitim tejto funkcie",
	important_ranks : "Dolezite rebricky"
}
arena : {
	/* ALL TRANSLATIONS IN THIS SECTION ARE MISSING, copy them from en.js */
} 
training : {
	points_breakdown_damage : "Utrpel: +{{integer}} (+{{float}})",
	points_breakdown_block : "Zablokovane: +{{integer}}% (+{{float}}%)",
	points_breakdown_block_max : "Zablokovane: maximum value",
	points_breakdown_block_short : "Zablokovane: +{{integer}}%",
	points_breakdown_normal_hit : "Sanca na uder: +{{integer}}% (+{{float}}‰) *",
	points_breakdown_critical_hit : "Sanca na kriticky uder: +{{integer}}% (+{{float}}‰)",
	points_breakdown_critical_hit_short : "Kriticky uder: +{{integer}}%",
	points_breakdown_double_hit : "Sanca na dvojity uder: +{{integer}}% (+{{float}}‰) *",
	points_breakdown_double_hit_factor : "Faktor dvojiteho uderu: {{number}}",
	points_breakdown_avoid_double_hit_factor : "Vyhnut sa faktoru dvojiteho uderu: {{number}}",
	points_breakdown_avoid : "Vyhnut sa sanci na kriticky uder: +{{integer}}% (+{{float}}‰)",
	points_breakdown_avoid_max : "Vyhnut sa sanci na kriticky uder: maximum value",
	points_breakdown_avoid_short : "Vyhnut sa kritickemu uderu: +{{integer}}%",
	points_breakdown_enemy_normal_hit : "Superova sanca na zasiahnutie: {{integer}}% ({{float}}‰) *",
	points_breakdown_enemy_double_hit : "Superova sanca na dvojity uder: {{integer}}% ({{float}}‰) *",
	points_breakdown_life : "Body zivota: +{{number}}",
	points_breakdown_regeneration : "Regeneracia za hodinu: +{{number}}",
	points_breakdown_threat : "Ohrozenie: +{{integer}} (+{{float}})",
	points_breakdown_heal : "Liecenie: +{{integer}} (+{{float}})",
	points_breakdown_critical_heal : "Kriticke liecenie: +{{integer}}% (+{{float}}‰)",
	points_breakdown_critical_heal_max : "Kriticke liecenie: maximum value",
	values_in_parenthesis_explanation : "Values inside parentheses shows the corresponding values before rounding."
}
auction : {
	sort : "Zoradit",
	sort_by : "Zoradit podla",
	sort_order : "Poradia",
	asc : "Vzostupne",
	desc : "Zostupne"
}
markets : {
	item_cant_buy_back : "Nebudes moct kupit tento predmet spät.",
	click_enter_to_sell : "Stlac enter   pre predanie",
	add_fees_in_price : "Pridane poplatky v cene"
}
forge : {
	show_hide_doll : "Zobrazit/skryt dolls",
	horreum_material_change : "Horreum materialy na vymenu"
}
merchants : {
	/* ALL TRANSLATIONS IN THIS SECTION ARE MISSING, copy them from en.js */
} 
packages : {
	advance_filters : "Rozsirenie filtrovanie",
	advance_filters_apply : "Potvrd filtrovanie",
	advance_filters_clear : "Zmaz filtrovanie",
	advance_filters_found : "(najdene {{items}})"
}
reports : {
	/* ALL TRANSLATIONS IN THIS SECTION ARE MISSING, copy them from en.js */
} 
sync : {
	/* ALL TRANSLATIONS IN THIS SECTION ARE MISSING, copy them from en.js */
} 
settings : {
	category_accessibility : "Pristupnost",
	category_global$expedition_dungeon_points_recover_timer : "Zobraz minuty ktore chybaju do obnovy expedicnych/zalarovych bodov",
	category_global$check_guild_pinned_message : "Zobraz pripnute spolkove spravy z kupelov",
	category_global$check_guild_application_pinned_messages_interval : "Skontroluj spolkove aktivity a pripnute spravy kazdych (minutes)",
	category_global$notify_guild_attack_ready : "Upozorni ma, ked vyprsi odpocet na novy spolkovy utok",
	category_global$notify_guild_attack_ready_interval : "Skontroluj odpocet na spolkovy utok kazdych (minutes)",
	category_global$show_forge_info : "Zobraz materialy pre item na nastrojovej liste",
        category_global$show_mercenaries_real_name_and_combat_stats : "Zobraz realne mena otrokov (type) a statistiky z utoku na nastrojovej liste",
	category_global$show_upgrade_values : "Zobraz zvysene hodnoty na posilneniach & vylepseniach",
	category_global$global_arena_timer : "Zobraz casovac Globalnej areny",
	category_global$gladiatus_site_fixes : "Oprav a vylepsi chyby stranky Gladiatus",
	category_global$lock_section_visibility : "Uzamkni aktualny stav skryvatelnych sekcii",
	category_global$hide_language_flags : "Skry jazykove vlajky pod hracovymi menami",
	category_overview$double_click_consume : "Dvojity klik pre skonzumovanie predmetu",
	category_packages$small_items_layout : "Mensie zobrazenie predmetov",
	category_packages$list_view_layout : "Zobraz baliky ako prehlad v liste",
	category_packages$double_click_open : "Dvojity klik pre otvorenie pakiet",
	category_packages$advance_filter : "Rozsirene filtrovanie balikov",
	category_packages$pop_over_bag : "Pop bag over on scroll",
	category_packages$packages_shortcuts : "Pridaj kategoriu predmetu medzi skratky",
	category_pantheon$show_mysterybox_rewards_owned : "Ukaz mystery-box ciastku z odmien",
	category_reports$battle_analyzer : "Analyzuj hlasenia a ukaz zivotne statistiky",
	category_merchants$ruby_icon_on_items : "Pridaj ikonu na predmety ktore stoja rubiny",
	category_merchants$show_shop_info : "Ukaz informacie o obchode (celkova cena a rubiny)",
	category_merchants$double_click_actions : "Dvojity klik pre predanie/nakup predmetov",
	category_forge$horreum_materials_names : "[Horreum] Ukaz meno materialu",
	category_forge$horreum_remember_options : "[Horreum] Zapamätaj posledne zvolene nastavenia",
	category_forge$horreum_select_meterials : "[Horreum] Zvol material klikom",
	category_arena$sort_by_lvl : "Zorad hracov v arene podla urovne",
	category_arena$highlight_guild_members : "Vyznac hracov na druhych serveroch, ktori by mohli byt clenom spolku",
	category_arena$target_list : "Zoznam zazobanych hracov",
	category_market$add_fees_button : "Ukaz [+] tlacitko, ktore zahrna poplatky v predajnej cene",
	category_market$custom_prices : "Volitelne ceny na trhu, oddelene ciarkami. Vypocitaj zaklad na percentach ceny predmetu pridanim '%'. (napr., '10000, 10.000, 200%')",
	category_market$double_click_select : "Zvol predmet dvojitym klikom",
	category_market$sell_warning_icons : "Ikona upozornenia pri predavani predmetov",
	category_market$sell_with_enter : "Predaj predmety stlacenim ENTER ⏎",
	category_guild$bank_book_show_changes : "Ukaz pridane prispevky od poslednej navstevy bankovej knihy",
	category_auction$item_name : "Ukaz meno predmetu",
	category_auction$save_last_state : "Zabudovane ulozenie vyhladavania aukcie a nacitaj to bez neho",
	category_accessibility$white_level_indicators : "Zmen level indikatora cisla na predmete na bielo",
	category_accessibility$qualty_symbols_indicators : "Pridaj symbol kvality na indikator predmetov",
	category_accessibility$tooltips_qualty_white : "Zmen nazov predmetu v nastrojovej liste na bielo",
	category_accessibility$tooltips_qualty_symbols : "Pridaj symboly kvality na nastrojovu listu",
	category_data$export_settings_to_notes : "Exportuj nastavenia do poznamok",
	category_data$import_settings_from_notes : "Importuj nastavenia z poznamok",
	category_data$clear_cache_data : "Vycisti docasne subory addon-u (cache)",
	category_data$cross_browser_login : "Prepojenie internetovych vyhladavacov",
	category_data$export_error_player_settings : "Exportuj uzivatelove nezname data do suboru",
	show_info : "Zobraz informacie",
	each_category : "Spusti na vybranej kategorii",
	all_category : "Spusti na vybranej kategorii & vsetkych",
	do_not_run : "Nespustaj",
	default : "Predvolene",
	data_exported_save_the_file : "Data boli exporotvane. Uloz subor.",
	missing_translations : "Chybajuce preklady"
}

**Comment by GreatApo** [comment]
Thanks!
