### ISSUE TITLE
Missing translations for Magyar (Hungarian) (hu)

### ISSUE THREAD

**Issue by Gabooor** [DinoDevs/GladiatusCrazyAddon#458]
uploaded by Gabooor

/*
	Missing translations for Magyar (Hungarian) (hu)
	Add these values in the existing file or
	translate them and send them at:
	https://github.com/DinoDevs/GladiatusCrazyAddon/issues/new?template=translation.md
*/

global : {
	guild_baths_goto : "Ugrás a Vox Logusba",
	auction_food_goto : "Ugrás az élelmiszer aukciókhoz",
	gold_exp_data_reset : "A statisztikák nullázódtak!",
	gold_exp_data_desc : "Az adatok 5 percenként kerülnek mentésre. Ha vásárolsz egy tárgyat és újra eladod, az mégegyszer felszámolódik.",
	gains_with_full_stats : "Maximális statisztikákkal járó értékek:",
	base : "Base",
	prefix : "Prefix",
	suffix : "Suffix"
}
guild : {
	total_donations : "Összes adomány",
	min_upgrades_gold : "Fejlesztésekre elköltött arany (minimum)",
	max_stolen_gold : "Más egyesületektől rabolt arany (maximum)",
	pinned_message : "Rögzített egyesületi üzenet",
	pin_unpin_message : "Üzenet rögzítése / rögzítés törlése",
	pinned_message_info : "A rögzített üzenetek mindenki számára az üzenetek tetején lesz látható",
	important_ranks : "Fontos rangok"
}
training : {
	points_breakdown_damage : "Sebzés: +{{integer}} (+{{float}})",
	points_breakdown_block : "Blokkolás: +{{integer}}% (+{{float}}%)",
	points_breakdown_block_max : "Blokkolás: maximum érték",
	points_breakdown_block_short : "Blokkolás: +{{integer}}%",
	points_breakdown_normal_hit : "Esély a találatra: +{{integer}}% (+{{float}}‰) *",
	points_breakdown_critical_hit : "Esély a kritikus találatra: +{{integer}}% (+{{float}}‰)",
	points_breakdown_critical_hit_short : "Kritikus találat: +{{integer}}%",
	points_breakdown_double_hit : "Dupla találat: +{{integer}}% (+{{float}}‰) *",
	points_breakdown_double_hit_factor : "Dupla találati faktor: {{number}}",
	points_breakdown_avoid_double_hit_factor : "Dupla találat elkerülési faktor: {{number}}",
	points_breakdown_avoid : "Kritikus találat elkerülésének esélye: +{{integer}}% (+{{float}}‰)",
	points_breakdown_avoid_max : "Kritikus találat elkerülésének esélye: maximum érték",
	points_breakdown_avoid_short : "Kritikus találat elkerülésének esélye: +{{integer}}%",
	points_breakdown_enemy_normal_hit : "Ellenfél találatának esélye: {{integer}}% ({{float}}‰) *",
	points_breakdown_enemy_double_hit : "Ellenfél dupla találatának esélye: {{integer}}% ({{float}}‰) *",
	points_breakdown_life : "Életerő: +{{number}}",
	points_breakdown_regeneration : "Regeneráció óránként: +{{number}}",
	points_breakdown_threat : "Veszély: +{{integer}} (+{{float}})",
	points_breakdown_heal : "Gyógyítás: +{{integer}} (+{{float}})",
	points_breakdown_critical_heal : "Kritikus gyógyítás: +{{integer}}% (+{{float}}‰)",
	points_breakdown_critical_heal_max : "Kritikus gyógyítás: maximum érték",
	values_in_parenthesis_explanation : "A zárójelekben található érték a kerekítés előtti értéket mutatja."
}
markets : {
	add_fees_in_price : "Piaci díj hozzáadása az árhoz"
}
forge : {
	horreum_material_change : "Csűr nyersanyag változás"
}
settings : {
	category_accessibility : "Megjelenítés",
	category_global$check_guild_pinned_message : "Show guild pinned messages from the baths in messages",
	category_global$check_guild_application_pinned_messages_interval : "Check for guild applications and pinned messages every (minutes)",
	category_global$show_mercenaries_real_name_and_combat_stats : "Display mercenaries real names (type) and combat stats on tooltips",
	category_global$show_upgrade_values : "Display buff values on reinforcements & upgrades",
	category_global$gladiatus_site_fixes : "Fix and improve Gladiatus site style problems",
	category_global$lock_section_visibility : "Lock the current state of hideable sections",
	category_global$hide_language_flags : "Hide language flags under player names",
	category_packages$list_view_layout : "Show packages as a list view",
	category_packages$pop_over_bag : "Pop bag over on scroll",
	category_packages$packages_shortcuts : "Add item category shortcuts",
	category_merchants$ruby_icon_on_items : "Ikon hozzáadása azokhoz a tárgyakhoz amik rubinba kerülnek",
	category_market$add_fees_button : "[+] gomb mutatása, amivel hozzáadhatjuk a piaci díjat az árhoz",
	category_market$custom_prices : "Custom market prices, separated with commas. Calculate base on percentage of the item's price by adding an '%'. (e.g., '10000, 10.000, 200%')",
	category_auction$item_name : "Tárgyak nevének mutatása",
	category_accessibility$white_level_indicators : "Tárgy szintek jelzése fehér színnel",
	category_accessibility$qualty_symbols_indicators : "Tárgyak minőségét jelző szimbólumok mutatása",
	category_accessibility$tooltips_qualty_white : "Tárgyak nevének megjelenítése fehér színnel (tárgy információját mutató kis ablakban)",
	category_accessibility$tooltips_qualty_symbols : "Tárgyak minőgését jelző szimbólumok mutatása (tárgy információját mutató kis ablakban)",
	category_data$export_settings_to_notes : "Beállítások exportálása a feljegyzésekhez",
	category_data$import_settings_from_notes : "Beállítások importálása a feljegyzésekből",
	default : "Default"
}

**Comment by Gabooor** [comment]
Also in the packages menu where there's the special sorting option, at "Apply filters" it says "Szűrők elogadása", which is misspelled. It should be "Szűrők elfogadása" with an f in there.

**Comment by GreatApo** [comment]
Thanks!
