### ISSUE TITLE
Gladiatus Tools

### ISSUE THREAD

**Issue by DoonFreak** [DinoDevs/GladiatusCrazyAddon#459]
Good Morning,

I know you are not the right persons, but are you in contact with the https://en.gladiatus-tools.com developers? 
The page is down since a few weeks and the gladiatus players miss the page.

I hope you can help with this issue. 
Thank you very much.

greetings
DoonFreak

**Comment by GramThanos** [comment]
Hey there,

No, we haven't talked with [Michalus](https://forum.gladiatus.gameforge.com/user/69-michalus/) for a while.

We just hope he is well.

**Comment by DoonFreak** [comment]
ok thanks for you reply. I hope the same.
