### ISSUE TITLE
Cancel All Button Market

### ISSUE THREAD

**Issue by DoonFreak** [DinoDevs/GladiatusCrazyAddon#462]
Hello together,

if I have more than 20 Items in the guild market and I use the cancel all button, there is a error massage and some Items are still in the guild market left.

![Screenshot_1](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/34883943/ed1580e8-1f51-430d-9ec9-1ddd0ad6a9d2)
![Screenshot_2](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/34883943/c56a1d09-3587-4f42-964f-a7278e36a201)

**Browser info (optional)**
 - OS: Windows 11
 - Browser Chrome
 - Version 120.0.6099.129
 - Installed GCA version 4.3.7

**Comment by FrutyX** [comment]
Hey,

this problem is known, it was already reported by me in #424.

**Comment by DoonFreak** [comment]
oh, you are right. Thanks for that.
