### ISSUE TITLE
Integrating arena simulator into GCA

### ISSUE THREAD

**Issue by czapito** [DinoDevs/GladiatusCrazyAddon#463]
I would like to suggest integrating arena simulator somehow into the arena list. For example it would be nice if we could click a button and simulate fights straight from arena tab. Or display percentage win chance next to opponent. Same could be done for expeditions.

**Comment by GramThanos** [comment]
We can't do that.
In the past, the simulator was integrated with the addon and Gameforge asked us to remove it.
