### ISSUE TITLE
Global arena does not work

### ISSUE THREAD

**Issue by CLoretelli** [DinoDevs/GladiatusCrazyAddon#464]
It fails to load the list of enemyes in the global arena, saying that something is blocking the GCA server.
I do not use firewalls and I have labelled gladiatus.dinodevs.com as a safe site, but it still does not work.
Consol report attached

**Browser info (optional)**
 - OS: Mac Monterey
 - Browser Chrome
 - Version 121.0.6167.139
 - Installed GCA version 4.3.7
<img width="527" alt="Schermata 2024-02-01 alle 02 21 21" src="https://github.com/DinoDevs/GladiatusCrazyAddon/assets/29376760/a3386c1e-e716-48f1-93a8-31a1dc7df8f2">

**Comment by GreatApo** [comment]
Last week, after around 13 years, the server crashed and became corrupted. We are in the process of restoring some or all of it.

**Comment by GreatApo** [comment]
Thanos had almost everything up and running again.

**Comment by CLoretelli** [comment]
Thanks a lot

**Comment by GramThanos** [comment]
> Thanos had almost everything up and running again.

Almost? :P
