### ISSUE TITLE
Battle simulator down

### ISSUE THREAD

**Issue by Tasari** [DinoDevs/GladiatusCrazyAddon#468]
Hello, i have tried looking for your email, but failed, so I will post the issue here, the battle simulator seems to be down, it is "out of bananas" for a few days now, would be really glad if you took a look at it :)

**Comment by GramThanos** [comment]
We are experiencing problems with our servers and many GCA services (such as the simulator) are affected.

**Comment by Ondraczz3** [comment]
it never really worked anyway, it's useless

**Comment by GramThanos** [comment]
> it never really worked anyway, it's useless

Thank you for your helpful comment.

**Comment by FrutyX** [comment]
> it never really worked anyway, it's useless

Thank you for your opinion. But this is where it ends, it's your opinion.

**Comment by GramThanos** [comment]
The simulator website was moved to a new server.
I should now work without a problem.
