### ISSUE TITLE
update

### ISSUE THREAD

**Issue by Ondraczz3** [DinoDevs/GladiatusCrazyAddon#469]
when will the update be

**Comment by Ondraczz3** [comment]
GladiatusCrazyAddon Gladiatus would not be playable without this addon

**Comment by Ondraczz3** [comment]
GladiatusCrazyAddon Gladiatus would not be playable without this addon

**Comment by Ondraczz3** [comment]
Last updated on September 16, 2022
                                                    2024

**Comment by GramThanos** [comment]
> GladiatusCrazyAddon Gladiatus would not be playable without this addon

Maybe it is time to ask the developers for changes.

**Comment by GreatApo** [comment]
Unfortunately, we are not actively developing GCA anymore, so there is currently no timeline for an update.
