### ISSUE TITLE
[Feature Request] Collect gold packages

### ISSUE THREAD

**Issue by Schnurzeldurzel** [DinoDevs/GladiatusCrazyAddon#47]
At first, great work with the new version!
I have an recommendation for a comming up version. In the past it was possible to sell all gold packages or gold packages from current inventory site. That was an very helpful feature. Is it possible to implement it?

**Comment by GreatApo** [comment]
Take a look here: https://github.com/DinoDevs/GladiatusCrazyAddon/issues/42#issuecomment-354134894
However, we will look into this :)
