### ISSUE TITLE
Workbench - error when claiming item

### ISSUE THREAD

**Issue by Ondraczz3** [DinoDevs/GladiatusCrazyAddon#472]
https://github.com/DinoDevs/GladiatusCrazyAddon/assets/165718681/345db47e-0499-4cc8-9950-a0c669702047

**Comment by Ondraczz3** [comment]
https://github.com/DinoDevs/GladiatusCrazyAddon/assets/165718681/a453af76-bc43-4b50-8c43-247a42312715

**Comment by FrutyX** [comment]
See? That was actually helpful. I did a check, and yes, it seems the workbench returns an error when trying to claim the item, however, it's not that hot, because it's just a warning message, the item seems to be delivered anyway.

**Comment by CLoretelli** [comment]
Same problem here.
i confirm the item is not wasted, but this function was very helpful.
Added here a screenshot of the console if this can help
<img width="550" alt="Schermata 2024-09-05 alle 00 24 00" src="https://github.com/user-attachments/assets/8ccf53cf-0e77-442b-99d1-c4064cf69968">
