### ISSUE TITLE
New version - translation

### ISSUE THREAD

**Issue by Weakus** [DinoDevs/GladiatusCrazyAddon#473]
There is a Polish translation in the repo, but it is not added to the extension? Why?

**Comment by FrutyX** [comment]
Are you sure?

![polish](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/23278552/cd75fdd1-adbd-43d0-b165-a81d409ac9c3)

**Comment by FrutyX** [comment]
Oh, it's about that, nevermind me then.
