### ISSUE TITLE
Show forging resources in the tooltip not working

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#475]
The option "Show forging resources of items in the tooltip" may not be working for some players.
![image](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/9620510/d63ad2e4-2c10-40d7-bb2f-67b6e1ef53d9)

Reported by SPOTTER on the [forum](https://forum.gladiatus.gameforge.com/forum/thread/263-gladiatus-crazy-add-on/?postID=207304#post207304).

**Comment by GramThanos** [comment]
Ask which browser, the mode with the number of materials needs to talk with the addon's background page system.

**Comment by GramThanos** [comment]
Firefox seems to work. We need more info on this, otherwise we will have to close it.

**Comment by FrutyX** [comment]
> > Firefox seems to work. We need more info on this, otherwise we will have to close it.
> 
> The guy was offering more information on non English, and a moderator went ahead and completely deleted his comments...

Don't even mention it, I was pretty pissed, he could have at least kept his comments...

**Comment by FrutyX** [comment]
Now you can close this, Thanos.

I asked again, he cleared his GCA data and the issue got resolved:
https://forum.gladiatus.gameforge.com/forum/thread/263-gladiatus-crazy-add-on/?postID=207340#post207340
