### ISSUE TITLE
GCA randomly dropping out

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#477]
Continuing from https://github.com/DinoDevs/GladiatusCrazyAddon/commit/9985d83adda057292bf156799d03fa2591ef78a8 comments (contains a vid).

This is still happening, very randomly, sometimes most of the features dont get loaded, fixes itself on next page load.

The tricky part is, there is no error, never was, but what I have noticed, it always happens when there is this double fetch:

![fetch](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/23278552/53f41c9c-5de8-40ff-bb41-2644e6b87bdf)

I am using our GitHub beta version (latest commit) and Google Chrome v126, tried the usual troubleshooting steps, did not help.

**Comment by GramThanos** [comment]
These requests are related to the `detectPlayerId`. Do you get this request a lot?

**Comment by FrutyX** [comment]
Hard to specify, it's rather random, sometimes I get it more, sometimes not at all (that's why I was thinking if it's dependant on Gladiatus response).

I only know that when it double fetches, it basically stops GCA.

**Comment by GramThanos** [comment]
Yes, there are 2 problems here.

1) why this function is executed (this should be a fall back mechanic happening at most 1 time per session).

2) why after the fall back mechanic kicks the problem keeps appearing

**Comment by FrutyX** [comment]
Don't ask me, you are the smart one here.

No, seriously, I was unable to find a pattern in this, but since I can reproduce this time to time, if I can help in any way, just give me instructions.


https://github.com/DinoDevs/GladiatusCrazyAddon/assets/23278552/1ccd4947-732a-4890-835b-1e4a5f9998b2

**Comment by GramThanos** [comment]
Check if this will reproduce the problem:

Run this in the console:
```javascript
document.cookie = "Gca_" + gca_section.country + "_" + gca_section.server + "=0; path=/";
```
This will clear the player ID.

Then reload the page, this will most probably kick the request you are seeing.

**Comment by FrutyX** [comment]
Uhh, it did nothing, added to the console and refreshed the page.

![gc](https://github.com/DinoDevs/GladiatusCrazyAddon/assets/23278552/f8b4443f-5278-4b1e-a324-0896daa4ee24)

**Comment by GramThanos** [comment]
Try now, I made some changes.

**Comment by FrutyX** [comment]
Damn, when you have the time, you work fast.

So far it did not occured, tho it was very random before, so hard to tell. Time will tell then, imma keep randomly testing this during the day, but so far it seems to be gone.

Nice work, thank you.
