### ISSUE TITLE
Negative Gold Amount in Auction

### ISSUE THREAD

**Issue by brunoaugusto** [DinoDevs/GladiatusCrazyAddon#48]
The issue appeared when I had two tabs opened, Auction and Arena. I didn't have the cash to bid on something I wanted so I attacked someone and, without reloading the Auction page, I made my bid through this precious gem of bidding without refreshing.

Because I had a smaller amount before bidding when the addon updated the Gold amount in both top fixed bar and regular game placeholder, the result was a negative number.

I didn't look at the code but at the very least I assume an AJAX request is being performed. It would be nice to parse the native game results instead of computing the new value, at least the first time an item is bid or once every X minutes, to consider Expe-dungeons/Arenas cooldowns.

For the future, maybe even adding this as a configurable option, informing that without this negative numbers might appear.

**Comment by GreatApo** [comment]
Yeah I knew that can be improved :p
I don't remember the code exactly but I think it's even easier. When you bid the item there is a server reply, we check if the item was bidden there. We can also check the gold.

The only problem is the asynchronous of the bids with the multy-bid feature. Let's say you bid almost instantly 2-3 items, you get 3 server replies but you do not know which gold value is the current (if you take the minimum, the concept of opening a new tab will be invalid again). Of course requests are not instant but the server replies vary in time...
Anyway, maybe we can also keep track of the time from a timer in the reply content (but i think milliseconds are missing from the server timer :p).

I will look into it :)

**Comment by GreatApo** [comment]
Done! Comit fe51128e3e72700037387299d87e23642f1b0f2d
