### ISSUE TITLE
Cancel All button don't work if you only have 1 item in market

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#52]
Cancel All button don't work if you only have 1 item in market.

**Comment by GramThanos** [comment]
I can't reproduce this problem.
It works for me.

**Comment by GramThanos** [comment]
The bug apper if there is only one item in the market.

Fixed.
Commit de590e5b1613ade223e5f219b76ae5e2ef13b0e3
