### ISSUE TITLE
chat problem bug

### ISSUE THREAD

**Issue by Pusty253** [DinoDevs/GladiatusCrazyAddon#54]
Hi i have problem with chat when i use him in game i cant open markets / aucion etc .... only expeditions and dungeons work good . If you can check this problem i suggested check "main.php" when chat is On and "index.php" when he is off and all work good in adres link this can be fix this problem . I will wait for your answer thx .

**Comment by GramThanos** [comment]
We will check it.

**Comment by GramThanos** [comment]
If you temporary disable the "Remember merchants tabs" there will be no problem.
I am working on a fix.

**Comment by GramThanos** [comment]
Fixed bugs on chat page.
Commit 07afeea0b30bfa72025f8f57b717827dbede5dfd
