### ISSUE TITLE
Shadow missing Expedition

### ISSUE THREAD

**Issue by DoonFreak** [DinoDevs/GladiatusCrazyAddon#56]
the coloured shadow is missing at the secundary drop at the expedition.

http://prntscr.com/hv1a45

**Comment by GreatApo** [comment]
They load for me... Sometimes the shadows do not load (very rare). Please re-visite the report and tell use if it has shadow. There may be a bug when you see the report after the attack redirect?

**Comment by DoonFreak** [comment]
I see the shadow if I have a look at the report after the attack. It is only at the moment of the attack.

**Comment by GramThanos** [comment]
Ok, now it make sense. :)
We will debug it.

**Comment by GreatApo** [comment]
I think i found the problem.

Commit bbbf7503853cd23e5126fa2ea833c1c8c6548467
