### ISSUE TITLE
[Feature Request] Default market sort option

### ISSUE THREAD

**Issue by DoonFreak** [DinoDevs/GladiatusCrazyAddon#57]
If I open the gulid market, there is no sortation of the items. Is it possible to implement the sortation by value?

For example our guild market:
http://prntscr.com/hv1wrp

**Comment by GreatApo** [comment]
I don't understand... why don't you click on "Market price" at the top of the list? The items will be sort by price...

**Comment by DoonFreak** [comment]
thank you Apo. I know this, but I will save this click.

**Comment by GreatApo** [comment]
Oh, ok. Well, this is a little tricky. We will have to change the links (menu and buttons) leading the market pages, based on your last sorting...

Change links when on:
- Menu
- Guild buildings preview
- Shortcut bar
Save sort when on:
- Market

PS: This can also be done for Auction

**Comment by GramThanos** [comment]
@GreatApo we have the main functionality implemented for the remember tabs feature. I think it can be easily added.

**Comment by GramThanos** [comment]
Need feedback for the "remeber market sort".

**Comment by GreatApo** [comment]
It works for me. Lets improve it a little more:
Sort links have ▼ icons, change them to ▷ when they are not sorted and to ▲ ▼ based on the sort.
Also, rename settings option to "Improve and remember sort order".

**Comment by GreatApo** [comment]
Ready comit d5579841c63a5d45f1fab320bfe2a39fbed3ca60
