### ISSUE TITLE
Version [v4.0.2]

### ISSUE THREAD

**Issue by mim1985** [DinoDevs/GladiatusCrazyAddon#58]
Hi. In change log i found this: [v4.0.2] (28/12/2017) 
But in  downloads last version is 4.0.0

What i miss?

**Comment by GramThanos** [comment]
Left on copy paste... :P
Version v4.0.2 is under development.

**Comment by GreatApo** [comment]
We where going to make a release and then we desided to fix and improve some more things and i forgot to delete the changelog :P

**Comment by mim1985** [comment]
ok...:)))
