### ISSUE TITLE
New version window

### ISSUE THREAD

**Issue by GreatApo** [DinoDevs/GladiatusCrazyAddon#66]
Window showing new version's changelog

**Comment by brunoaugusto** [comment]
If this window is an indication that the extension has updated itself, it could include a link to the latest changelog.

**Comment by FrutyX** [comment]
Putting a **medium priority** on this one, it would be much better, if people had a changelog window notification when a new version gets released, so everyone knows about new features.

Many people won't ever read GitHub nor the forums... Also version 3 had a similar popup.
