### ISSUE TITLE
Remember last sort order

### ISSUE THREAD

**Issue by DoonFreak** [DinoDevs/GladiatusCrazyAddon#68]
Hello, 

thank you for the update. The "Remember last sort order" doesn't work for the guild market. For the global market it works.

**Comment by GreatApo** [comment]
You are right. Seems that @DarkThanos missed something :P

**Comment by DoonFreak** [comment]
thanks for your reply. 
The bus with the missing shadow at the expi is still alive^^

**Comment by GreatApo** [comment]
Sort fixed, comit 4dbc2c7162efe555874ac74265cd7fa33c7bda40

About the shadow, yes i know, i just forget it when playing. So i always miss it :P

**Comment by GramThanos** [comment]
Sorry, I forgot the guild market :P

**Comment by GramThanos** [comment]
Sorry, I forgot the guild market :P

**Comment by GramThanos** [comment]
Sorry, I forgot the guild market :P

**Comment by GramThanos** [comment]
Sorry, I forgot the guild market :P

**Comment by GramThanos** [comment]
Sorry, I forgot the guild market :P

**Comment by DoonFreak** [comment]
If I put an Item in the guild market, the addon loose the sort order for this moment. If I go later to the guild market all is fine. Is it possible to fix this issue?
