### ISSUE TITLE
Auto / 1g switch don't show if there are no items in market

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#69]
Auto / 1g switch don't show if there are no items in market.
It shows up only if there is at least one item in market.

**Comment by GreatApo** [comment]
For some stupid reason... i did that on purpose...

**Comment by GreatApo** [comment]
Ready! Feature was also added in settings, comit 394ca8b3610cbf591f9741d25216bdafba67340c
