### ISSUE TITLE
Underworld, no food features on overview

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#7]
Some food features do not work on underworld.

![14958290_1204188936322093_2041516067_n](https://cloud.githubusercontent.com/assets/14858959/20043245/61f027ee-a492-11e6-93f3-0ee38d0f3be0.png)

Reported by @GreatApo

**Comment by GreatApo** [comment]
Food should be transparent+red when in underworld.

**Comment by GramThanos** [comment]
Implemented

Commits: 714945f47a583474d096b89b1397ec34d68810ed e46edd4ca5f85de26503858ad235a9c121f6f960
