### ISSUE TITLE
Auto /1 gold in clan market please ?

### ISSUE THREAD

**Issue by hexos1** [DinoDevs/GladiatusCrazyAddon#70]
Hey guys, first of all thanks for making our lifes easier ! 

There is a auto/1g option for the global market but I want to see the same option in the clan market as well since I dont want to store my items in normal market :) 

Thank you !

**Comment by hexos1** [comment]
Oh yes you are right, you have to put 1 item in there first  :) Well these guys are close to perfection :D

**Comment by GramThanos** [comment]
:P funny bug

**Comment by GreatApo** [comment]
Sorry guys, my mistake :p
