### ISSUE TITLE
[Feature Request] Remember auction last search and load it by default

### ISSUE THREAD

**Issue by hexos1** [DinoDevs/GladiatusCrazyAddon#71]
When you enter the auction, it lists all the weapons for you, but it would be awesome if it was "all items" instead of just "weapons"  when you first click it . Hope you guys can do that.

Thank you !

**Comment by GramThanos** [comment]
Since this is quite a load for the server, I don't think it is a good idea.

Don't forget that the current gladiatus servers have load problems.

**Comment by GreatApo** [comment]
But it could be a good idea remember what was searched here too.

**Comment by DarkSide666** [comment]
Yes remembering last used auction tab could be good, but loading all is a NO NO - slow and painful.

**Comment by brunoaugusto** [comment]
Have you ever loaded all items by yourself? Even without the add-on the game struggles badly to deliver them.

**Comment by GramThanos** [comment]
Remember last search would be nice.
Maybe a search history too.

**Comment by GramThanos** [comment]
Implemented, remember last search and load it by default.
Commit d0b867c1f531d6718f54f96fb6f592fc72d5ec6c

**Comment by GreatApo** [comment]
Done!

**Comment by brunoaugusto** [comment]
Awesome! :smile:
