### ISSUE TITLE
Settings button doesn't work

### ISSUE THREAD

**Issue by ElhadiEinstein** [DinoDevs/GladiatusCrazyAddon#72]
Hi ... I don't know if the probleme is just with me but since the last update the settings button doens't work 
when i press it nothing happens as it is empty 
and i use Chrome

**Comment by DarkSide666** [comment]
Works fine on my Chrome and GCA 4.0.3 version.

**Comment by ElhadiEinstein** [comment]
same probleme with firefox , 
and that's a picture of how the window appears when using the link 
( i play in arabic community )
but it can be linked to my computer ,,, looking throught it 

![image](https://user-images.githubusercontent.com/34983228/34919983-aacc1250-f96b-11e7-853e-c72e6cac309b.png)

**Comment by ElhadiEinstein** [comment]
The probleme has been solved, it because i added the GCA last update directly to a new browser , and saved page of settings disppeared 
but when i used the GCA 4.0.0 the settings re-appeared , and it was saved when updating to 4.0.3

**Comment by GreatApo** [comment]
Yes, it's a bug of settings after an improvement DarkThanos made in settings. I have fixed it.

Except from your solution you can also run the following code in the console (F12->Console):

gca_locale.active = 'en';

And then click the settings button without refreshing :)

I am not closing the issue, so others can see it before the next release.

**Comment by ElhadiEinstein** [comment]
Thank you very much 
i'll keep that solution in mind if needed before the next update

**Comment by gladBR** [comment]
I have the same problem
Clicking on settings does nothing

**Comment by GreatApo** [comment]
Answers above...

Releasing new version...
