### ISSUE TITLE
[Bug] Export and import data

### ISSUE THREAD

**Issue by gladBR** [DinoDevs/GladiatusCrazyAddon#75]
In version 4.0.4

The export and import part of the settings does not work

In export, click and nothing happens

On import, the ERROR message appears.

**Comment by GramThanos** [comment]
Have you tried the feature on the previus version?

**Comment by gladBR** [comment]
Yes, I installed the new version 4.0.4
When you click export, nothing happens

**Comment by gladBR** [comment]
Any solution?

**Comment by GramThanos** [comment]
None yet. :(

**Comment by GladBR2018** [comment]
In firefox it really does not work

Chrome is already running the export

The solution  , is to export in chrome, and import to firefox

**Comment by GramThanos** [comment]
I was searching the problem on Chrome :P I will try to find it on Firefox :D

**Comment by GladBR2018** [comment]
The problem continues, even though upgrading to version 4.0.5

**Comment by GramThanos** [comment]
Yes, thats why there is no info over it on the changelog :P
We haven't really worked on the addon the last few months due to the lack of free time.

**Comment by GramThanos** [comment]
The bug with the palyer's id is a posible cause 312ea49918eac97ebf5858b70e611cde6bb75217

**Comment by GramThanos** [comment]
Report issues about import and export on #93
