### ISSUE TITLE
Material drop chance translation string error

### ISSUE THREAD

**Issue by DoonFreak** [DinoDevs/GladiatusCrazyAddon#79]
Hi 
I don't know how to describe this issue, but you can have a look at the screenshot ;)

http://prntscr.com/i69ff6

Thanks
DoonFreak

**Comment by GreatApo** [comment]
It's an error related with a not found translation variable. I will take a look...

**Comment by DoonFreak** [comment]
thank you, only a little bug, so not very important.

**Comment by GreatApo** [comment]
Yeah! It doesn't matter, it's a bug so thanks for reporting!

**Comment by GreatApo** [comment]
I found many bug considering translations... actually translations were not working on the developer version...

Comit 18c8e00273417b65b9c3aaa6af7ea993748d9046
