### ISSUE TITLE
Settings have disappeared!

### ISSUE THREAD

**Issue by JAMESwocogo** [DinoDevs/GladiatusCrazyAddon#80]
Hello,

I have found a very strange bug and that is - I wanted to use different language and in order to go back to the original, English, I chose one blank space in languages menu and since then I can not go to the settings anymore. Everytime I try that I end up with a blank screen.

Now I have to delete my Add On data and try to set the whole thing again.

**Comment by ElhadiEinstein** [comment]
I had a similar problem once and i opened an issue about it 

try that solution given to me that time 

![image](https://user-images.githubusercontent.com/34983228/35571057-521989ea-05d1-11e8-8f30-c2a37345e14a.png)

**Comment by JAMESwocogo** [comment]
Thanks.

Anyway I just deleted cookies and set it up once again.

**Comment by GramThanos** [comment]
It was my mistake, GreatApo fixed it (18c8e00273417b65b9c3aaa6af7ea993748d9046), so we think it will be fixed on the next version (we just haven't found some time to release a version)
