### ISSUE TITLE
[Feature request] Alert for orange/red Items in the shops 

### ISSUE THREAD

**Issue by ElhadiEinstein** [DinoDevs/GladiatusCrazyAddon#81]
Hi ,, 

that's a feature request , to add a warning if an orange or red items (or even purple) appears in the shop 
because some times a player forget to check the shops, or maybe he finds that ennoying to check every shop box
or he can't find the time especially in the last fast servers with X5 speed

**Comment by GramThanos** [comment]
I think that we should not implement any other feature that creates a server request to check each bag.
We can save if you left any item in a shop, and warn the user if some time passed without rebuying it.

**Comment by brunoaugusto** [comment]
I agree with @GramThanos. If the player wants more purple/orange and even red (although much rarer) items to smelt, it's their responsibility to check the shops. The add-on is a helper, not a bot.

**Comment by FrutyX** [comment]
Implemented a different working solution in #292.

Closing this one.
