### ISSUE TITLE
[Feature Request] Shortcut for guild applications / auto choose rank

### ISSUE THREAD

**Issue by ElhadiEinstein** [DinoDevs/GladiatusCrazyAddon#82]
Hi 
i have a proposition to add a shortcut to guild applications, 
and auto choosing rank after accepting the application request  

because now that we're making 2 to 3 guild just for their storages , and that we're entering and leaving them everyday ,, it became really annoying to do all the clicks just to accept and to choose rank 

thank you for considering it ^_^

**Comment by GramThanos** [comment]
The rank select when accepting application was implemented.
