### ISSUE TITLE
Prevent Expedition/Arena/Provinciarum if HP is too low

### ISSUE THREAD

**Issue by brunoaugusto** [DinoDevs/GladiatusCrazyAddon#84]
This would be great to not waste an Expedition point or lose a fight you usually win in Arena/Provinciarum just because a few seconds before you clicked the button/links someone much stronger than you (I'm looking at you speed-servers') attacked and depleted your health.

And I believe this should be a configurable value because of the variety of Expedition Bosses. For example: Cassi, the first Expedition Boss from Britannia, is weak but has a huge armour rating, so anything above 1-1.5k of HP is enough to survive the messed formulas and beat him (assuming you're strong enough to even consider Britannia, of course), but this value doesn't work for Dracolich, the humongous Expedition Boss from the last area in Germania.

**Comment by GramThanos** [comment]
I like the idea, just a simple confirmation, We don't have boss stats so that we can not make it dynamic for each boss but just a basic limit (configurable from settings) would be just fine I think.

**Comment by brunoaugusto** [comment]
That's how I was thinking too. Just like the game does (custom modal optional, of course) but with a configurable value. Much better handled than the pathetic 25 points threshold defined by game's mechanics.

**Comment by GramThanos** [comment]
I think an automatic food eat feature is an over kill... You can do it yourself after canceling a warning modal notification.

It may also blacklist the extension. But you can suggest it at the gladiatus support directly if you think it is needed.

**Comment by FrutyX** [comment]
Note for future Gram or Apo:

Get the HP from header values, add it to the settings as slider, if HP smaller than the set slider, send a desktop notification.

Nothing automatic, GCA is not a bot.
