### ISSUE TITLE
[Question] Mute sound

### ISSUE THREAD

**Issue by tryllejens** [DinoDevs/GladiatusCrazyAddon#85]
is there a way to mute the adddon?

**Comment by GramThanos** [comment]
There is a sound icon on the bottom right corner of the screen, click it to toggle the sounds.

**Comment by brunoaugusto** [comment]
However, the right way to do it would be setting the add-on to not play any sound: Profile > Gladiatus Crazy Add-on Settings > Sounds > Enable sound system (OFF) -OR- Mute/Unmute sounds (ON).

You can also mute only the tab in which the game is opened by third-clicking on it/them and choosing 'Mute'
