### ISSUE TITLE
[Feature Request] Search a player in battle reports

### ISSUE THREAD

**Issue by mim1985** [DinoDevs/GladiatusCrazyAddon#88]
Hi. I have a sugestion, to put a search option of a player in battle reports (provinciarum arena/ turma). For example if you just attack a player in prov.turm and you took 100k gold from him, if you have that option to search him in reports you can find if he attacked you in arena so you can gave revenge...so another 100k gold you'll take...

**Comment by GramThanos** [comment]
This would require to crawl the reports pages and we avoid such actions as it generates traffic to the gladiatus servers.
