### ISSUE TITLE
[Bug] Unable to send quick messages

### ISSUE THREAD

**Issue by brunoaugusto** [DinoDevs/GladiatusCrazyAddon#89]
Today I needed to clear my browser's cookies in order to test the implementation of something that would use cookies — which doesn't matter — two times.

The first I did I forgot to backup my settings and I had to reconfigure everything by hand. The second time I remembered (\o/) of backing them up and after I did what I needed I restored them as expected but now every time I try to use that small box for quick messages right below the timers I receive a red box saying just "No data", like if I was trying to post something without type anything.

Just in case, clearing out my cookies and logging back in (and then reconfiguring manually like before) seemed to solve the issue as I could message my Guild perfectly as usual o.O

I'll mark #75 because it seems to be related

**Comment by GramThanos** [comment]
The addon cache the guild's players so that it does not spam the server with requests in order to get them.

I think it updates the cache once per day or something, maybe we needed to add a button on the settings, and inform the player about it on error.

**Comment by brunoaugusto** [comment]
Makes sense. Could, perhaps, something related to this process to be bugged somehow when involving the Export/Import feature?

**Comment by GramThanos** [comment]
Not, but export only exports your setting, not your cache (there is no point in saving them).

**Comment by GreatApo** [comment]
Too old, closed
