### ISSUE TITLE
Enable developer options/mode

### ISSUE THREAD

**Issue by bla1215** [DinoDevs/GladiatusCrazyAddon#91]
How do I enable developer mode/options? I want this add-on to show me what resources will I possibly obtain if I melt the object, when i point my cursor at this object. I know it is possible, and you have to enable it in options, yet somehow i can't set it up. Ver. 4.0.5.

Sorry if i'm posting in the wrong place. Any help appreciated. Cheers

**Comment by GramThanos** [comment]
We haven't implemented such a feature.

**Comment by bla1215** [comment]
Ok, then I've been lied to. 
Thank you for your help, you can delete the thread cos its not an issue then, I guess. 

And by the way, thanks for the fantastic addon, I love it and it works superb.
