### ISSUE TITLE
[Feature Request] Save gladiators to attack them on arena(s)

### ISSUE THREAD

**Issue by Thetawaves666** [DinoDevs/GladiatusCrazyAddon#92]
The idea behind this is to make a check of specific players to attack, when the opportunity appears on provinciarum. Can also be used to make a follow of those players that seems to be quite actives in Gladiatus. It can be made in any of the following two options:

1. The possibility to add players (nickname and province) on a small window, and save them. When you enter the arena or turma and, someone of the 5 players to attack matches any of the players added previously; make the name glimmer, or anything else to let the player know there is a match.

2. The possibility to make a 2nd "notes" windows, that pops when you enter turma or arena, where you can make notes.

Any posteriors idea are welcome.

**Comment by GramThanos** [comment]
Seems do-able.

**Comment by GramThanos** [comment]
Feature was implemented.
Commit c0e88d13c7c0d9adbe44248b5d61d5d95a2ab476

![image](https://user-images.githubusercontent.com/14858959/44840336-79bfc080-ac49-11e8-9a7b-0a992562a912.png)

![image](https://user-images.githubusercontent.com/14858959/44840404-a1af2400-ac49-11e8-8f15-5557c41a5fee.png)

![image](https://user-images.githubusercontent.com/14858959/44840610-12564080-ac4a-11e8-89e7-8ea3a3610212.png)

**Comment by Thetawaves666** [comment]
Looking pretty good. Thanks for going on in making my idea a reality. 
Maybe can it be too much, to choose from 2 o 3 colors?

**Comment by DoonFreak** [comment]
great idea. If we get 2 or 3 colors it is also possible to make a friend list for your guildmates on other servers, for example.

**Comment by GramThanos** [comment]
I will add color options.

Guild members from other servers (if they have the same name) are highlighted, we scripted it last week 79e3837ea9ffed5795f6169b70d992b7e23b32db

**Comment by DoonFreak** [comment]
sounds great, thank you. When can we get this feature?

**Comment by GramThanos** [comment]
Yeah it was misspelled...

**Comment by GramThanos** [comment]
Color support added 23cd7474c4e63aa3e756a1fbc127ce3f8e808e09

![image](https://user-images.githubusercontent.com/14858959/45453519-b7acf200-b6e9-11e8-929f-0eb2c57646ba.png)

![image](https://user-images.githubusercontent.com/14858959/45453555-cf847600-b6e9-11e8-9a94-870e895dad00.png)

**Comment by GreatApo** [comment]
Target list... GreatApo... BRING IT ON!!!

**Comment by GreatApo** [comment]
S
