### ISSUE TITLE
[Bug] Improve export and import data

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#93]
Data export don't gather all the addon's data.
Also maybe we can add selection for categories.
Data clean up can clean up gladiatus data too.

**Comment by GreatApo** [comment]
Request to include in exported data:
- "target list" data

**Comment by GramThanos** [comment]
Added on commit 19947d9eee1da56ae75c3fb10d802295a4c6f134
