### ISSUE TITLE
[Bug] Achivements category percent

### ISSUE THREAD

**Issue by GramThanos** [DinoDevs/GladiatusCrazyAddon#94]
The percent shown on achivements is not correct.

**Comment by Emefar** [comment]
I agree with you.
It should be 100% : ![image](https://user-images.githubusercontent.com/36764954/46570519-1a528000-c96e-11e8-92d8-9e1353784994.png)

**Comment by GramThanos** [comment]
Fixed 927f089847e6daff68a9339746569df7e2ffa3d9
