### ISSUE TITLE
(Website) Highscore System Bug

### ISSUE THREAD

**Issue by Emefar** [DinoDevs/GladiatusCrazyAddon#95]
**Describe the bug**
Highscore system not working correctly. Gladiatus changed link system but you are using old system. Please update s5.en.gladiatus.... -> s5-en.gladiatus.... You should change " . " to " - " for the whole system to work.
**Screenshot**
https://i.hizliresim.com/7DOdYP.png

**Comment by Emefar** [comment]
And i am playing Turkey servers. Signature section have 30 servers but we have 36 servers. And Signature section is not working also. Same bug. ( "-" and "." bug)

**Comment by GramThanos** [comment]
The website is under reconstruction 😆 , we only update the download links.

**Comment by Emefar** [comment]
But maybe you can fix minor bugs for now :D Just - and . bugs :D

**Comment by Emefar** [comment]
I'm really curious about highscore..

**Comment by GramThanos** [comment]
Hahaha, it shows only the people that used it, so it is not accurate.

**Comment by Emefar** [comment]
But you can add refresh button on developer side. When you click button, scan all servers and display data. I trust you. You can do this :D

**Comment by GramThanos** [comment]
😆

31 countries requests to get the servers
262 servers * max 20 pages on the high score = max 5240 requests
5240 requests * 250ms = 1310000 ms = 21.8 min

A refresh button that will start a 10-20 minutes action is a bad idea.

**Comment by GramThanos** [comment]
Well not today :P , maybe in the future we develop an other global high score.

**Comment by Emefar** [comment]
You can press the refresh button monthly, not everyday :D I think good idea :P

**Comment by GreatApo** [comment]
Converted to global arena highscore
